### ISSUE TITLE
Sensor por cada hora del dia anterior

### ISSUE THREAD

**Issue by yevon** [uvejota/homeassistant-edata#1]
Buenas! Me he instalado la extensión también para ir probando. Lo suyo seria tener un sensor que actualizara cada hora mostrando el consumo de la misma hora pero del dia anterior, para así poderlo integrar con el nuevo panel de energia de home assistant.

La idea seria un sensor que daria esta info:

Actualizado a las  2021-08-12T13:00:00+00:00, pero mostrando:

state_class: measurement 
last_reset: 2021-08-11T13:00:00+00:00 
unit_of_measurement: kWh
estado: Consumo en kWh

**Comment by yevon** [comment]
Vale no he dicho nada, veo que datadis no se actualiza tanto, en mi caso por ejemplo solo puedo ver datos anteriores al dia 9. Y también  veo que datadis está bugged, le tienes que poner startDate i endDate del mismo dia, sino te devuelve: 

can't parse JSON.  Raw result:

Parámetro requerido en estado vacío, con formato erróneo, o con valores fuera de rango / Parámetro de ordenación erróneo

Este error lo he visto en home assistant i queria ver porque era

**Comment by uvejota** [comment]
Hola, efectivamente como dices la consulta de maxímetro o pones el rango perfecto o devuelve un error, es mejorable, pero mirando fechas de los contratos puede sacarse el rango "adecuado". En teoría debe estar corregido en la v0.1.2.

Sobre la integración con el nuevo panel de energía de home assistant, lo veo complicado ya que sólo disponemos del histórico, y según la pereza de la distribuidora... en cualquier caso voy a echarle un ojo a ver qué se puede hacer.

¡Un saludo y gracias por el feedback!

**Comment by uvejota** [comment]
@SirMartin yo he estado echándole un ojo, y no tengo claro si puedo añadir algún parámetro tipo 'last_reset' para que vaya dibujando las barras aunque no sean temporalmente equiespaciadas.

También tengo pendiente ver si puedo inyectar datos en el recorder a pasado (aunque sea para corregir el delay de 1 día en la toma de los datos).

**Comment by SirMartin** [comment]
Aqui me pillas completamente, porque la verdad que de Home Assistant controlo muy muy poquito, estoy todavía pasándome de Openhab que es lo que he usado en casa estos últimos años, así que realmente no se lo que es posible o no. Si necesitas alguna ayuda, o que pruebe cosas, yo ahora en un par de semanas tendré algo más de tiempo.

**Comment by uvejota** [comment]
Explico un poco más en:

https://github.com/uvejota/homeassistant-edata/issues/22#issuecomment-921675278

**Comment by uvejota** [comment]
Seguimos esto en https://github.com/uvejota/homeassistant-edata/issues/22#issuecomment-921675278
