### ISSUE TITLE
Consumo actual

### ISSUE THREAD

**Issue by unixtall** [uvejota/homeassistant-edata#100]
Hola, ¿hay alguna forma de ver el consumo del día? Lo quiero poner en energía.

**Comment by uvejota** [comment]
Desgraciadamente no se puede ver el consumo en tiempo real, es una limitación de Datadis (de las distribuidoras en realidad). No leen datos en tiempo real, sino que cada 24h aproximadamente van facturando el consumo del día anterior (según les viene en gana en realidad).

**Comment by darguez** [comment]
Estaba este issue relacionado que abordaba también este tema: https://github.com/uvejota/homeassistant-edata/issues/51
