### ISSUE TITLE
Off topic: Consumo agua (telelectura)

### ISSUE THREAD

**Issue by mabusdogma** [uvejota/homeassistant-edata#101]
Hola, hay algo que suena interesante pero al no ser informático no sé por dónde empezar: la telelectura permite lo mismo con el agua ahora, al menos en Barcelona.

![Screenshot_20220715-161605523](https://user-images.githubusercontent.com/19146242/179244909-52bf9e19-d4ae-4b50-b094-935f38a652dd.jpg)

Cómo podría hacer que estos datos, que aparecen en la página principal, al poner mi nombre de usuario y contraseña, pasaran en gráficas a Home Assistant?

La página es
https://www.aiguesdebarcelona.cat/es/area-clientes

**Comment by uvejota** [comment]
Sería muy chulo, pero al no residir en Barcelona tendría muy complicado el testeo. 

En cualquier caso, si no ofrecen una API habría que hacer scrapping de la web (leer el código fuente, buscar patrones de contenido y extraer los datos), lo cual sería difícil de mantener (este tipo de webs cambian con relativa frecuencia).

Lo siento

**Comment by mabusdogma** [comment]
No pasa nada, yo aprendo poco a poco, a ver si puedo ayudar

**Comment by amaciasf** [comment]
Hola! Mi telecontador de agua también reporta a una web que no tiene API pública y la única manera de obtener datos es haciendo scrapping. HA-multiscrape [1] es un complemento que facilita mucho este trabajo, pero como dice @uvejota, si la web cambia, es posible que deje de ir el sensor hasta que actualices la configuración de multiscrape.

Saludos!

[1] https://github.com/danieldotnl/ha-multiscrape

**Comment by carlos-48** [comment]
Yo estoy intentado configurar desde hace semanas el componente `ha-multiscrape` para leer en la Página de Aguas de Valencia, pero no consigo que funcione por el tema del login. En cuanto tenga configuración que funcione, la compartiré.

**Comment by carlos-48** [comment]
> Yo estoy intentado configurar desde hace semanas el componente `ha-multiscrape` para leer en la Página de Aguas de Valencia, pero no consigo que funcione por el tema del login. En cuanto tenga configuración que funcione, la compartiré.

Finalmente, en lugar de una integración completa, hice un sensor desde el `configuration.yaml`, ya que para mis conocimientos es mucho más sencillo.

Además no use el `ha-multiscrape` porque no podía hacerlo funcionar por un tema de sesiones y cookies necesarias para el login, así que usé el sensor `command-line`.

Os dejo aquí enlazado lo que he hecho, por si alguien se anima... https://github.com/carlos-48/homeassistant-aguasdevalencia

Básicamente, con las herramientas de desarrollador de cualquier navegador puedes in analizando las consultas que hace el navegador, para tratar de replicarlas con Home Assistant.

Todavía hay mucho por mejorar, pero no tengo tiempo. Tampoco conocimientos, pero me encanta aprender así que eso no es el problema, mi problema es la falta de tiempo para aprender+probar+error+corregir+hacer funcionar.
