### ISSUE TITLE
ERROR (SyncWorker_21) [edata.connectors] DatadisConnector: unknown error while retrieving token, got {"timestamp":"2022-08-09T09:48:29.877+0000","status":500,"error":"Internal Server Error","message":"Bad credentials","path":"/nikola-auth/tokens/login"}

### ISSUE THREAD

**Issue by Daru-man** [uvejota/homeassistant-edata#102]
Buenas uvejota,

Primero, gracias por la integración.
Me gustaría comentarte, que no consigo sincronizar. Da el siguiente error:
2022-08-09 11:48:29.903 ERROR (SyncWorker_21) [edata.connectors] DatadisConnector: unknown error while retrieving token, got {"timestamp":"2022-08-09T09:48:29.877+0000","status":500,"error":"Internal Server Error","message":"Bad credentials","path":"/nikola-auth/tokens/login"}

Y en datadis me aparece una autorización pendiente. Está relacionado?
![image](https://user-images.githubusercontent.com/97914522/183629106-304f431e-ca1f-43cc-86af-699d1cbd6740.png)

¿Le debo dar algún valor?

Disculpa las molestias,

JFRico

**Comment by musantro** [comment]
El error 500 con `Bad credentials` suena a que no has configurado bien el usuario y la contraseña al configurar la integración en HA. El usuario es tu DNI (yo la letra la pongo en mayúsculas, no sé si es relevante).

Prueba a chequearlo por si te sirve.

Lo segundo que comentas es esta [esta página](https://datadis.es/private/api-private), eso es un lugar para probar la API. Si quieres hacer pruebas, tienes que primero hacer un POST a `/nikola-auth/tokens/login` y el resultado es un token de muchos caracteres que tienes que copiar y pegar en `Value` en la captura de pantalla que has mandado. Y con eso ya puedes hacer pruebas y consultas a la api en los diversos GET. Pero no tiene nada que ver con la integración en sí.

**Comment by uvejota** [comment]
Seguimos la discusión en #103 :)
