### ISSUE TITLE
get-consumption-data from api getting always error 500

### ISSUE THREAD

**Issue by musantro** [uvejota/homeassistant-edata#103]
Buenas,

Abro issue para investigar un poco porque me parece raro que el 100% de las requests devuelva siempre un 500:

> Logs en Home Assistant:
```
https://datadis.es/api-private/api/get-consumption-data?cups=ESXXXXXXXXXXXXXXXXXX&distributorCode=5&startDate=2021/08/01&endDate=2022/08/11&measurementType=0&pointType=4& 

returned 

{
  "status": 500,
  "error": "INTERNAL_SERVER_ERROR",
  "message": "500 Internal Server Error",
  "timestamp": "2022-08-11T12:10:44.091+0200"
} 

with code 500
```

He hecho pruebas con el [Swagger que ofrece Datadis en su página](https://datadis.es/private/api-private), y aunque a veces da un 500, normalmente da un 200, usando el mismo request.

Estoy usando Home Assistant versión Docker en una Raspberry pi, versión HA 2022.8.2.

¿Puede ser algo de los headers que no cuadre? Seguiré investigando por si puedo dar alguna información extra.

Gracias en cualquier caso a los contribuyentes por el plugin!

**Comment by musantro** [comment]
Alguna vez da este 500:

```json
{
  "status": 500,
  "error": "INTERNAL_SERVER_ERROR",
  "message": "Unable to acquire JDBC Connection; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection",
  "timestamp": "2022-08-11T07:07:31.153+0200"
}
```

Esto parece que es más del lado de la API de Datadis y que poco podemos hacer, pero por si puede dar a alguien alguna idea.

**Comment by jbenleo** [comment]
Buenas, tengo el mismo error (el primero). He probado desde la interfaz de datadis y funciona correctamente. He hecho alguna prueba con el componente e-data y parece que saca también el error 500 pero sólo con rangos de fechas grandes (parece que se vuelve un poco loco el servidor). No sé si es posible configurar una fecha de inicio mas cercana en el tiempo y que el start date no sea el año pasado.

**Comment by daniko** [comment]
Hola, ¿puede ser que hayan capado el acceso API?

Estoy en la [página de registro de datadis](https://datadis.es/registry), y pone lo siguiente:
"Solicito acceso a datos vía API (Solo disponible para NIF con formato CIF) "

Es un checkbox que en mi caso esta gris (no clicable) porque obviamente soy persona fisica (NIF) y no empresa (CIF).

**Comment by uvejota** [comment]
> Buenas, tengo el mismo error (el primero). He probado desde la interfaz de datadis y funciona correctamente. He hecho alguna prueba con el componente e-data y parece que saca también el error 500 pero sólo con rangos de fechas grandes (parece que se vuelve un poco loco el servidor). No sé si es posible configurar una fecha de inicio mas cercana en el tiempo y que el start date no sea el año pasado.

Voy a probar esto, tardará más en obtener los datos, pero igual así no casca. En cualquier caso, creo que es una especie de baneo por parte de Datadis (que también os digo, si les molesta las consultas grandes, que no las permitan e informen del tamaño máximo...).



> Hola, ¿puede ser que hayan capado el acceso API?
> 
> Estoy en la [página de registro de datadis](https://datadis.es/registry), y pone lo siguiente: "Solicito acceso a datos vía API (Solo disponible para NIF con formato CIF) "
> 
> Es un checkbox que en mi caso esta gris (no clicable) porque obviamente soy persona fisica (NIF) y no empresa (CIF).

Esa casilla es para la API pública, este complemento usa la API privada (habilitada por defecto).

**Comment by uvejota** [comment]
> Buenas, tengo el mismo error (el primero). He probado desde la interfaz de datadis y funciona correctamente. He hecho alguna prueba con el componente e-data y parece que saca también el error 500 pero sólo con rangos de fechas grandes (parece que se vuelve un poco loco el servidor). No sé si es posible configurar una fecha de inicio mas cercana en el tiempo y que el start date no sea el año pasado.

La versión 2022.09.1 (aún beta) intenta primero descargar el último año del tirón, si falla intenta descargar mes a mes (rangos de 30 días me parecen razonables...)

También se ha mejorado la detección de la fecha de inicio de contrato, había casos puntuales en los que podía fallar.

Hacer muchas peticiones en poco tiempo también hace que el servidor falle (códigos 50X), así que si os ponéis a probar a conciencia es posible que os suceda. Supongo que es un tipo de baneo/límite que aplican por usuario.
