### ISSUE TITLE
Consumo del último día registrado en los atributos de la entidad

### ISSUE THREAD

**Issue by darguez** [uvejota/homeassistant-edata#105]
Viendo que tal como llegan los datos casi nunca existen datos de ayer, quizá sería una buena idea añadir en los atributos de la entidad principal los correspondientes a los datos del último día registrado (la fecha ya está indicada en `last_registered_kWh_date`).

Podría ser por ejemplo:
- last_registered_day_kWh
- last_registered_day_hours
- last_registered_day_p1_kWh
- last_registered_day_p2_kWh
- last_registered_day_p3_kWh
- last_registered_kWh_date <-- ya está

**Comment by alexsalvo1** [comment]
Tiene mucho sentido tu propuesta!

**Comment by uvejota** [comment]
Um, el cambio sería inmediato... ¿Decís reemplazándolo por el consumo del día anterior? ¿O añadiendo esos nuevos y dejando los que ya existen como están?

**Comment by darguez** [comment]
Se podría dejar igualmente yesterday por si en algún momento aparecen datos.

**Comment by uvejota** [comment]
En principio no tengo nada en contra de implementarlo, me preocupa que haya "demasiados" atributos en el sensor, pero bueno, es cuestión de estética (tampoco creo que nadie visualice los datos de edata así)

**Comment by Danieldiazi** [comment]
Al final si algún dia implementan "yesterday" tendrá los mismos valores que "last_registered", igual queda más limpio quitar directamente yesterday. 


Es decir: Si no hay datos de ayer "yesterday" no aporta nada. Si hay datos de ayer, esos datos ya están en "last_registered". La conclusión es que "yesterday" no aporta nada.


 Por dar mi opinión, simplemente!

**Comment by uvejota** [comment]
> Al final si algún dia implementan "yesterday" tendrá los mismos valores que "last_registered", igual queda más limpio quitar directamente yesterday.
> 
> Es decir: Si no hay datos de ayer "yesterday" no aporta nada. Si hay datos de ayer, esos datos ya están en "last_registered". La conclusión es que "yesterday" no aporta nada.
> 
> Por dar mi opinión, simplemente!

Yo creo que opino similar, lo veo redundante. Lo pongo a la cola cuando termine de resolver algunos bugs :)

**Comment by MikelMirror** [comment]
Yo creo que NO es redundante, ya que, al menos en mi caso, rara vez obtengo los datos de día - 1, normalmente es día - 3 o 4 (o más).

Y last_registered_kwh_date contiene la fecha/hora de los últimos datos cargados, que no tienen por qué ser los de ayer ni los de hoy.

En mi opinión dejaría día - 1 para la gente que lo utiliza y le va bien y anadiriria 3 atributos o entidades:

-Fecha/hora última respuesta ok de dadadis de la que tengamos constancia, ya que las respuestas ok de datadis que haya registrado hass como timeout no la conocemos.
-Fecha/hora última consulta lanzada a datadis.
-Periodo de consulta, actualmente cada 24h.

Las dos últimas nos ayudarán a entender cuando se volverá a lanzar la consulta y deberían ser modificables, por si queremos ajustarlas manualmente.

**Comment by uvejota** [comment]
Esto está implementado en 2022.11.2 (ya liberada).

Gracias por la sugerencia.
