### ISSUE TITLE
Error tras la última actualización

### ISSUE THREAD

**Issue by jgarridoalcazar** [uvejota/homeassistant-edata#106]
Buenos días:

Llevaba un tiempo sin actualizar homeassistant-edata (desde abril o mayo) y funcionando correctamente. Tras instalar la versión actual me ha dejado de funcionar la integración mostrando el siguiente mensaje en el log:

> Unable to prepare setup for platform edata.sensor: Platform not found (cannot import name 'get_instance' from 'homeassistant.components.recorder' (/usr/src/homeassistant/homeassistant/components/recorder/__init__.py)).

Mi versión de HA es 2022.3.2. ¿Es posible que el error venga de no haber actualizado HA en este tiempo?

Saludos y muchas gracias por esta gran integración.

**Comment by uvejota** [comment]
Um, apostaría que sí...

El problema es que a los usuarios que han actualizado les saltaba un warning diciendo que se utilizara el get_instance... tengo que ver si no es mucho jaleo mantener ambas "versiones"

**Comment by jgarridoalcazar** [comment]
Bueno, no tardaré mucho en actualizar. Lo tenía pendiente desde hace un tiempo y esto puede ser una motivación. Si ves que es mucho follón no te preocupes.

**Comment by uvejota** [comment]
En cualquier caso haces bien en avisar :)

Si no lo corrijo tendré que fijar una nueva versión mínima de HA

**Comment by jgarridoalcazar** [comment]
Perfecto. Vuelve a funcionar con la rama dev. Muchas gracias!!

**Comment by jgarridoalcazar** [comment]
Ummmm... pues no, parece que ha salido algún problema más.

Al poner la rama dev me cargaba los datos diarios, pero no los atributos. He cambiado el nombre de los ficheros .storage y reiniciado HA para que volviera a recargar los datos, pero me ha salido un nuevo error, que parece que también puede estar relacionado con lo mismo.

> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/edata/coordinator.py", line 138, in _async_update_data
>     await self.clear_all_statistics()
>   File "/config/custom_components/edata/coordinator.py", line 229, in clear_all_statistics
>     all_ids = await self.hass.data[DATA_INSTANCE].async_add_executor_job(
> AttributeError: 'Recorder' object has no attribute 'async_add_executor_job'

**Comment by uvejota** [comment]
Voy a ver, con eso creo que ya sé cómo arreglarlo :)

**Comment by uvejota** [comment]
Bueno, ahí va mi segundo intento, está en la rama dev :)

**Comment by jgarridoalcazar** [comment]
Parece que sigue habiendo alguna llamada a función que no está en las versiones antiguas.

> Unexpected error fetching edata_xt0f data: 'HomeAssistant' object has no attribute 'get_session'
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/edata/coordinator.py", line 144, in _async_update_data
>     await self.clear_all_statistics()
>   File "/config/custom_components/edata/coordinator.py", line 249, in clear_all_statistics
>     await get_db_instance(self.hass).async_add_executor_job(
>   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 703, in clear_statistics
>     with session_scope(session=instance.get_session()) as session:  # type: ignore[misc]
> AttributeError: 'HomeAssistant' object has no attribute 'get_session'

**Comment by uvejota** [comment]
Creo que ya sí, he hecho algunas pruebecillas y parece que anda. 

Ese último error ha sido fallo mío... reemplacé más cosas de las que debía.

**Comment by jgarridoalcazar** [comment]
Ahora sí. Todos los datos parece que se están recuperando correctamente.

Muchas gracias de nuevo por el trabajo.
