### ISSUE TITLE
Varios Cups

### ISSUE THREAD

**Issue by fateton** [uvejota/homeassistant-edata#109]
Hello people:

Any solution to put several CUPS? I tryied cups: !secret my_cups cups1: !secret my_cups1 but this not worked

**Comment by uvejota** [comment]
Try to configure it through the user interface. 

YAML config is deprecated.

**Comment by fateton** [comment]
Sorry to reopen issue . And thanks a lot for your job.

But as you know password and cup would be defined via sensor.yaml and datadis.yaml as you mentioned in instalation in 
![image](https://user-images.githubusercontent.com/94257838/191820668-f5d257e4-ac98-46cb-8d6b-86c1af6bb08c.png)

And if I include other cups in this datadis.yaml dont work

**Comment by fateton** [comment]
To clarify I already have the two cups include in the integration 
![image](https://user-images.githubusercontent.com/94257838/191827450-3683ec38-d6e4-4148-bb30-8458eeea170d.png)

But the sencond dont work

**Comment by uvejota** [comment]
Both should work after a while with your current UI configuration. ¿Could you check home assistant logs?

YAML configuration is no longer needed (after v2022.01.0) and you should remove it from configuration.yaml since it can lead to configuration errors.

**Comment by fateton** [comment]
Hello uvejota thanksyou for your reply.

I removed edata data (user and password)  in configuration.yaml . I removed edata integration. I restored HA and re-installed edata integration.

The CUPS that was working before continued working.

But the second not-

My log 

![imagen](https://user-images.githubusercontent.com/94257838/192247860-92ecbf92-6a45-41d6-b561-86e10219b5f0.png)
![imagen](https://user-images.githubusercontent.com/94257838/192247951-55b80380-2f83-497e-94cb-6dc3cb384178.png)
![imagen](https://user-images.githubusercontent.com/94257838/192248036-5bdf5ff9-a40a-47ce-ae76-4c508f7c30b8.png)
![imagen](https://user-images.githubusercontent.com/94257838/192248159-39c2f399-324a-45ad-a5d8-287d504ec342.png)
![imagen](https://user-images.githubusercontent.com/94257838/192248227-850fb530-41b0-4898-aeae-c0097ef224c4.png)

**Comment by fateton** [comment]
One comment i check the CUPS with the s-distribucion web and is ok.
