### ISSUE TITLE
Gráfico con PVPC "N/A"

### ISSUE THREAD

**Issue by frodix** [uvejota/homeassistant-edata#11]
Hola, lo primero agradecerte esta integración, es una pasada!

A la hora de poner el gráfico del mes actual y el mes anterior, el importe de la factura me sale como "N/A", no sé qué estoy haciendo mal.

Gracias
![image](https://user-images.githubusercontent.com/27883894/131527535-f108a24d-b3b0-498d-81a0-b28945da4a62.png)

**Comment by uvejota** [comment]
Hola, tienes que añadir `experimental: true` en la configuración, no está bien especificado en la documentación porque está en fase muy "experimental" jeje.

Un saludo, ¡ya me dices!

**Comment by frodix** [comment]
Perfecto, ahora sí! Gracias.
Para ser muy "experimental" está genial.
Para futuras mejoras, podrías dar la opción a poner el ciclo de facturación en un determinado día del mes distinto al mes natural?
Gracias

**Comment by uvejota** [comment]
Hola, sí, lo tengo pensado junto con otras cosas chulas, a ver si saco un poquito de tiempo :-)

¡Gracias por la sugerencia!
