### ISSUE TITLE
coste por Kw contratado p1/p2 duda

### ISSUE THREAD

**Issue by Ie0nard0** [uvejota/homeassistant-edata#110]
Buenas! gracias por incluir el coste personalizado, tengo una duda, mi compañia me pasa el precio de las potencias por día:
Precio potencia P1: 0.10161 € kW/día.
Precio potencia P2: 0.030449 € kW/día

como debemos incluir este dato?
gracias

**Comment by uvejota** [comment]
Buenas, basta con multiplicar por 365 cada uno de los dos precios.
