### ISSUE TITLE
No se ven los costes

### ISSUE THREAD

**Issue by mtk1976** [uvejota/homeassistant-edata#115]
No consigo que se vean los costes en la pantalla de energia. 
He intentado quitar el dispositivo, volver a ponerlo. Lo del reset que indicas en la explicación y nada.
<img width="1213" alt="Captura de pantalla 2022-10-09 a les 11 09 15" src="https://user-images.githubusercontent.com/6632062/194748308-512b0fae-2e3c-4195-a695-0e8f28fc8f17.png">

**Comment by mtk1976** [comment]
Vaya, creo que era un problema de configuración del panel de energia.
Por lo que entendi, solo hay que poner un coste al consumo porque es la suma de los tres.
Por favor, corrigeme si me equivoco.

**Comment by MarcoEnd** [comment]
Yo he tenido el mismo problema. Para resolverlo:
- Busca en "herramientas para desarrolladores" pestaña "Estadísticas" los 4 digitos del CUPS
- la entidad tiene el nombre XXXX eur cost (edata:xxxx_cost o edata:xxxx_p1_cost, etc.)
- En ajustes/panales de control/energía en la parte "Red eléctrica" busca por XXXX p1_kWh consuption y al lapiz. Elige la opcion "Usar una entidad que realiza un seguimiento de los costes totales" y busca por la entidad de costes "XXXX eur cost".
- guardar y te salen los costes

**Comment by mtk1976** [comment]
No me sale la entidad edata:xxxx_p1_cost, pero si que sale la de eur_cost.
El resto es exactamente como indicas, me ha funcionado perfecto.
