### ISSUE TITLE
Invocaciones repetidas antes de 24horas

### ISSUE THREAD

**Issue by mcarlosro** [uvejota/homeassistant-edata#116]
Hola,

Parece que con la nueva API no se puede repetir peticiones hasta 24 horas después de la última.

2022-10-25 13:02:18.297 ERROR (SyncWorker_4) [edata.connectors] https://datadis.es/api-private/api/get-consumption-data?cups=XXXX&distributorCode=8&startDate=2022/10/23&endDate=2022/10/24&measurementType=0&pointType=5& returned Consulta ya realizada en las últimas 24 horas.  with code 429
2022-10-25 13:02:18.363 ERROR (SyncWorker_4) [edata.connectors] https://datadis.es/api-private/api/get-max-power?cups=XXX&distributorCode=8&startDate=2022/10&endDate=2022/10& returned Consulta ya realizada en las últimas 24 horas.  with code 429

¿Alguna solución para esto? Llevar un control de las llamadas hechas y sus resultados?? La verdad que esta limitación no tiene sentido para una API.

Gracias

**Comment by uvejota** [comment]
Buenas, necesito un par de días para implementar alguna "solución".

Que ya la hay, vaya, periódicamente se piden los datos que faltan... y ese periódicamente es cada hora. Basta con cambiarlo a cada 24. Esto inevitablemente va a retrasar aún más la aparición de los datos en la integración.

Hay más cambios en la API, ahora sólo se pueden pedir meses enteros (no rangos de días)...

La verdad, si quieren que no utilicemos la API, que no la pongan. 12 consultas diarias por usuario no es ninguna barbaridad, y la única consulta relativamente grande es la primera, el resto son incrementales de un día.

**Comment by mcarlosro** [comment]
Muchas gracias por tu respuesta y dedicación. Es un trabajo extraordinario.

Coincido con tu opinión sobre el uso de la API. Debe ser que no están dimensionados correctamente. Una lástima.

Quedo a la espera de la actualización.

Gracias de nuevo

**Comment by Danieldiazi** [comment]
> Buenas, necesito un par de días para implementar alguna "solución".
> 
> Que ya la hay, vaya, periódicamente se piden los datos que faltan... y ese periódicamente es cada hora. Basta con cambiarlo a cada 24. Esto inevitablemente va a retrasar aún más la aparición de los datos en la integración.
> 
> Hay más cambios en la API, ahora sólo se pueden pedir meses enteros (no rangos de días)...
> 
> La verdad, si quieren que no utilicemos la API, que no la pongan. 12 consultas diarias por usuario no es ninguna barbaridad, y la única consulta relativamente grande es la primera, el resto son incrementales de un día.

Justo han enviado un correo hace unos dias, titulado "Mejora API" en el que comentan esto:

> No se permitirán repetir llamadas que generen errores provocados por parte del usuario tales como parámetros incorrectos, formato erróneo, no disponer de autorización, etc... Por favor, tenga en cuenta de que si necesitan los datos, éstos no podrán volver a ser consultados hasta que no hayan pasado 24 horas. Les recomendamos que guarden sus datos. 

Es una pena, porque la integración es muy útil, y el API que ofrecían permitía sacar todo su potencial, y ahora lo ponen más dificil. No sé si son conscientes de todo lo que aporta esta integración y el valor añadido que para ellos tiene, pues creo que les da una buena imagen.

**Comment by jgarridoalcazar** [comment]
A mí al menos no me ha cargado ningún dato nuevo desde la madrugada del domingo al lunes, cuando empezó a salir ese error. No sé si es por seguir haciendo consultas en menos de 24 horas, o porque da error la consulta, pero apostaría a lo primero.

**Comment by uvejota** [comment]
@jgarridoalcazar la consulta ahora es diferente (hay que pedirle meses completos), tengo que actualizarla, estoy ultimando algunas verificaciones :)

**Comment by uvejota** [comment]
Esto debería estar resuelto en la release 2022.10.1

**Comment by mcarlosro** [comment]
Confirmado. Ya funciona

Muchas gracias por tu esfuerzo

**Comment by jgarridoalcazar** [comment]
Muchas gracias. Realmente lo de sólo permitir consultar cada 24 horas no es tanto problema si las consultas van bien, ya que los datos de Datadis no se actualizan mucho más.

**Comment by adrz95** [comment]
Muchas gracias @uvejota y demás por vuestro tiempo y dedicación, buen trabajo!
