### ISSUE TITLE
Sin actualización de datos desde 2022-10-24

### ISSUE THREAD

**Issue by Dixaum** [uvejota/homeassistant-edata#117]
Antes de nada, muchas gracias uvejota por tu trabajo. Espectacularmente útil para un montón de gente.

Desde el día 24-10-2022 no se actualizan los datos de consumos diarios.

Datadis envió un mail a todos los usuarios de api acerca de que actualizaría la forma de acceso a los datos en la semana del 25-10-2022. Me pregunto si la falta de datos es porque sería necesaria una actualización de la integración para volver a interpretarlos. 

El log de HA muestra lo siguiente:

Este error se originó a partir de una integración personalizada.

Logger: custom_components.edata.coordinator
Source: custom_components/edata/coordinator.py:275
Integration: Integración edata (documentation, issues)
First occurred: 23 de octubre de 2022, 22:50:02 (653 occurrences)
Last logged: 10:40:02

Some stats are missing for 21dc.

Además, muestra el siguiente mensaje cuando se recarga la integración:

Logger: edata.connectors
Source: /usr/local/lib/python3.10/site-packages/edata/connectors.py:79
First occurred: 25 de octubre de 2022, 08:08:30 (149 occurrences)
Last logged: 10:01:13

https://datadis.es/api-private/api/get-max-power?cups=ES002xxxxxxxxxxxxxxx&distributorCode=8&startDate=2022/10&endDate=2022/10& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-max-power?cups=ES002xxxxxxxxxxxxxxx&distributorCode=8&startDate=2022/10&endDate=2022/10& returned {"status":404,"error":"NOT_FOUND","message":"404 Not Found","timestamp":"2022-10-27T08:46:26.492+0200"} with code 404
https://datadis.es/api-private/api/get-consumption-data?cups=ES002xxxxxxxxxxxxxxx&distributorCode=8&startDate=2022/10/23&endDate=2022/10/27&measurementType=0&pointType=5& returned Fechas incorrectas with code 400
https://datadis.es/api-private/api/get-consumption-data?cups=ES002xxxxxxxxxxxxxxx&distributorCode=8&startDate=2022/10/23&endDate=2022/10/27&measurementType=0&pointType=5& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-max-power?cups=ES002xxxxxxxxxxxxxxx&distributorCode=8&startDate=2022/10&endDate=2022/10& returned {"status":404,"error":"NOT_FOUND","message":"404 Not Found","timestamp":"2022-10-28T08:59:43.567+0200"} with code 404

**Comment by SmilinStanSStanman** [comment]
Tienes la integración actualizada? Yo tengo datos descargados mas recientes.

![Screenshot_2022-10-28-11-04-18-80_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/76565446/198549704-91c53a35-1af9-4e7c-8cf1-4f14d5793ad8.jpg)

**Comment by adrz95** [comment]
Buenas @Dixaum, te recomiendo que ocultes tu CUPS, es solo cuestión de privacidad.

Es posible que tengas un error en la integración de HA, a mi me funciona bien, la petición a la API de DATADIS la está realizando pero el parametro donde se envian las fechas parece incorrecto.

Comprueba que tienes la integración actualizada, he comparado la URL donde haces la petición y las fechas tienen un formato distinto al mio.

**La URL a la que solicita datos tu HA:**
https://datadis.es/api-private/api/get-consumption-data?cups=CUPS&distributorCode=8&startDate=2022/10/23&endDate=2022/10/27&measurementType=0&pointType=5&

**En mi HA :**
https://datadis.es/api-private/api/get-consumption-data?cups=CUPS&distributorCode=2&startDate=2022/10&endDate=2022/10&measurementType=0&pointType=5&

En mi HA, el valor del parametro startDate y endDate es "2022/10" y si compruebas el tuyo es "2022/10/27".
No hace mucho que sigo esta integración pero puede que la tengas desactualizada.

EDIT:
https://github.com/uvejota/homeassistant-edata/issues/116#issuecomment-1290650580

Confirmado, tienes la integración desactualizada.

**Comment by Dixaum** [comment]
Muchas gracias @adrz95 por la sugerencia de borrar el CUPS. No había caído... Y muchas gracias @TripitonPT por la rápida respuesta.

Con respecto a actualizar la integración, ¿necesito desinstalarla y volverla a instalar? No encuentro la forma de actualizarla si no es así...

**Comment by SmilinStanSStanman** [comment]
Para actualizarla, vete al HACS de tu Home assistant y ahi te apareceran los repositorios personalizados pendientes de actualizar. Ahi aparecera el e-data si no esta al dia.

**Comment by Dixaum** [comment]
¡Ah, claro! HACS... No recordaba que esta integración estaba en HACS.

Actualizada y funcionando.

Muchas gracias @TripitonPT
