### ISSUE TITLE
No se pudo cargar el flujo

### ISSUE THREAD

**Issue by darkangeloti** [uvejota/homeassistant-edata#118]
Hola buenos días , no soy capaz de hacer funcionar la integración. Después de instalarla e intentar abrirla me sale el siguiente error: no se pudo cargar el flujo de configuración:Failed dependencies recorder. La versión que tengo es la última “2022.10.2” y la versión del home assistant es la “2022.11.0”.
Un saludo

**Comment by uvejota** [comment]
Buenas, el 'recorder' de Home Assistant es necesario para que funcione la integración.

Por defecto viene habilitado (creo que con la cláusula default_config), pero es posible que hayas restringido su uso a ciertas integraciones (en el configuration.yaml).

**Comment by darkangeloti** [comment]
Hola pues ahora que lo dices lo tengo configurado con Mariadb.
Que es lo que puedo hacer?
Un saludo y gracias por la respuesta

**Comment by darkangeloti** [comment]
Hola buenos días he deshabilitado maríadb y ya funciona. He visto que me ha salido una barra lateral donde puedo configurar todo el tema de la energía. Supongo que se ha instalado con esta integración. Pero solo he configurado el consumo del contador, si el día de mañana quiero añadir las placas solares. Cómo se edita de nuevo dicho panel?
Un saludo

**Comment by adrz95** [comment]
Hola @darkangeloti, el panel de energía es nativo de Home Assistant, la integración (e-data) añade los datos que recibe de datadis en este panel.

Cuando tengas placas solares tendrás que utilizar otros metodos para añadir los datos en el panel. Esta integración solo obtiene datos de tu consumo de la api de DATADIS, la configuración de costes es para hacer un cálculo aproximado de costes en el panel de energía.

Respecto al [comentario anterior,](https://github.com/uvejota/homeassistant-edata/issues/118#issuecomment-1301912346) tienes toda la información sobre que puedes hacer con la integración y como funciona en el readme.
https://github.com/uvejota/homeassistant-edata#readme

Saludos

**Comment by darkangeloti** [comment]
Hola buenas tardes, pues muchas gracias.
Todo aclarado, y enhorabuena por la integración, gran trabajo.
Un saludo
