### ISSUE TITLE
Demasiadas llamadas a la API - mail de aviso

### ISSUE THREAD

**Issue by mvillarejo** [uvejota/homeassistant-edata#119]
Hola, 

he recibido un mail desde datadis avisando de una cantidad excesiva de llamadas desde que hace un par de días actualicé a la última versión, adjunto una captura.

![E6858E33-F3AA-4516-B82E-B23BC3D48AB2](https://user-images.githubusercontent.com/4228967/200037063-f44dcbd4-2249-4a4f-b1e9-3d2086c98324.jpeg)

Creéis tiene alguna relación o mejor pruebo a reinstalar y regenerar el token?

Gracias

**Comment by uvejota** [comment]
Voy a revisarlo, no sea que tenga algún error en la implementación... a ver si saco tiempo.

Gracias por el aviso.

**Comment by uvejota** [comment]
Teóricamente resuelto en 2022.11.1

**Comment by mvillarejo** [comment]
ok, acabo de actualizar. 
Gracias
