### ISSUE TITLE
Resultado None

### ISSUE THREAD

**Issue by ar3l** [uvejota/homeassistant-edata#12]
Hola buenas sigo tu trabajo y gracias por ello. No consigo hacer funcionar la integración, ya estoy registrado en datadis, cambie los últimos datos por el cups y cambie los datos en la tarjeta pero ni aún así funciona. ¿Alguien tiene alguna idea? Gracias!!!

**Comment by uvejota** [comment]
Hola, te copio las instrucciones que he puesto en otra issue para encontrar el posible fallo:

1. Instala la última versión disponible de edata
2. Configúralo:
``` yaml
sensor:
  - platform: edata
    username: DNICONLETRA
    password: PASSWORD
    cups: XXCUPSCOMPLETOENMAYUSXXX
```
3. Reinicia HA o recarga edata (servicio edata.reload)
4. Se te ha debido de crear un sensor llamado sensor.edata_XXXX siendo XXXX los últimos cuatro dígitos de su CUPS, su estado inicial es 'loading' y cambia a una fecha/hora conforme se actualiza (fecha de la última actualización). Si tiene fecha y hora: ¿tiene atributos?, ¿Vacíos o con datos?
5. Si tiene atributos y datos, el sensor funciona, si los atributos están vacíos puede ser (a) que datadis no ha respondido adecuadamente, y se actualizará solo la próxima hora, (b) que hayas metido mal los datos de CUPS/credenciales, (c) otro error que desconozco pero que vamos a encontrar

Una vez resuelto lo anterior, pasaríamos a habilitar las tarjetas, necesitarás el custom_component de apexcharts-card (también disponible en HACS), y reemplazar los XXXX por los últimos 4 valores de tu CUPS (los sensor.edata_xxxx deben estar en minúscula, tal y como te lo haya creado HA)

Ya me dices, y si no hay éxito revisamos de nuevo :-)

**Comment by ar3l** [comment]
Hola te adjunto una captura después de seguir los pasos indicados. Puedes
comprobar que el cups en el sensor si lo cambia, pero los atributos salen
sin datos.

**Comment by uvejota** [comment]
Hola, me temo que no he recibido captura ni al mail ni al hilo

**Comment by ar3l** [comment]
Te lo mando ahora, ver qué tal?

**Comment by uvejota** [comment]
Hola, mi apuesta es por CUPS erróneo. 

¿Puedes probar a copiar y pegar el que te escupe la web de datadis en la configuración?

**Comment by ar3l** [comment]
Vale ya tengo atributos, el error es que mis cupos tiene 2 dígitos más.

Gracias un saludo
