### ISSUE TITLE
Múltiples CUPS y nueva actualización

### ISSUE THREAD

**Issue by webtense** [uvejota/homeassistant-edata#121]
Buenos días
de nuevo gracias por tu excelente trabajo, que tanto me ha ayudado. 
yo le he dado una vuelta mucho más grande a este proyecto y he añadido, he añadido 127 contadores.
he de decir que con algunos cambios, que te he ido informando , cambio de 5 dígitos en lugar de 4 dígitos, ha funcionado todo bien hasta esta última actualización,

¡me he revisado tu código entero, y los cambios de EDATA, y no entiendo el porqué no me está funcionando ninguno de los sensores, no llega a cargar la info, siempre se queda cargando!

hay alguna cosa que puede hacer, para que carguen de nuevo los datos. ahora me resetea todos los sensores que hay en .store y elimina todo lo anterior y no carga!

gracias

**Comment by uvejota** [comment]
No creo que eso se deba a los cambios que se han hecho en la integración (limitar a 1 update cada 24 horas y actualizar la query de consumos).

La verdad, no tengo ni idea, ¿Quizá han implementado algún tipo de baneo por IP?

Yo probaría a quitar 1 de los sensores y volverlo a configurar, y ver si ese "funciona". Si es así, es que de alguna forma el registro de sensores de HA está corrupto.

Por cierto, desde que recibí tu mail tengo en mente preparar que el nº de dígitos sea configurable (y por defecto 4). Gracias por la idea.

**Comment by uvejota** [comment]
Buenas, la última versión en pruebas (2022.12.3) está preparada para elegir dinámicamente el número de caracteres usados en el cups abreviado, de modo que no "colisionen".

Lamentablemente tendrás que reconfigurar las integraciones y las tarjetas.

Pensé en hacerlo configurable, pero el exceso de configuración es una hoja de doble filo... muchos usuarios tocarían sin saber lo que están haciendo.
