### ISSUE TITLE
Falta parámetro authorizedNif cuando se consultan las potencias máximas

### ISSUE THREAD

**Issue by darroyop** [uvejota/homeassistant-edata#122]
Hola, al llamar a /api-private/api/get-max-power con el CUPS de un tercero, falta añadir el NIF con el parámetro authorizedNif. En la consulta del consumo sí que se está enviando.
Ahora mismo da error al no ser propietario del CUPS el usuario que hace la consulta.

Muchas gracias por tu trabajo.

**Comment by uvejota** [comment]
Cierto, parece ser que se me ha "pasado".

Lo apunto a la lista de deberes.

Gracias por el aviso.

**Comment by uvejota** [comment]
Esto está presumiblemente resuelto en 2022.11.2 (ya liberada).

Gracias por los avisos.
