### ISSUE TITLE
Platform error sensor.edata

### ISSUE THREAD

**Issue by VMLV** [uvejota/homeassistant-edata#123]
Hola.
Al verificar el configutation.yaml me da un error.
Platform error sensor.edata - Requirements for edata not found: ['e-data==0.4.4']
He reinstalado todo varias veces y copiado el codigo como indican y siempre se queda en este punto.
En Datadis puedo ver mi informacion sin problemas.
Alguna sugerencia?
Gracias

**Comment by adrz95** [comment]
Hola, 

Si tienes la **versión 2022.01.0** o superior, seguramente lo tengas, NO es necesario configurar nada en configuration.yaml  para que funcione la integración. Debes hacerlo desde los ajustes de Home Asistant  (buscar "edata" en Configuración > Dispositivos y servicios > Añadir integración). 

Tienes toda la información en el readme:
https://github.com/uvejota/homeassistant-edata#instalaci%C3%B3n

**Comment by VMLV** [comment]
Muchas gracias por tu respuesta pero da el mismo error.
Te copio mensaje de error.
Gracias

Logger: aiohttp.server
Source: requirements.py:252
First occurred: 19:30:22 (1 occurrences)
Last logged: 19:30:22

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py",
line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line
504, in _handle
    resp = await handler(request)
  File
"/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line
117, in impl
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/security_filter.py",
line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py",
line 100, in forwarded_middleware
    return await handler(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/request_context.py",
line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line
82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line
236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line
136, in handle
    result = await result
  File
"/usr/src/homeassistant/homeassistant/components/config/config_entries.py",
line 148, in post
    return await super().post(request)
  File
"/usr/src/homeassistant/homeassistant/components/http/data_validator.py",
line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py",
line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225,
in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 243,
in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 805,
in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 361, in
async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 49, in
async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 168, in
async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 183, in
_async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 230, in
async_process_requirements
    self._raise_for_failed_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 252, in
_raise_for_failed_requirements
    raise RequirementsNotFound(integration, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for edata not
found: ['e-data==0.4.4'].

**Comment by uvejota** [comment]
¿Tienes algún problema de conectividad en la máquina?

Falla antes de instalar e-data, al descargar las dependencias de pip.

Poco se puede hacer por mi parte.

**Comment by Danieldiazi** [comment]
Es como si no tuviese acceso para descargarse la versión 0.4.4 de la librería e-data

**Comment by uvejota** [comment]
Sin duda esto poco tiene que ver con nosotros, es un problema en la descarga del paquete (que puede ser de encaminamiento, de dns, de pip...)
