### ISSUE TITLE
No actualiza datos desde el 22 de octubre de 2022

### ISSUE THREAD

**Issue by jjvelar** [uvejota/homeassistant-edata#125]
Hola,
No actualiza los datos desde el 22 de octubre de 2022.
He entrado en la web de Datadis y he podido descargarme de los últimos días así que no parece que se haya caído el servicio.
He mirado la entidad sensor.edata_XXXXX y, a pesar de que el estado es "ready", la mayoría de los atributos relativos al consumo posterior al 22 de octubre aparecen como "null".
En los logs tengo 106 errores que son como éste (he cambiado mi código CUPS por XXX por privacidad, pero el que sale es el correcto):

`https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXX&distributorCode=2&startDate=2022/09/01&endDate=2022/09/01&measurementType=0&pointType=5& returned Fechas incorrectas revise: Formato de fechas YYYY/MM, las fechas deben ser anteriores o iguales al mes actual, fecha inicio no superior a fecha fin. with code 400`

Gracias por la ayuda

**Comment by uvejota** [comment]
Buenas, tienes que actualizar la integración.

**Comment by jjvelar** [comment]
Gracias por contestar tan rápido.
Cómo lo hago? Vuelvo a instalarla o hay una forma específica para actualizarla?

**Comment by uvejota** [comment]
Pues si la instalaste con HACS puedes actualizarlo por ahí

**Comment by jjvelar** [comment]
Ah, ya veo. Es que esperaba que "avisara" como hacen otras integraciones de HACS. Veo que lo que tengo que hacer es descargarla de nuevo.
Gracias!

**Comment by jjvelar** [comment]
> Pues si la instalaste con HACS puedes actualizarlo por ahí

No lo cierres todavía porque anoche tampoco se actualizó. Le estoy dando 24 horas pero antes se actualizaba de madrugada

**Comment by jjvelar** [comment]
Ahora sí se ha actualizado. Gracias!
