### ISSUE TITLE
No concuerdan los datos del mes pasado en datadis y en la integración

### ISSUE THREAD

**Issue by davidesancho** [uvejota/homeassistant-edata#126]
Hola,

Mil gracias lo primero por el curro, la integración es maravillosa. Tengo una discordancia de datos, en la web de datadis, el mes pasado (octubre) me marca 100.68 y sin embargo en la integración me sale este dato, last_month_kWh: 196.93 . Mil gracias,

Saludos

**Comment by uvejota** [comment]
Hola, qué curioso, ¿puedes investigar si el exceso está localizado en todos los días o en algún día en concreto? Así puedo localizar mejor el desencadenante del fallo.

También cuando te llegue la factura de ese mes, a ver qué pone, para descartar que Datadis esté fallando.

Gracias

**Comment by davidesancho** [comment]
Hola, gracias por responder tan rápidamente. Pues de los días que tengo info en home assistant (imagino que es cuando puse la integración) y si macheo lo que me marca en datadis, sale el mismo gasto por día, he mirado los diez días últimos de octubre. Cuando me venga la factura de Octupus, miraré a ver y te comento. Gracias!
