### ISSUE TITLE
Error 429 permanentemente

### ISSUE THREAD

**Issue by damaca** [uvejota/homeassistant-edata#127]
Durante varios dias la integración no está actualizando datos. Al mirar en los logs se ve de constante el siguiente error:

```
Logger: edata.connectors
Source: /usr/local/lib/python3.10/site-packages/edata/connectors.py:79
First occurred: 09:06:26 (605 occurrences)
Last logged: 09:07:20

https://datadis.es/api-private/api/get-max-power?cups=ES************&distributorCode=8&startDate=2022/11&endDate=2022/11& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-consumption-data?cups=ES************&distributorCode=8&startDate=2021/11&endDate=2021/12&measurementType=0&pointType=5& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-consumption-data?cups=ES************&distributorCode=8&startDate=2021/12&endDate=2022/01&measurementType=0&pointType=5& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-consumption-data?cups=ES************&distributorCode=8&startDate=2022/01&endDate=2022/01&measurementType=0&pointType=5& returned Consulta ya realizada en las últimas 24 horas. with code 429
https://datadis.es/api-private/api/get-max-power?cups=ES************&distributorCode=8&startDate=2021/11&endDate=2022/01& returned Consulta ya realizada en las últimas 24 horas. with code 429
```

He probado a dejar la integración deshabilitada durante un par de dias para volverla a habilitar despues y no ha habido ningun cambio.

**Comment by Pabsilon** [comment]
Tengo el mismo error desde el día 22.
Hasta ese día el funcionamiento (en mi antigua casa) era perfecto, cambié la titularidad del contrato de la casa a la que me acabo de mudar y cambié los datos de la integración. Sólo me ha recuperado un día de datos (el 22).
Lo achaqué a ser un contrato nuevo o que no hubiera suficientes datos, pero en otra instancia de HA (sin cambios en el contrato!) tampoco hay datos nuevos desde el día 23.

**Comment by JokeRsevilla** [comment]
yo estoy igual, error 429... Última actualización correcta el 4/11/2022... y en la web de datadis hay datos de ayer...

**Comment by uvejota** [comment]
Probad la última beta

**Comment by PacmanForever** [comment]
Hola, entiendo que una vez instalada hay que esperar 24h ¿no?
Porqué con cada petición con error (que se repiten) impide volver hacer la consulta hasta dentro un dia ¿no?

Gracias por hacer esta integración.

**Comment by davidesancho** [comment]
Hola, como se instala la beta? Gracias!

**Comment by BronRZ** [comment]
Hola,

Desde que me cambiaron algo en el contador para temas de autoconsumo el 3-4 de noviembre, no se me actualizaban los datos. Esperé días tras días a ver si se actualizan, mirando los logs para que no hubiera errores. Eliminando por completo la integración y volviendo a configurarla sin éxito.

Finalmente, al instalar la **versión beta** ya se han cargado los datos perfectamente hasta el último día del registro.

¡Muchísimas gracias!

![firefox_5887](https://user-images.githubusercontent.com/3785798/204127323-6eb23533-6fca-431f-ac2c-27689d3a0be3.jpg)

**Comment by uvejota** [comment]
Esto está presumiblemente resuelto en 2022.11.2 (ya liberada).

Gracias por los avisos.



> Hola, entiendo que una vez instalada hay que esperar 24h ¿no? Porqué con cada petición con error (que se repiten) impide volver hacer la consulta hasta dentro un dia ¿no?
> 
> Gracias por hacer esta integración.

Si es la primera vez que usas la API de datadis, no, debería ser "inmediata".  Lo de las 24 horas sólo afecta si la respuesta ha sido exitosa.

**Comment by PacmanForever** [comment]
Hola,

perdonad que insista en este issue, pero puse la beta y después la última release y continuo sin datos desde inicio de noviembre.
 
He recreado las estadísticas pero nada.

¿alguna idea?

**Comment by f-vicente** [comment]
Yo tampoco consigo que funcione.

En mi caso instalé la 11.1 y me salió el error por lo que no llegó a configurar el sensor. Actualicé a la beta y seguí con el error. Actualicé a 11.2 y lo mismo.

He probado eliminado todo y volviendo a instalarlo y siempre me aparece el error y no llega a configurar el sensor.

**Comment by uvejota** [comment]
Necesitaré que los que sigan sin tener datos me abran una nueva issue aportando logs + información sobre qué información aparece en la entidad + contenido anonimizado del fichero de .storage + particularidades de vuestro contrato (si habéis cambiado recientemente, vivienda vacía...) 

Vuestro caso es "particular" y no se debe al exceso de peticiones que aquí se habla, de ahí que haya cerrado la issue.

PD: evitad reiniciar HA para forzar descargas de datos, o seguirá saliendo el error 429. La integración pedirá lo que le falta cada 24h.
