### ISSUE TITLE
Errores y mejoras

### ISSUE THREAD

**Issue by ajtudela** [uvejota/homeassistant-edata#128]
Buenas, lo primero de todo, quiero darte las gracias por tu fantástica integración. Con esta última beta, por fin puedo ver los datos de mi consumo. Sin embargo, tengo unos errores y te propongo mejoras.

![Captura](https://user-images.githubusercontent.com/4681902/203850829-fd051220-6e48-4ce0-97b8-29f5b7ba9b84.JPG)

- En el mes de mayo (color rojo) me sale un consumo desorbitado respecto a los demás meses. He mirado en Datadis, tengo consumos desde el mes de abril, que es cuando me pusieron el contador nuevo; pero todos los meses son "normales". En la integración, el mes de abril no me aparece y el mes de mayo tiene consumos muy por encima.
- ¿Sería posible cambiar el nombre a los valores de consumo: XXX p1_kWh consumption, ..? (color azul) He intentado cambiarlos pero no he podido cambiarlo porque no me aparecen como entidades.
- En cuanto al coste, en el panel de energía, he añadido el coste como "precio estático" con un valor fijo para cada uno de los periodos (color negro) pero no me aparece en dicho panel, sin embargo, tengo otra integración con el coste de la misma forma y si aparece.  
- Sé que está el coste de la energía total (edata:xxxx_energy_cost) pero he pensado que sería interesante añadir el coste de energía por cada periodo (p1, p2, p3). Así se puede añadir en el panel de energía directamente desde el sensor y no un valor a mano.

Gracias!!

**Comment by uvejota** [comment]
Buenas, el exceso del panel de energía creo que puedes corregirlo llamando al servicio de regeneración de estadísticas.

> Desde la versión 2022.09.0, puedes regenerar las estadísticas manualmente mediante un servicio (Herramientas para desarrolladores > Servicios > edata.recreate_statistics).

Sobre el nombre de las estadísticas del panel de energía, no se pueden personalizar por el usuario puesto que HA no lo permite (como apuntas son estadísticas no vinculadas a una entidad). La inyección de estadísticas a pasado es una funcionalidad bastante reciente de HA y supongo que habrá mejoras. Por otro lado, yo podría cambiar el nombre a algo más significativo, la verdad.

Sobre los tramos en la tarificación, es claramente un siguiente paso, pero antes voy a intentar consolidar lo que ya tenemos :) 

Gracias por el testing

**Comment by jrlesco** [comment]
Creo que no  lo tienes bien configurado ya que en el panel de energía consumida de la red, ademas de los tres periodos reflejados, que su suma daría el total, tienes también el termo sumándolo a los tres periodos dando un consumo superior al real

**Comment by ajtudela** [comment]
Sí, cierto, me di cuenta de eso y lo añadí a la parte de dispositivos individuales. Gracias!
