### ISSUE TITLE
Sin datos - Debug

### ISSUE THREAD

**Issue by netamego** [uvejota/homeassistant-edata#13]
Hola,

Antes de nada gracias por este pedazo de addon y el currazo que le has metido. Eres un crack.
¿Me puede indicar alguien como poner debug a este addon? No recibo datos pero tampoco veo errores en el log.

Muchas gracias!!

**Comment by uvejota** [comment]
Hola, el debug_level se puede establecer a través de homeassistant para el nivel que quieras, con INFO deberías tener suficiente información (i.e., https://www.home-assistant.io/integrations/logger/). 

De todos modos, si no lanza errores, ¡es raro! Prueba lo siguiente y me dices:

1. Instala la última versión disponible de edata
2. Configúralo:
``` yaml
sensor:
  - platform: edata
    username: DNICONLETRA
    password: PASSWORD
    cups: XXCUPSCOMPLETOENMAYUSXXX
```
3. Reinicia HA o recarga edata (servicio edata.reload)
4. Se te ha debido de crear un sensor llamado sensor.edata_XXXX siendo XXXX los últimos cuatro dígitos de su CUPS, su estado inicial es 'loading' y cambia a una fecha/hora conforme se actualiza (fecha de la última actualización). Si tiene fecha y hora: ¿tiene atributos?, ¿Vacíos o con datos?
5. Si tiene atributos y datos, el sensor funciona, si los atributos están vacíos puede ser (a) que datadis no ha respondido adecuadamente, y se actualizará solo la próxima hora, (b) que hayas metido mal los datos de CUPS/credenciales, (c) otro error que desconozco pero que vamos a encontrar

Una vez resuelto lo anterior, pasaríamos a habilitar las tarjetas, necesitarás el custom_component de apexcharts-card (también disponible en HACS), y reemplazar los XXXX por los últimos 4 valores de tu CUPS (los sensor.edata_xxxx deben estar en minúscula, tal y como te lo haya creado HA)

Ya me dices, y si no hay éxito revisamos de nuevo :-)

**Comment by joaquimpin** [comment]
Hola buenas!
ayer me instale la ultima version, y me pasa exactamente lo mismo, a ver si consigues solucionarlo



![image](https://user-images.githubusercontent.com/37812092/131744317-3c7d0d85-3b4a-497d-b39a-3f0fb42730d8.png)


Muchas gracias!

**Comment by joaquimpin** [comment]
@netamego en mi caso no tenía registrado datadis, estaba usando eDistribucion (venía de tu otro repositorio), ha sido darme de alta en datadis poner los códigos de acceso y funcionar perfectamente,

![image](https://user-images.githubusercontent.com/37812092/131825641-97cd83c5-8599-4d95-a30d-a2bbfa8e31a8.png)

¡Muchas gracias!

**Comment by netamego** [comment]
uvejota eres un crack. Ese es exactamente el problema. Por eso hacia todo bien menos descargarse los datos. El tema es que yo metí el CUPS según está en mi factura. Creo que, por lo menos en todos los cups de Iberdrola, al final tienen el 0F y en datadis está sin 0F. 

Por curiosidad pongo un pantallazo de alguna comercializadora que avisa de este aspecto.

![0F](https://user-images.githubusercontent.com/10206580/131858832-18aaf28d-0489-42d2-a845-2f75fb5d7ec6.png)

Vamos que lo mio ha sido torpeza por mi parte pero lo mismo no está de mas indicarlo en el proceso de configuración. Mas que nada por evitar que abran "issues" innecesarios.

Muchas gracias @joaquimpin por tu ayuda.

Y por supuesto @uvejota que ha dado con el tema!!!.

Un saludo.

**Comment by uvejota** [comment]
😄 genial!

Cierro esto, gracias por la sugerencia @netamego, estoy preparando una Wiki con una sección de FAQ! 👌
