### ISSUE TITLE
Histórico de datos

### ISSUE THREAD

**Issue by GMTZMU** [uvejota/homeassistant-edata#130]
Primero de todo, agradecerte el trabajo realizado nos ayuda a todos.
Ahora mismo tengo un histórico de 1 año de datos y observo que solo puedo tener 1 año, me gustaría poder disponer de más tiempo, para poder comparar el consumo del mismo mes en dos años.

¿Sería posible tener un histórico de 2 años?.

Muchas gracias.

**Comment by mcarlosro** [comment]
Creo que recordar que antes se recuperaban más datos. ¿ha cambiado algo? a mi me gustaria recuperarlo todo para poder comparar en distintos meses o años (2022 vs 2021 o 2021 vs 2020)

**Comment by uvejota** [comment]
Buenas, posible es, intentaré hacerlo configurable cuando la vida me de un minuto :)

**Comment by Murada99** [comment]
Primero de todo, agradecerte el trabajo realizado.
Yo también estoy interesado en tener más de 1 año. 
Difícil comparar los meses con el año anterior cuando solo tenemos 1 año.

Muchas Gracias
