### ISSUE TITLE
Efectivamente, m faltaba el dato en 1 tarjeta. Espero ya m aparezcan mñna los datos. Gracias

### ISSUE THREAD

**Issue by EMACSAN** [uvejota/homeassistant-edata#132]
Efectivamente, m faltaba el dato en 1 tarjeta. He quitado todas las tarjetas apexcharts y he dejado únicamente la de datos. 
Gracias

Después de esperar algunas horas, sigo teniendo este error.

Logger: custom_components.edata.statistics
Source: custom_components/edata/statistics.py:147
Integration: Integración edata ([documentation](https://github.com/uvejota/homeassistant-edata/), [issues](https://github.com/uvejota/homeassistant-edata/issues))
First occurred: 09:37:05 (1 occurrences)
Last logged: 09:37:05

Some stats are missing for xn0f

_Originally posted by @EMACSAN in https://github.com/uvejota/homeassistant-edata/issues/131#issuecomment-1332798661_

**Comment by uvejota** [comment]
Seguimos mejor en #131, que os pasa a varios :)
