### ISSUE TITLE
Cambios en la API de estadisticas de Home Assistant 2022.12 (beta) rompen edata

### ISSUE THREAD

**Issue by skgsergio** [uvejota/homeassistant-edata#133]
Buenas, no se si estas al tanto pero como uso la beta me gusta ir reportando estas cosas antes de que llegue la estable a publico en general.

Con la beta de la 2022.12 se ve el siguiente error:
```python
2022-12-02 16:57:08.477 ERROR (MainThread) [custom_components.edata.coordinator] Unexpected error fetching edata_83tp data: get_last_statistics() missing 1 required positional argument: 'types'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/edata/coordinator.py", line 136, in _async_update_data
await self.statistics.update_statistics()
File "/config/custom_components/edata/statistics.py", line 131, in update_statistics
last_stats = {
File "/config/custom_components/edata/statistics.py", line 132, in <dictcomp>
x: await get_db_instance(self.hass).async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: get_last_statistics() missing 1 required positional argument: 'types'
```

Y es debido a este breaking-change: https://github.com/home-assistant/core/pull/82131

Ahora `get_last_statistics` requiere un nuevo argumento types que es un set de con los posibles valores "last_reset", "max", "mean", "min", "state" y "sum". Parece que antes devolvia todo esto y ahora eliges cual o cuales quieres que devuelva.

Lo malo es que mantener compatibilidad simultanea con la 2022.12 y anteriores requeriría algo feo estilo (no se cuantas versiones quieres soportar pero dejo la idea):

```python
from homeassistant.const import MAJOR_VERSION, MINOR_VERSION

[...]

  if MAJOR_VERSION < 2022 or (MAJOR_VERSION == 2022 and MINOR_VERSION < 12):
    # llamada a get_last_statistics sin type
  else:
    # llamada a get_last_statistics con type
```

**Comment by PacmanForever** [comment]
¿De ahí viene esto?

![imagen](https://user-images.githubusercontent.com/37216513/205351262-c10b0a0b-5b30-415c-af6d-4d1b2386bce3.png)

**Comment by uvejota** [comment]
Joder, es un mes movidito, a ver si saco un ratito mañana y lo adapto.

Gracias por el aviso

**Comment by uvejota** [comment]
> ¿De ahí viene esto?
> 
> ![imagen](https://user-images.githubusercontent.com/37216513/205351262-c10b0a0b-5b30-415c-af6d-4d1b2386bce3.png)

No creo, hablamos de cambios del canal beta, aún no están en las instalaciones "normales".

Prueba si con la última versión de la integración (y unos días de espera) se rellena. En mi caso sigo esperando, a principios de mes datadis me tarda un pelín.

**Comment by uvejota** [comment]
Resuelto en rama `dev`

**Comment by skgsergio** [comment]
Instalada rama `dev` y funcionando 🚀

**Comment by uvejota** [comment]
> Instalada rama `dev` y funcionando 🚀

Había un pequeño bug, ahora está corregido en `dev`

**Comment by skgsergio** [comment]
Vale, actualizado y aparentemente todo sigue bien:

![image](https://user-images.githubusercontent.com/186349/205440369-05d1c0a8-0348-4634-ad30-0acf5406b8a8.png)
