### ISSUE TITLE
Carga de datos congelada

### ISSUE THREAD

**Issue by jrlesco** [uvejota/homeassistant-edata#134]
Esto es lo que reflejan los logs
[edata.helpers] Update requested for CUPS XXXX from 2021-12-04T12:01:25.218205 to 2022-12-03T23:59:00
[edata.connectors.datadis] GET https://datadis.es/api-private/api/get-supplies
[edata.connectors.datadis] No token found, fetching a new one
[edata.connectors.datadis] GET https://datadis.es/api-private/api/get-supplies
[edata.connectors.datadis] Got 200 OK at https://datadis.es/api-private/api/get-supplies
[edata.helpers] Supplies data has been successfully updated
[edata.connectors.datadis] GET https://datadis.es/api-private/api/get-contract-detail?cups=XXXXXXXXXXXXXXX&distributorCode=8&
[edata.connectors.datadis] Got 200 OK at https://datadis.es/api-private/api/get-contract-detail?cups=XXXXXXXXXXXXXXXXXX&distributorCode=8&
[edata.helpers] Contracts data has been successfully updated
[edata.helpers] Identified missing consumptions: 2022-11-30T23:00:00 - 2022-12-03T23:59:00
[edata.helpers] Identified missing maximeter: 2022-11-12T00:00:00 - 2022-12-03T23:59:00
[edata.helpers] Supplies and contract start date do not match, exploring non-registered contracts

**Comment by uvejota** [comment]
Eso significa que tu distribuidora/comercializadora ha registrado un contrato cuya fecha de inicio no corresponde a la fecha de inicio del suministro.  Es decir, si tu suministro se dio de alta en enero de 2020 (hasta hoy), en Datadis el alta del contrato más antiguo de ese suministro es posterior a enero de 2020.

¿Puedes ponerme el contenido de edata.storage_XXXX anonimizado?

**Comment by jrlesco** [comment]
> Eso significa que tu distribuidora/comercializadora ha registrado un contrato cuya fecha de inicio no corresponde a la fecha de inicio del suministro. Es decir, si tu suministro se dio de alta en enero de 2020 (hasta hoy), en Datadis el alta del contrato más antiguo de ese suministro es posterior a enero de 2020.
> 
> ¿Puedes ponerme el contenido de edata.storage_XXXX anonimizado?

Gracias por tu pronta respuesta, cambie el contrato de pvpc a un fijo hace dos meses y tu maravilloso proyecto lo tengo activo desde hace un año

**Comment by jrlesco** [comment]
> > Eso significa que tu distribuidora/comercializadora ha registrado un contrato cuya fecha de inicio no corresponde a la fecha de inicio del suministro. Es decir, si tu suministro se dio de alta en enero de 2020 (hasta hoy), en Datadis el alta del contrato más antiguo de ese suministro es posterior a enero de 2020.
> > ¿Puedes ponerme el contenido de edata.storage_XXXX anonimizado?
> 
> Gracias por tu pronta respuesta, cambie el contrato de pvpc a un fijo hace dos meses y tu maravilloso proyecto lo tengo activo desde hace un año

{
  "version": 1,
  "minor_version": 1,
  "key": "edata.storage_XXX”X,
  "data": {
    "supplies": [
      {
        "cups": “XXXXXXXXXXXXXXXXX,
        "date_start": "1970-01-01T00:00:00",
        "date_end": "2022-12-05T00:00:00",
        "address": “XX”XXXXXXXXXXXXXXXXXXXXXXX,
        "postal_code": “XXXXXXX”,
        "province": “XXXXXXXX”,
        "municipality": “XXXXXXXXXXXXXXXXXXXX”,
        "distributor": "I-DE REDES ELÃCTRICAS INTELIGENTES, S.A.U.",
        "pointType": 5,
        "distributorCode": "8"
      }
    ],
    "contracts": [
      {
        "date_start": "2022-10-24T00:00:00",
        "date_end": "2022-12-05T00:00:00",
        "marketer": "IBERDROLA CLIENTES, S.A.U",
        "distributorCode": "8",
        "power_p1": 3.4,
        "power_p2": 3.4

Esto me pides?

**Comment by uvejota** [comment]
> > > Eso significa que tu distribuidora/comercializadora ha registrado un contrato cuya fecha de inicio no corresponde a la fecha de inicio del suministro. Es decir, si tu suministro se dio de alta en enero de 2020 (hasta hoy), en Datadis el alta del contrato más antiguo de ese suministro es posterior a enero de 2020.
> > > ¿Puedes ponerme el contenido de edata.storage_XXXX anonimizado?
> > 
> > 
> > Gracias por tu pronta respuesta, cambie el contrato de pvpc a un fijo hace dos meses y tu maravilloso proyecto lo tengo activo desde hace un año
> 
> { "version": 1, "minor_version": 1, "key": "edata.storage_XXX”X, "data": { "supplies": [ { "cups": “XXXXXXXXXXXXXXXXX, "date_start": "1970-01-01T00:00:00", "date_end": "2022-12-05T00:00:00", "address": “XX”XXXXXXXXXXXXXXXXXXXXXXX, "postal_code": “XXXXXXX”, "province": “XXXXXXXX”, "municipality": “XXXXXXXXXXXXXXXXXXXX”, "distributor": "I-DE REDES ELÃ�CTRICAS INTELIGENTES, S.A.U.", "pointType": 5, "distributorCode": "8" } ], "contracts": [ { "date_start": "2022-10-24T00:00:00", "date_end": "2022-12-05T00:00:00", "marketer": "IBERDROLA CLIENTES, S.A.U", "distributorCode": "8", "power_p1": 3.4, "power_p2": 3.4
> 
> Esto me pides?

Afirmativo, si te fijas, tu suministro está dado de alta desde 1970-1-1 (inicio de los tiempos...) hasta la actualidad, pero han borrado los contratos anteriores a este último, que va desde el 24-oct hasta hoy.

La integración se va guiando por los periodos de los contratos, y si el inicio de los contratos no cuadra con el inicio del suministro, "explora" hacia atrás (hasta hace 1 año).

En resumen:

El mejor caso: edata consigue recuperar el histórico sin problemas
El peor caso: edata sólo consigue recuperar datos del contrato actual (desde el 24 de octubre).

Mi recomendación es que esperes un poco, y si no lo consigue resolver le echamos un ojo más en profundidad. Puedes ignorar el warning 'Supplies and contract start date do not match, exploring non-registered contracts' de momento, pues es "normal", la integración ha detectado esta inconsistencia y va a intentar resolverla.

**Comment by jrlesco** [comment]
> > > > Eso significa que tu distribuidora/comercializadora ha registrado un contrato cuya fecha de inicio no corresponde a la fecha de inicio del suministro. Es decir, si tu suministro se dio de alta en enero de 2020 (hasta hoy), en Datadis el alta del contrato más antiguo de ese suministro es posterior a enero de 2020. 
> > > > ¿Puedes ponerme el contenido de edata.storage_XXXX anonimizado?
> > > 
> > > 
> > > Gracias por tu pronta respuesta, cambie el contrato de pvpc a un fijo hace dos meses y tu maravilloso proyecto lo tengo activo desde hace un año
> > 
> > 
> > { "versión": 1, "versión_menor": 1, "clave": "edata.storage_XXX”X, "datos": { "suministros": [ { "tazas": “XXXXXXXXXXXXXXXXX, "fecha_inicio": "1970-01 -01T00:00:00", "fecha_fin": "2022-12-05T00:00:00", "dirección": “XX”XXXXXXXXXXXXXXXXXXXXXXX, "código_postal": “XXXXXXX”, “provincia”: “XXXXXXXX”, " municipio": “XXXXXXXXXXXXXXXXXXXXX”, “distribuidor”: “I-DE REDES ELÉCTRICAS INTELIGENTES, SAU”, “pointType”: 5, “distributorCode”: “8” } ], “contratos”: [ { “date_start”: "2022-10-24T00:00:00", "fecha_fin": "2022-12-05T00:00:00", "comercializador": "IBERDROLA CLIENTES, SAU", "distributorCode": "8", "potencia_p1": 3,4, "potencia_p2": 3,4
> > Esto me pides?
> 
> Afirmativo, si te fijas, tu suministro está dado de alta desde 1970-1-1 (inicio de los tiempos...) hasta la actualidad, pero han borrado los contratos anteriores a este último, que va desde el 24-oct hasta hoy .
> 
> La integración se va guiando por los periodos de los contratos, y si el inicio de los contratos no cuadra con el inicio del suministro, "explora" hacia atrás (hasta hace 1 año).
> 
> En resumen:
> 
> El mejor caso: edata consigue recuperar el histórico sin problemas El peor caso: edata sólo consigue recuperar datos del contrato actual (desde el 24 de octubre).
> 
> Mi recomendación es que esperes un poco, y si no lo consigues resolver le echamos un ojo más en profundidad. Puedes ignorar el aviso 'Suministros y fecha inicio contrato no coinciden, explorando contratos no registrados' de momento, pues es "normal", la integración ha detectado esta inconsistencia y va a intentar resolverla.

Muchísimas gracias.

**Comment by pinifiux** [comment]
Hola, tengo exctamente el mismo problema, he esperado a ver si sincronizaba pero llevo 20 días en “loading”, alguna solución?

**Comment by jrlesco** [comment]
Reinstale la integración y esperar a que EDATA se integre bien con la proveedora de datos, pero tarda en hacerlo.

**Comment by pinifiux** [comment]
Vaya si tarda, he descargado la versión beta ( ya de probar pues al lio ), pero lleva días y sigue sin sincronizar…
