### ISSUE TITLE
Desglose de coste por tramo en panel de energía

### ISSUE THREAD

**Issue by etatus** [uvejota/homeassistant-edata#135]
Ha sido genial que hayas decidido incluir los precios PVPC. Muchas gracias por ello. El único problema es que no entiendo muy bien como usarlo. Tras activar ambas casillas en la configuración, facturación y PVPC, ya me aparece el sensor (eur) para añadir en el panel de energía, pero resulta que solo aparece uno y yo tengo tres sensores de energía (p1, p2, p3). Me imagino que si solo hay uno se referirá al total, que iría con el sensor de energía que da el total también, pero en mi caso lo tengo desglosado. ¿No podría haber también para los gastos PVPC el desglose p1, p2 y p3? Entiendo que esa información está en la fuente...

¡Muchas gracias!

**Comment by uvejota** [comment]
Buenas, efectivamente falta el desglose de consumo por tramo, es algo que ya me pidieron en #128 y tiene todo el sentido del mundo.

Lo que no tengo claro es si debería incluirlo para sólo el consumo de energía, o el total (incluyendo potencia), o ambos...

**Comment by etatus** [comment]
Tal como lo veo, lo coherente sería que coincidiese con los sensores de energía, si los hay desglosados y para el total, los costes también deberían estar tanto para el desglose como para el total. Imagino que habrá quien prefiera el desglose y habrá quien prefiera directamente el total y ambos deberían poder añadir el coste correspondiente.

**Comment by uvejota** [comment]
Pues ea, está implementado en la 2022.12.4 (de momento beta).

**Comment by etatus** [comment]
Va perfecto, muchas gracias!!

Por cierto, es posible pintar esos costes PVPC en una gráfica que no sea la del panel de energía? No me aparecen como sensores...

**Comment by uvejota** [comment]
> Va perfecto, muchas gracias!!
> 
> Por cierto, es posible pintar esos costes PVPC en una gráfica que no sea la del panel de energía? No me aparecen como sensores...

De momento no, estoy haciendo algunos cambios en la parte de visualización y aún no tengo muy claro cómo "encajarlo" (estoy planteando mi propio componente para ver los datos para evitar la tediosa configuración...)

**Comment by darguez** [comment]
Vale, pues una solución sencilla y coherente que permitiría acceder a parte de esa información fuera del panel de energía sería la de incorporar en el sensor los atributos:
- `yesterday_€`
- `last_registered_day_€`

Más que nada porque ya existen esos atributos para el mes.

**Comment by darguez** [comment]
> Vale, pues una solución sencilla y coherente que permitiría acceder a parte de esa información fuera del panel de energía sería la de incorporar en el sensor los atributos:
> 
> * `yesterday_€`
> * `last_registered_day_€`
> 
> Más que nada porque ya existen esos atributos para el mes.

@uvejota al final has incluido estos atributos? si no están, prefieres que lance un issue aparte con la propuesta?

**Comment by uvejota** [comment]
> > Vale, pues una solución sencilla y coherente que permitiría acceder a parte de esa información fuera del panel de energía sería la de incorporar en el sensor los atributos:
> > 
> > * `yesterday_€`
> > * `last_registered_day_€`
> > 
> > Más que nada porque ya existen esos atributos para el mes.
> 
> @uvejota al final has incluido estos atributos? si no están, prefieres que lance un issue aparte con la propuesta?

hola, están ya desde hace un tiempo (el nombre es ligeramente distinto, mira los atributos de la entidad)

un saludo

**Comment by darguez** [comment]
Pues qué extraño, los únicos atributos que veo de € son `month_€` y `last_month_€`.

La versión que tengo creo que es 2023.02.01

**Comment by darguez** [comment]
> Pues qué extraño, los únicos atributos que veo de € son `month_€` y `last_month_€`.
> 
> La versión que tengo creo que es 2023.02.01

¿Puede ser que no me aparezcan esos nuevos atributos porque no se me cargan nuevos datos desde el 13 de febrero?
