### ISSUE TITLE
Error 429 otra vez

### ISSUE THREAD

**Issue by PacmanForever** [uvejota/homeassistant-edata#138]
Buenos días,

pensava que esto estava arreglado, pero veo que no del todo.

Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:191
First occurred: 6 de desembre de 2022, a les 14:48:34 (6 occurrences)
Last logged: 7 de desembre de 2022, a les 14:53:39

    429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?

**Comment by mcarlosro** [comment]
Yo también tengo ese problema. Mi última actualización fue el 4 de diciembre.

**Comment by damaca** [comment]
Estoy en el mismo caso. Mi impresión tras ver los logs es que tras una consulta pesada donde acaba muriendo por timeout se empieza a reintentar posteriormente, teniendo el 429 al haber hecho la consulta recientemente. En mi caso nunca llega a salir de ahí, parece que los reintentos en los que se tiene el 429 hacen que entre en un bucle.

**Comment by uvejota** [comment]
Según Datadis, una consulta sólo se registra si devuelve un código 200 (éxito), y ahí empiezan las 24h de intervalo. La integración hace lo mismo.

Eventualmente puede ocurrir lo que indica @damaca (timeouts), pero no debería resultar en ningún "bucle".

En cualquier caso, el timeout está establecido a valores enormes (del orden de medio minuto), que en una petición HTTP es más que suficiente. Si tarda más, es claramente un problema de sus servidores.

Se pueden mejorar cosillas de la integración en este mecanismo, pero difícilmente vamos a poder solucionar algunos de estos problemas.

En cualquier caso, ¿Se os llegó a solucionar?
