### ISSUE TITLE
No hace la primera conexión

### ISSUE THREAD

**Issue by javirln** [uvejota/homeassistant-edata#140]
Hola buenas tardes,

Al instalar la integración y seguir los pasos del README, me encuentro con los siguientes logs en HA:

![Screenshot 2023-01-04 at 15 25 31](https://user-images.githubusercontent.com/4128269/210576262-2fa53513-2b0c-49e3-be7a-65b3621242d9.png)

En Datadis, aparecen datos, tengo al un solo supplier y parece que está todo en orden. Comentar qué tengo las ultimas versiones tanto de HA como de la integración.

El problema es que no aparecen datos pero sin embargo si puedo verlos sin problemas en Datadis.

Un saludo y gracias.

**Comment by javirln** [comment]
Si desactivo las opciones de billing y de PVPC, el error es diferente:
![Screenshot 2023-01-04 at 15 41 26](https://user-images.githubusercontent.com/4128269/210579693-f525bd48-6467-4037-be93-8096dfc624bb.png)

Sin embargo, si tengo un supplier. Al consultar la información de supplier desde Datadis, esta es la información:
```json
[ {
  "address" : "La direccion",
  "cups" : "El CUPS",
  "postalCode" : "El codigo postal",
  "province" : "La provincia",
  "municipality" : "La ciudad",
  "distributor" : "El distribuidor",
  "validDateFrom" : "2021/03/30",
  "validDateTo" : "",
  "pointType" : El tipo de punto?,
  "distributorCode" : "El coding del distribuidor"
} ]
```

Como se ve, lo unico que sale vacío es el campo `validDateTo`

**Comment by javirln** [comment]
He seguido mirando y he hecho lo siguiente, como parecía que el problema pudiera estar en la dependencia, [python-edata](https://github.com/uvejota/python-edata/tree/dev), me he descargado el repositorio y, en la rama `dev`, con mis credenciales, funciona todo fantásticamente, usando el snippet de README del repo y no importa que el campo ese este vacío.

Igual es algo que se introdujo desde el ultimo commit en la ultima release de la dependencia hasta el ultimo que hay dentro de la rama `dev`.

**Comment by javirln** [comment]
Borrandolo todo y haciendo una instalación desde 0 parece que soluciono el problema, cierro la issue para que quede limpio.

Muchas gracias por la integración.

**Comment by uvejota** [comment]
La magia de la programación.

Me alegra que lo solucionaras.

Gracias a ti por el feedback.
