### ISSUE TITLE
Errores varios en la descarga de datos

### ISSUE THREAD

**Issue by lufegut** [uvejota/homeassistant-edata#144]
Aparentemente no da ningun error, pero no he recibido mas datos desde el 1 de enero.

¿como puedo acceder a los logs para ver que está pasando?

**Comment by currentrutherfordium** [comment]
A mi me pasa lo mismo pero me ha dejado de funcionar desde el día 7 de Enero

**Comment by lufegut** [comment]
Ahora que lo reviso de nuevo...a mi tambien, el ultimo día que recibí datos fue el 7 de enero.

**Comment by VictorvandenHoven** [comment]
The same here from January 9th:

![Screenshot_2023-01-20-12-45-35-75_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/26108282/213687890-75e21479-97e0-4bc7-a659-feff97a73e06.jpg)

**Comment by madmalkav** [comment]
Me pasa lo mismo.

**Comment by edersong** [comment]
a mi también, la última actiualización es de 6 de enero pasado.

**Comment by quiqueroca** [comment]
Lo mismo desde el 17
![8A987A5E-009E-4E23-81C9-39543C48EE4B](https://user-images.githubusercontent.com/51929173/214396235-7659bf89-1c73-4673-8bad-ea56b8740e39.jpeg)

**Comment by Murada99** [comment]
Lo mismo también desde el 17

![image](https://user-images.githubusercontent.com/48693406/214428876-8beef949-af94-4eeb-8064-1dd81920aabe.png)

**Comment by lugrinder** [comment]
Igual, el día 15 fue el último día con datos.

**Comment by albertobmha** [comment]
Lo mismo, desde el día 6 de enero nada, ha vuelto a recargar y con figurar y nada. En datadis la verdad que siempre me da error al ver mis datos.
No se muy bien interpretar los datos, pero si me comentas lo intento hacer ;-)

![Screenshot_20230126-075244_Home Assistant](https://user-images.githubusercontent.com/81884417/214774961-d41175cc-b1d6-4feb-885d-caddfe67dece.jpg)

**Comment by FifasCat** [comment]
Me uno a los demás compañeros. Desde el 09/01/2023 no me cargan los datos.
Quiero agradecer desde aquí el trabajazo de la integracion.

**Comment by 50l3r** [comment]
Me quedo por aqui ya que tengo el mismo problema 😁

**Comment by PacmanForever** [comment]
Me pongo a la cola!! Nada desde el día 8.

**Comment by edersong** [comment]
El mio ha acabado de actualizar.

**Comment by jcs86** [comment]
Igual desde el 7 de enero. Escribí a Datadis y me dijeron que es q la distribuidora no cargaba los datos hasta que facturarse. Vamos que no tenían ni idea. Ahora mismo la página de Datadis no funciona

**Comment by PacmanForever** [comment]
Hola, en mi caso datadis tiene mis datos hasta el 27 de enero y HA no muestra nada desde el 8 de enero. 
Datadis no lo pone fácil con tantos cambios, pero la integración tampoco funciona correctamente y es una lástima.
Si tuviera más información en los logs para saber de donde viene el problema, echaría una mano para arreglarlo.

Por cierto, ahora la información de la api esta aquí, igual puede ayudar.

![imagen](https://user-images.githubusercontent.com/37216513/215707798-a383ac61-0f83-4c6f-8731-8fcf1b2ef4bc.png)

**Comment by VictorvandenHoven** [comment]
> Igual desde el 7 de enero. Escribí a Datadis y me dijeron que es q la distribuidora no cargaba los datos hasta que facturarse. Vamos que no tenían ni idea. Ahora mismo la página de Datadis no funciona

January 12th I received this from Endesa:
![image](https://user-images.githubusercontent.com/26108282/215717982-04b6e9d5-a322-459e-a97f-3b091aefa255.png)

May be the data is just not at Datadis yet.

**Comment by tergontor** [comment]
Mi caso es el mismo, sin datos desde el día 11 de enero, he eliminado y vuelto a instalar edata pero sigue igual.  Nota: la primera vez que lo hice me salió un código CUPS de 5 dígitos pero no cargaba nada. La segunda ya si salió el código de cuatro digitos habitual.  También comentar que en otra vivienda se me actualiza sin problema, allí está montado HA en una raspberry y aquí en un NUC. No sé si esto tiene que ver.

**Comment by jcs86** [comment]
Yo también en Nuc, aunque no creo que tenga que ver. Suministradora Naturgy por si ayuda

**Comment by FifasCat** [comment]
Yo tengo una raspberry Pi, así que no es. También me funciona bien la web de Dadadis. Hay algún problema e  el programa. seguro que lo solucionan pronto.

**Comment by quiqueroca** [comment]
Ya carga datos . 😁 tras actualizar HA

**Comment by PacmanForever** [comment]
Yo no he hecho ningún cambio y ha cargado, pero tengo la sensación que el problema no se ha resuelto mágicamente.

**Comment by jcs86** [comment]
A mi por ahora nada de nada

**Comment by albertobmha** [comment]
A mi ha dia de hoy ya me ha recargado toda la información!! Podría ser problema de datadis?

**Comment by jcs86** [comment]
Yo ya tengo datos del día 1, veremos a ver si sigue actualizando o tenemos que esperar otro mes, y como me decían solo lo cargan cuando facturan. Una pregunta offtopic, os tarda en abrir la app móvil por tener en el Dashboard los gráficos?

**Comment by uvejota** [comment]
Buenas a todos, me temo que son temas de Datadis o de las distribuidoras. Mi instalación va perfectamente, hubo un retraso de unos 6 días a principios de año, pero se recuperó y va como siempre.

Si no hay logs de error es que no hay ningún error por nuestra parte (o no debiera), simplemente Datadis no devuelve datos (lo cual no puede considerarse un error, puesto que simplemente puede significar que no estén disponibles).

**Comment by uvejota** [comment]
> Yo ya tengo datos del día 1, veremos a ver si sigue actualizando o tenemos que esperar otro mes, y como me decían solo lo cargan cuando facturan. Una pregunta offtopic, os tarda en abrir la app móvil por tener en el Dashboard los gráficos?

Entiendo que algo retrasará la apertura, y será más notable en los terminales menos potentes. En mi caso (iPhone 11) es inapreciable.

En cualquier caso, estoy trabajando en una serie de tarjetas para e-data (sin fecha de lanzamiento, voy lento porque no tenía ni puñetera idea de TypeScript), para evitar utilizar el componente apexcharts-card, y optimizarlo para nuestro caso de uso particular.

**Comment by jcs86** [comment]
> > Yo ya tengo datos del día 1, veremos a ver si sigue actualizando o tenemos que esperar otro mes, y como me decían solo lo cargan cuando facturan. Una pregunta offtopic, os tarda en abrir la app móvil por tener en el Dashboard los gráficos?
> 
> Entiendo que algo retrasará la apertura, y será más notable en los terminales menos potentes. En mi caso (iPhone 11) es inapreciable.
> 
> En cualquier caso, estoy trabajando en una serie de tarjetas para e-data (sin fecha de lanzamiento, voy lento porque no tenía ni puñetera idea de TypeScript), para evitar utilizar el componente apexcharts-card, y optimizarlo para nuestro caso de uso particular.

No son poco potentes, Poco F3. Pero cierto que las tablets menos potentes quedan pilladas. Perfecto si lo vas a mejorar, gran trabajo

**Comment by lufegut** [comment]
Ayer puse un email a datadis, quejandome, porque en su web, tampoco estaban los datos desde el 7 de enero, y hoy, de repente han aparecido hasta el 31 de enero, y se me han cargado tambien en la integracion...no se si habrá sido casualidad, o si habrán tocado algo. Aun así seguimos con 5 días de retraso...

**Comment by popoff1998** [comment]
En la web de datadis puedo ver mis consumos hasta ayer, 18/2/2023.

En mi HA, en el json edata.storage_TC0F, en la clave "consumptions", el último valor que tengo es este:
```
      {
        "datetime": "2023-02-01T01:00:00",
        "delta_h": 1,
        "value_kWh": 2.013,
        "real": true
      }
```
que coincide como es lógico con lo que me reprensentan las gráficas de la integración. Sin embargo en la clave "pvpc" si tengo datos de ayer:
```
      {
        "datetime": "2023-02-18T23:00:00",
        "value_eur_kWh": 0.1905,
        "delta_h": 1
      }
```
Por tanto se está bajando algunos datos actualizados de datadis, pero no los de consumption. Por cierto, mi distribuidora es e-distribucion

**Comment by popoff1998** [comment]
Si antes escribo antes se arregla, ya tengo los datos de ayer ... Será que datados lee esto.

**Comment by tergontor** [comment]
Pues en mi caso no tenía datos desde el 10 de enero, mandé un correo a
Datadis y a los tres días ya tuve datos hasta el 8 de febrero. Desde ese
día hasta ahora na de na. Da la sensación que, en mi caso, falla algún
automatismo y solo se cargan datos si lo hacen de manera manual previo
aviso por email.
Saludos

**Comment by kaciker** [comment]
Sin datos desde fin de Enero, pero dentro de Datadis tampoco hay. Borre antes la integración y al crearla de nuevo he perdido todo el histórico. Mandado un mail para que lo revisen.... pero después entro en UFD y veo que tampoco hay datos.... a si que el origen del problema es UFD

**Comment by PacmanForever** [comment]
¿Alguien lo tiene actualizado en marzo más tarde del día 3?

**Comment by destaben** [comment]
a mí no me carga datos desde el 28 de Febrero, tampoco los tengo en datadis desde esa misma fecha así que igual es el origen que no los carga

**Comment by Murada99** [comment]
Ultimo el 5 de Abril e in datadis hay hasta el 9 de Abril

**Comment by jjvelar** [comment]
Hola,
@uvejota:
No me carga los datos desde el 8 de junio de 2023.
Tengo instalada la versión 202306.03.
Gracias!

José

**Comment by jjvelar** [comment]
Hola!
Alguna novedad con esto?
Gracias y un saludo,
José

**Comment by arnauos** [comment]
A mi me dejó de funcionar el día 12 de Junio, he activado el debug pero no veo ningún error que me llame la atención. He verificado y en Datadis están todos los datos disponibles.

**Actualización**: ayer día 1 se cargaron todos los datos sin hacer nada en especial... será entonces un problema con la api de datadis que va según le apetece?

**Comment by javiermartingonzalez** [comment]
A mi en UFD que es mi caso, no me ha cargado nada del mes de junio hasta primeros de julio, he abierto incidencia en UFD

**Comment by lufegut** [comment]
UFD carga los datos cuando le da la gana...

**Comment by javiermartingonzalez** [comment]
Antes cargaba al menos a mi a los 2-3 días, pero ahora nada. Antes me iba bien las peticiones al contador y ahora dan error, es como que no estuviera conectado en tiempo real desde hace 1-2 meses

**Comment by lufegut** [comment]
A mi siempre me ha cargado con un par de días de retraso. Pero en Enero cuando abrí este tema, dejó de cargar. Y empezó a cargar los datos de golpe, cada vez que acababa un mes, y luego no cargaba nada, hasta que acababa el mes siguente y se cargaban los datos del mes anterior de golpe. Puse un monton de reclamaciones a UFD, y me respondian que ese era el funcionamiento normal. A pesar de que les demostraba que no era cierto, con capturas antiguas, en las que se veía que los datos se actualizaban a diario.

Total que dí el tema por perdido.
Pues sin haber mediado nada, desde hace un par de semanas, la situación se ha "normalizado", y vuelven a volcar datos con un par de días de retraso...

Yo creo que el principal problema es que ni ellos saben como funciona...

**Comment by javiermartingonzalez** [comment]
Yo tengo 2 CUPS, y uno de ellos sigue cargando a los 2 días, y el otro me pasa lo que comentas, a fin de mes... he abierto reclamación pero todavía sin respuesta. Pero si, ellos no deben de tener ni idea, en mi caso parece que el terminal se ha desconectado de Internet de la consulta en directo... pero son muy chapuzas.

Para otra gestión, también me estuvieron mareando, será cuestión de esperar

**Comment by jjvelar** [comment]
Sigue sin cargar datos desde el 8 de junio.
@uvejota: alguna idea de cuál puede ser la causa y cómo se puede arreglar?
Gracias y un saludo,

José

**Comment by cdeharo** [comment]
Seguimos igual, se carga de golpe el mes anterior y se queda sin actualizar hasta que termina el mes actual. El último dato que tengo ahora mismo es `last_registered_date: 2023-08-02T06:00:00`

**Comment by jjvelar** [comment]
Pues yo estoy sin datos desde el 8 de junio. 
Hay algo que se pueda hacer para al menos coger los datos mensualmente?
Gracias

**Comment by mabusdogma** [comment]
Este error se originó a partir de una integración personalizada.

Logger: custom_components.edata.coordinator
Source: helpers/update_coordinator.py:313
Integration: Integración edata (documentation, issues)
First occurred: 11:25:58 p. m. (4 occurrences)
Last logged: 11:28:31 p. m.

Error requesting edata_al0x data: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
Error requesting edata_lw0x data: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

Parece no poder descomprimir los datos

**Comment by divemasterjm** [comment]
este es el error que tengo desde 15/3 que no actualiza
502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> at https://datadis.es/api-private/api/get-contract-detail?
