### ISSUE TITLE
500 error por un mes incompleto

### ISSUE THREAD

**Issue by b0g3r** [uvejota/homeassistant-edata#146]
Yo tengo un contract con `startDate: "2022/12/14"`, y recibo regularmente el error 500 para la solicitud `get-consumption-data`. Revisé y la integración está solicitando datos desde 2022/12 hasta 2023/02, pero si solicito los datos manualmente 2023/01 hasta 2023/02, obtengo los datos. 

Creo que el problema está en el mes 12 incompleto, porque datadis 500. 

¿Cómo saltar un mes?

**Comment by hugo1721** [comment]
Mismo problema, error 500, mi contrato empezó el 12 de Diciembre.

**Comment by uvejota** [comment]
Mismo problema que en #152

Voy a implementar un fix para saltarnos esos meses cuando se vuelven puñeteros
