### ISSUE TITLE
Gráfico detalles sin datos

### ISSUE THREAD

**Issue by jumavi** [uvejota/homeassistant-edata#15]
En primer lugar gracias por tu trabajo, lo veo muy útil. 

El problema que tengo es que los gráficos de los detalles me aparecen sin datos no se que puedo estar haciendo mal, la información del sensor está pero no se refleja en los gráficos.
![Captura de pantalla 2021-09-02 094938](https://user-images.githubusercontent.com/50085845/131804442-d8381dfb-7904-412c-81ce-ee1ddc273c98.jpg)

Tampoco me aparace el atrubuto "last_month_pvpc_€" ¿eso será culpa de la compañia, yo tengo UDF
![Captura de pantalla 2021-09-02 095209](https://user-images.githubusercontent.com/50085845/131804684-8cc61a7d-c89a-4030-b2d6-f4d508f7c438.jpg)

Gracias de antemano.

**Comment by uvejota** [comment]
Si la información sale en el sensor, el problema está en la configuración de las tarjetas. 

¿Has reemplazado el valor de xxxx por los 4 últimos caracteres del cups (en minúscula, tal y como aparece en la entidad (sensor.edata_abcd)?

**Comment by jumavi** [comment]
Lo del PVPC resuelto, gracias.
La tarjeta la tengo así, crei que es correcta
![Captura de pantalla 2021-09-02 120257](https://user-images.githubusercontent.com/50085845/131824823-8a052126-4d21-4897-84b7-d60471200657.jpg)

**Comment by salvasacie** [comment]
Tengo el mismo problema que el usuario **jumavi**. No me aparecen los datos de _Ayer, Mes en curso y Mes pasado_

**Comment by uvejota** [comment]
@jumavi @salvasacie 

Hola a ambos, por partes:

Si tenéis atributos rellenos en el sensor (como @jumavi) es muy extraño que la tarjeta no funcione, ya que muestra los datos del atributo en concreto... por asegurarnos, copiad y pegad el nombre de la entidad ("sensor.edata_xxxx") en los campos `entity` de la tarjeta (a veces las l parecen 1, y similar). No sé mucho más que decir, ¡hay poco más que se pueda configurar en ella! Si el nombre de la entidad y el del atributo están ok, debería funcionar 😢 

Si el caso es otro (y el sensor no arroja datos) puede ser un fallo del componente, o un error de configuración, y eso ya tendríamos que verlo con más detalle.

¡Un saludo!

**Comment by salvasacie** [comment]
**SOLUCIONADO.**
-----------------------

Tengo "recorder integration" en mi HA para gestionar el historial de estado de los sensores que quiero que se almacenen en la DB.
He incluido sensor.edata_XXXX en el "recorder integración" de mi HA y ahora sí aparece los gráficos tipo tarta.

Gracias por tu gran trabajo.

Un saludo.

**Comment by javi581** [comment]
Gracias, **salvasacie**, desde que creé el archivo recorder.yaml solo he tenido problemas, uno detrás de otro….
Ahora todo funciona

**Comment by jumavi** [comment]
Sí señor ! funcionando, gracias @salvasacie, solo con añadir el sensor en recorder se soluciona.
@uvejota sería buena idea comentarlo en las instrucciones.

Gracias !
