### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by PacmanForever** [uvejota/homeassistant-edata#150]
Hola,

sigo teniendo problemas para que se carguen los datos en HA y que sí existen en datadis.
Mirando los logs he visto esto:

```
500 {"timestamp":"2023-02-16T07:46:36.481+0000","status":500,"error":"Internal Server Error","message":"**Connect to nikola-back-private:8085 [nikola-back-private/10.1.101.27**] failed: Connection refused (Connection refused)"} at https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXX&distributorCode=X&startDate=2023/01&endDate=2023/02&measurementType=0&pointType=5&
```

¿Esto os pasa a todos?

Gracias

**Comment by uvejota** [comment]
Conforme saco algo de tiempo intento averiguar por qué a algunos no os funciona, pero no doy con la tecla... 

Seguiré revisando, a ver... 

¿Sigue sin cargarte nada?

**Comment by acarrilloa** [comment]
Gracias por el esfuerzo uvejota
A mí me cargó la información hasta el 5 de febrero, cuando salió la nueva versión de HA, ya e-data no podía acceder a datadis.
He modificado el _init_.py como indicas, vuelvo c conectar pero únicamente recupera la información hasta el 5 de febrero.
Adjunto un fichero con los registros.
[home-assistant_edata_2023-02-18 corto.txt](https://github.com/uvejota/homeassistant-edata/files/10774920/home-assistant_edata_2023-02-18.corto.txt)

**Comment by PacmanForever** [comment]
> Conforme saco algo de tiempo intento averiguar por qué a algunos no os funciona, pero no doy con la tecla...
> 
> Seguiré revisando, a ver...
> 
> ¿Sigue sin cargarte nada?

No tengo datos nuevos desde el día 4 de febrero, en datadis hay hasta este finde.
