### ISSUE TITLE
The provided scups parameter is not correct: XXXX

### ISSUE THREAD

**Issue by luismipr** [uvejota/homeassistant-edata#151]
I installed this component, but is not working propertly
this is te error appear in logs:

`ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX`

Home Assistant 2023.2.5
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

Version component: 2022.12.4

**Comment by uvejota** [comment]
Hello, that error happens when cards config is not properly set. Revise your config and replace every `XXXX` coincidence to match your entity/cups ending.
