### ISSUE TITLE
Error endpoint get-consumption-data al consultar el mismo mes del inicio de contrato

### ISSUE THREAD

**Issue by alexgraupera** [uvejota/homeassistant-edata#152]
¡Hola! ¡¡¡Primero de todo agradecer el trabajo de @uvejota en este proyecto!!! 👏🏻

No sé si esto también le pasará a alguien y quería comentarlo por aquí. 

Hace tiempo que en el log de HA veo que hay una consulta recurrente en el endpont `get-consumption-data` que retorna un error 500. El contrato de mi suministro tiene como fecha inicial `2022-03-29` y analizando la url que da el error recurrente, curiosamente en los parámetros `startDate` y `endDate` el mes informado es `2022-03` (siempre la misma fecha)

Detalle log de HA:

`2023-02-17 21:08:17.109 ERROR (SyncWorker_4) [edata.connectors.datadis] 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-02-17T21:08:17.089+0100"} at https://datadis.es/api-private/api/get-consumption-data?cups=XXXXXXXXXXXXXXXXXXXXXX&distributorCode=2&startDate=2022/03&endDate=2022/03&measurementType=0&pointType=5&`

También he probado de realizar la llamada desde Postman, y efectivamente, para el mes `2022/03` me retorna un status `500`. Si acabo informando, por ejemplo, el mes siguiente (que coincide con un mes hábil o entero) el endpoint retorna los datos correctamente (por ejemplo, `2022/04`)

```
{
    "status": 500,
    "error": "INTERNAL_SERVER_ERROR",
    "message": "500 Internal Server Error",
    "timestamp": "2023-02-17T17:28:34.975+0100"
}
```

Si analizo el fichero de datos donde se almacena la información obtenida, tengo datos a partir de los días 29, 30 y 31 de marzo de 2022, que coincide con el inicio de mi contrato de suministro, por lo que me hace pensar que estaba funcionando y por algún posible cambio en la api de Datadis (¿el cambio de formato de fecha en los parámetros `startDate` y `endDate`?) dejó de funcionar.

Otra posibilidad es que tenga un problema en los datos de mi suministro y he intentado enviar un contacto a la plataforma. de Datadis. No sé si contestarán...

Si esto ya está tratado por aquí, pido disculpas por adelantado (no encontré algo relacionado) 🙏🏻
Si se necesita algún dato aidcional, pues nada, intentaré aportarlo 😊

¡¡Saludos y muchas gracias!! 👋🏻

**Comment by uvejota** [comment]
Buenos días, parece ser que, en algunos casos, consultar el consumo del primer mes de contrato da error.

Como os pasa a muchos, implementaré algún mecanismo para ignorar estos periodos cuando de un par de veces error, o algo así. 

El lado del servidor se comporta de forma inconsistente, supongo que dependerá de la distribuidora también. Por eso a algunos nos va, a otros no... ¡Es una pena! 

Un saludo

**Comment by alexgraupera** [comment]
¡Hola @uvejota!

He investigado un poco más y parece alguna inconsistencia de datos por parte de la api de Datadis. En la distribuidora aparecen los datos sin problema.

Incluso desde la web o UI de Datadis, tampoco aparecen (eso si, ahí no aparece ningún error 🙂)

Si necesitas cualquier dato o prueba, adelante. 

¡Saludos y gracias!

**Comment by uvejota** [comment]
Creo que ocurre con frecuencia con el primer mes de contrato, si este es incompleto. Pero sólo con algunas distribuidoras (en mi caso va ok). ¿Cuál es la tuya?

Gracias

**Comment by alexgraupera** [comment]
¡Buenas! e-distribucion

**Comment by jgarridoalcazar** [comment]
Añado información por si es de utilidad. En mi caso tengo 3 contratos distintos con e-Distribucion en la siguientes situaciones:

- Contrato con cambio de comercializadora hace 30 días. Aparecen datos en la UI de Datadis, pero siempre da error ("Internal Server Error") a través de la API. En un par de días sabré si al hacer un mes empieza a proporcionar datos.
- Contrato con cambio de comercializadora de ayer. Aún no aparecen datos en la UI de Datadis, y también da error en todas las consultas de consumo a través de la API.
- Contrato sin cambio de comercializador desde hace tiempo. Devuelve datos tanto en la API como en Datadis. Todo funciona correcto.

Por tanto, parece que no hay mucha solución. Además, coincido con @alexgraupera en que han debido hacer algún cambio en el comportamiento de la API, dado que en los cambios de comercializadora que tuve antes esto no ocurría.

En fin, a esperar que pase el mes

**Comment by alexgraupera** [comment]
¡Hola de nuevo!

Solo confirmar que desde el último fix #154 ya no aparece el error del primer mes 👏🏻
Muchas gracias por la rapidez @uvejota 

También comentar que me puse en contacto con soporte de Datadis y me confirmaron que tienen reportado este problema de extracción de datos para el mes de inicio de contrato. Están trabajando con la distribuidora para solucionarlo (sin timing especificado)

¡Saludos!

**Comment by uvejota** [comment]
Pues si está confirmado por Datadis... poco que hacer :)

La última versión de edata es menos pesada con este error.

Gracias por la info. Lo dejamos por aquí por si le sucede a más personas.
