### ISSUE TITLE
Actualizar la versión de edata desde HACS?

### ISSUE THREAD

**Issue by popoff1998** [uvejota/homeassistant-edata#153]
Hola. 

Veo que desde la actualización de HASS 2023-3, la función async_setup_platforms ha sido sustituida por async_forward_entry_setups, y que ya lo tienes implementado en el commit del ticket #148.

En los logs tengo este mensaje:

> Logger: homeassistant.helpers.frame
> Source: helpers/frame.py:77
> First occurred: 09:50:04 (1 occurrences)
> Last logged: 09:50:04
> 
> Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for edata using this method at custom_components/edata/__init__.py, line 22: hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> 

Instalé edata desde HACS y tengo la release 2022.12.4, y no se donde decirle que actualize a la 2023.01.1 que es la que lo lleva corregido. El caso es que no se si será por esto que en HASS tengo datos solo hasta el 1/2/2023, a lo mejor es por otro problema diferente.

En cualquier caso me gustaría saber si las actualizaciones son automáticas y si no como habría que hacerlas. Si el problema de actualización puede ser por otro motivo, agradecería alguna indicación. Por supuesto que desde la web de datadis tengo acceso a los consumos del día anterior al que consulte y no están los consumos "congelados" a esa fecha que he puesto.

**Comment by uvejota** [comment]
Hola, si quieres actualizar a alguna beta desde HACS, prueba a darle a Reinstalar y luego marcar la casilla de "Mostrar versiones beta". En cualquier caso ya la he habilitado como "stable".

Sobre los consumos congelados, os pasa a algunos, tengo que ver por qué. Por lo general cuando esto ocurre, es cosa de la API de Datadis, pero tengo que confirmarlo. Me temo que la API va regular en algunas distribuidoras, o algo, pero debe haber algún patrón que desconozco. En mi caso, e-Distribución, va al día (dos contadores distintos).

Cierro esto y podemos seguir la discusión en #144. Que os pasa a varios, y así dejamos la info recopilada si te parece.

Gracias
