### ISSUE TITLE
Maximeter no actualiza la estadística desde 27/08/2022

### ISSUE THREAD

**Issue by sergiobrillo** [uvejota/homeassistant-edata#155]
Hola,

Primero felicitarte por tu trabajo, es de agradecer el tiempo y la dedicación.

Me ocurre una cosa muy rara, desde el 27/08/2022 no se actualiza la estadística del maximeter, he mirado en la base de datos y desde ese día no hay ni un solo registro añadido. El mirado los log y me devuelve lo siguiente (la fecha coincide con el último dato obtenido en la estadística):

`2023-02-21 15:30:13.961 INFO (SyncWorker_10) [edata.helpers] Identified missing maximeter: 2022-08-27T10:30:00 - 2023-02-20T23:59:00`

Espero que puedas darme alguna pista para poder resolverlo. 

Muchas gracias, un saludo.

**Comment by goncal** [comment]
A mi me pasa lo mismo: los últimos datos de maximeter son de agosto de 2022 (en las dos CUPS que monitorizo).
Me sumo también a los agradecimientos por el excelente trabajo y toda tu dedicación @uvejota !

**Comment by sergiobrillo** [comment]
Hola, he usado el servicio "Recreate statistics" y ha conseguido obtener todos los datos faltantes.
