### ISSUE TITLE
Error al actualizar 

### ISSUE THREAD

**Issue by albertobmha** [uvejota/homeassistant-edata#159]
Hola, desde las última actualización, la integración no me funciona, no me deja reinstalar, no reiniciar

Adjunto uno de los logs, que puedo hacer?

Logger: homeassistant.util.package
Source: util/package.py:100
First occurred: 28 de febrero de 2023, 00:26:20 (15 occurrences)
Last logged: 00:07:55

Unable to install package e-data==1.1.0: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/52/6e/b1b4e0182204ac7a57525fe3291878c7421a54d02adbf75ef4d90da9b4cb/e_data-1.1.0-py2.py3-none-any.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))) [notice] A new release of pip available: 22.3 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

**Comment by Danieldiazi** [comment]
Hola.
No sé si tiene mucho que ver, pero veo en otros proyectos problemas similares, por ejemplo aqui: https://github.com/pypa/pip/issues/10963 . Por lo que leo en ese caso, parece que el problema es de un sistema de bloqueo de Vodafone, no sé si es tu caso: "was "Vodafone Secure Net". Vodafone was blocking https://files.pythonhosted.org/
I dissabled it, and now is working like a charm."

**Comment by albertobmha** [comment]
Muy buenas,  pues puede ser el problema, ya que he cambiado de tarifa y me han regalado "Secure Net". 
Voy a desactivarlo y te cuento el resultado. 

Muchas gracias por la ayuda

**Comment by uvejota** [comment]
Como te dicen tiene toda la pinta que el secure net de vodafone es un proxy http, tiene poca solución por nuestra parte. Cierro si no os importa (se me acumulan las issues :) )

**Comment by albertobmha** [comment]
Si, he comprobado desactivando "secure net" y ha vuelto ha funcionar perfectamente.  Perdon por las molestias y muchas gracias por la ayuda. Todo ok
