### ISSUE TITLE
Sin datos que mostrar

### ISSUE THREAD

**Issue by rafasanz** [uvejota/homeassistant-edata#162]
Componente de HACS ok
Integración ok
La entidad creada me muestra contract_p1_kW: 6.9 y contract_p2_kW: 6.9 lo cual es correcto. Sin embargo, el resto de valores están en null. He dejado pasar varias semanas por si necesitara tomar datos y nada, sigue igual. He vuelto a borrar y crear de nuevo la integración y tampoco.

Mirando en el registro aparecen los siguientes errores:

Este error se originó a partir de una integración personalizada.
Logger: custom_components.edata.coordinator
Source: custom_components/edata/coordinator.py:98
Integration: Integración edata (documentation, issues)
First occurred: 11:46:52 (1 occurrences)
Last logged: 11:46:52

Some data is missing, will try to fetch later
Logger: homeassistant.components.sensor
Source: runner.py:179
Integration: Sensor (documentation, issues)
First occurred: 11:47:02 (1 occurrences)
Last logged: 11:47:02
Setup of sensor platform edata is taking over 10 seconds.

Este error se originó a partir de una integración personalizada.
Logger: custom_components.edata.statistics
Source: custom_components/edata/statistics.py:213
Integration: Integración edata (documentation, issues)
First occurred: 11:47:48 (1 occurrences)
Last logged: 11:47:48
Some stats are missing for sk0f

Este error se originó a partir de una integración personalizada.
Logger: custom_components.edata.coordinator
Source: custom_components/edata/coordinator.py:140
Integration: Integración edata (documentation, issues)
First occurred: 11:47:48 (1 occurrences)
Last logged: 11:47:48
Some data is missing, will try to fetch later

Este error se originó a partir de una integración personalizada.
Logger: custom_components.edata.websockets
Source: custom_components/edata/websockets.py:22
Integration: Integración edata (documentation, issues)
First occurred: 11:49:14 (4 occurrences)
Last logged: 11:49:14
The provided scups parameter is not correct: XXXX

El registro detallado es el siguiente:
2023-03-10 11:44:50.698 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration edata which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-10 11:46:52.188 WARNING (MainThread) [custom_components.edata.coordinator] Some data is missing, will try to fetch later
2023-03-10 11:47:02.107 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform edata is taking over 10 seconds.
2023-03-10 11:47:48.922 WARNING (MainThread) [custom_components.edata.statistics] Some stats are missing for sk0f
2023-03-10 11:47:48.927 WARNING (MainThread) [custom_components.edata.coordinator] Some data is missing, will try to fetch later
2023-03-10 11:49:14.826 ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX
2023-03-10 11:49:14.835 ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX
2023-03-10 11:49:14.838 ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX
2023-03-10 11:49:14.840 ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX

Alguna idea de por qué puede estar sucediendo esto?

**Comment by develmts** [comment]
> 2023-03-10 11:49:14.826 ERROR (MainThread) [custom_components.edata.websockets] The provided scups parameter is not > correct: XXXX 2023-03-10 11:49:14.835 ERROR (MainThread) [custom_components.edata.websockets] The provided scups 
> parameter is not correct: XXXX 2023-03-10 11:49:14.838 ERROR (MainThread) [custom_components.edata.websockets] The 
> provided scups parameter is not correct: XXXX 2023-03-10 11:49:14.840 ERROR (MainThread) 
> [custom_components.edata.websockets] The provided scups parameter is not correct: XXXX
> 
> Alguna idea de por qué puede estar sucediendo esto?


Esas XXXX dicen que en algun sitio que tenias que poner los 4 ultimos caracteres de tu CUPS no los has puesto en todos los sitios donde debias.... Eso hace que no se pueda acceder a segun que datos. Repasate la configuracion las cards ...

**Comment by rafasanz** [comment]
Si, la configuración de las cards está revisada y nada. Sigue sin mostrar datos. Cuando en datadis me aparecen datos de consumos diarios, en la gráfica de HA no me aparecen.
Actualmente solo me aparece lo siguiente
<img width="678" alt="image" src="https://user-images.githubusercontent.com/102509029/226305703-19d087ad-e423-40e5-ac4b-07b339c716ee.png">
Alguna idea de qué puede estar pasando?

**Comment by develmts** [comment]
a mi me tardo como 3 dias en aparecer

**Comment by pelayolartategui** [comment]
@rafasanz se te ha solucionado? A mi me sale ese mismo log
```The provided scups parameter is not correct: XXXX``` pese a que la tarjeta de markdown si que puede sacar cual es mi cups

**Comment by rafasanz** [comment]
> @rafasanz se te ha solucionado? A mi me sale ese mismo log `The provided scups parameter is not correct: XXXX` pese a que la tarjeta de markdown si que puede sacar cual es mi cups

Pues tras mucho batallar, el problema reside en la propia comercializadora. Desde antes de tener contrato con ellos vienen acusando numerosos problemas (aún sin resolver) sobre medición y facturación de los clientes. Es por ello que Datadis no recoge los datos porque la comercializadora no lo hace tampoco.

Es más, Datadis muestra más datos que la propia aplicación de la comercializadora. Por lo tanto me temo que luego me llegará una factura importante después de tantos meses.

Un saludo,

En cuanto tenga más información al respecto la compartiré con todos.

**Comment by pelayolartategui** [comment]
Uff, que mal rollo...

Respecto al error ```The provided scups parameter is not correct: XXXX``` te confirmo que es un problema de las cards de la UI. Si sigues viendo esos logs, coge tu dashboard, editalo en yaml y busca XXXX. Cambia las X por las ultimas 4 cifras de tu cups.

**Comment by uvejota** [comment]
Por unificar hilos, lo seguimos en #144
