### ISSUE TITLE
No cargan datos últimos días 

### ISSUE THREAD

**Issue by jbustdel** [uvejota/homeassistant-edata#166]
Desde hace unos días no cargan datos en home Assistant. En datadis están los datos pero no se vuelcan. He cambiado recientemente de compañía. No sé si ahí estará el error.

He borrado la integración y la he vuelto a configurar pero sigue igual.

Alguna idea?.

![Screenshot_20230319-133735](https://user-images.githubusercontent.com/72611008/226175684-7b761bff-2e13-420b-bad4-524280bf9137.png)

**Comment by alex-pardo** [comment]
Tengo el mismo problema. Parece un error de Datadis. En su web aparecen los consumos en la pantalla inicial:
![image](https://user-images.githubusercontent.com/2378470/226304334-676e8682-1895-4235-8e21-765bfc4bcc8e.png)

Pero si juegas con las agrupaciones deja de tener datos:
![image](https://user-images.githubusercontent.com/2378470/226304531-acd7ea17-878d-4f6d-a3e5-7d6f28a304a6.png)

Voy a contactar con ellos.


Edit: Por API puedo autenticarme y solicitar los suministros pero no los consumos:
![image](https://user-images.githubusercontent.com/2378470/226307182-0aa8cb91-f5e9-4e7a-9dfa-b7e45ea9da0f.png)

**Comment by jbustdel** [comment]
Mi problema es que al cambiar de contrato, sólo aparecen los consumos nuevos del nuevo contrato pero no se me vuelcan en HA, sólo veos los antiguos del historial. No sé que pasa.

Creo que el problema es el primer mes que se comenta por aquí.

**Comment by jbustdel** [comment]
Me puse en contacto con datadis y me.comunican que la distribuidora no vuelca los datos y que se pondrán en contacto con ella.

**Comment by jjvelar** [comment]
Pues a ver qué tal, porque yo no tengo datos desde el 5 de marzo

**Comment by gerar19** [comment]
yo estoy igual, los últimos días tampoco me da datos, y en datadis si salían.

**Comment by alex-pardo** [comment]
El servidor de Datadis sigue dando error:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/2378470/227227695-e4025c75-46b8-4fb2-9b44-c33481c8829a.png">

El martes abrieron un ticket con soporte (DATADIS-5904), así que imagino que están en ello. Si me dicen algo más os informo.

**Comment by uvejota** [comment]
Por unificar hilos, lo seguimos en #144
