### ISSUE TITLE
No me carga los datos desde el 12 de Marzo - *** Parece que vuelve

### ISSUE THREAD

**Issue by QuaKim** [uvejota/homeassistant-edata#168]
No me esta cargando los datos desde el 12 de Marzo, y en la web de Datadis veo que estan volcados hasta el dia de ayer.

[image](https://user-images.githubusercontent.com/121525213/228375017-4626ea05-b305-421f-bf73-bd51f55f093c.png)

**Comment by QuaKim** [comment]
Parece que he arreglado algo.

He quitado la integración y la he vuelto a configurar y he visto que que ha creados un nuevo sensor pero con los últimos 5 números del CUPS en vez de los 4.

Antes no me cargaba ningún dato, ahora la menos la potencia máxima... a ver si los acaba de volcar, recuerdo que la primera vez que lo instalé también tardo.

![image](https://user-images.githubusercontent.com/121525213/228380980-2eb8b21e-428f-4c2c-978f-6cbf37b6bd68.png)

**Comment by QuaKim** [comment]
No funcionó, volví a quitar la integración y volver a instalar, y esta vez me volvió a crear el sensor con los 4 caracteres finales solo y no cinco... y ahora si, parece que vuelve a funcionar.

![image](https://user-images.githubusercontent.com/121525213/228976661-6011bfbb-f3ab-4af1-9280-b8fa59edcf04.png)

**Comment by uvejota** [comment]
Por unificar hilos, lo seguimos en #144
