### ISSUE TITLE
Los datos dejan de actualizarse cuando cambias de distribuidora

### ISSUE THREAD

**Issue by mardito** [uvejota/homeassistant-edata#169]
Buenas, el pasado 24 de marzo hice un cambio de comercializadora y desde entonces he dejado de recibir datos.
He activado las trazas y veo esto en los logs de HA:

* 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-04-12T15:40:28.673+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ES003140XXXXXXXXXXXXXX&distributorCode=2&startDate=2022/07&endDate=2022/07&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
* 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-04-12T15:51:33.954+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ES003140XXXXXXXXXXXXXX&distributorCode=2&startDate=2022/08&endDate=2022/08&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
* 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-04-12T15:52:03.780+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ES003140XXXXXXXXXXXXXX&distributorCode=2&startDate=2022/09&endDate=2022/09&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
* 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-04-12T16:53:47.536+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ES003140XXXXXXXXXXXXXX&distributorCode=2&startDate=2022/11&endDate=2022/11&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
* 500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-04-12T18:54:44.334+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ES003140XXXXXXXXXXXXXX&distributorCode=2&startDate=2023/03&endDate=2023/03&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart

Si entro en datadis, veo todos los datos correctamente.
Si hago peticiones al API directamente a través del Postman, veo que la única petición que me ofrece datos es la del mes en curso (startDate=2023/04&endDate=2023/04), pero esa petición no la veo en las trazas. 

Estuve unos días esperando por si se solucionaba solo, pero veo que no tiene pinta.
También probé a desinstalar esta integración, reiniciar HA y volver a instalarla, pero tampoco aparecen los datos.

¿alguna idea de qué puede estar pasando y de cómo solucionarlo?

Muchas gracias de antemano.

**Comment by mardito** [comment]
Tras darle un vistazo a las todas las issues, entiendo que está relacionado con lo indicado en [#152 ](https://github.com/uvejota/homeassistant-edata/issues/152)

**Comment by uvejota** [comment]
Afirmativo @mardito 

Poco que hacer por nuestra parte, es una jodienda...

Te cierro el hilo para evitar duplicados :)
