### ISSUE TITLE
No descarga consumos anteriores al 31-05-2021

### ISSUE THREAD

**Issue by joseal70** [uvejota/homeassistant-edata#17]
Hola,

No se si es problema de la integración o de las tarjetas, están configuradas como en la documentación con 365d en la de consumo mensual  y 1y en la de Maxímetro.

El caso es que en la tarjeta de Consumo mensual solo sale desde el mes de Mayo y en la de Maxímetro solo las potencias de los dos últimos meses. En la web de datadis sí salen los datos de los demás meses.

Probé a borrar el fichero edata.storage_xxxx y reiniciar HA y sigue igual. Versión v0.1.7-beta.11

![Screenshot_20210907-182935](https://user-images.githubusercontent.com/63608768/132382075-35013099-056b-484a-be25-d1eea35bdf56.jpg)

Consumo mensual en datadis
![Screenshot_20210907-183821](https://user-images.githubusercontent.com/63608768/132382109-b8deeae1-68a4-456e-a677-e897ae383ff6.jpg)

Potencia en datadis
![Screenshot_20210907-071600](https://user-images.githubusercontent.com/63608768/132382201-750d68dd-5ba0-4206-9ed9-8e34f720fa38.jpg)

Edito: He visto que estaba la versión v0.1.8-b4. He actualizado pero sigue igual.

Un saludo y muchas gracias.

**Comment by uvejota** [comment]
Hola, claramente es cosa de la integración. 

Tengo alguna idea de lo que puede ser: ¿Has cambiado de contrato por mayo?

¡Un saludo!

**Comment by uvejota** [comment]
En cualquier caso @joseal70, acabo de subir un fix que igual resuelve tu problema, versión v0.1.9-b1

¡Ya me dices!

**Comment by joseal70** [comment]
Hola, sí pero fue en febrero, cambié de 2.0A a 2.0DH y me cambiaron el contrato.
Pruebo la versión nueva y te digo

**Comment by joseal70** [comment]
Nada, sigue igual.
Esto es lo que sale en log:

2021-09-08 15:44:10 WARNING (SyncWorker_5) [edata.connectors] Connector: still missing the following consumption ranges [{'from': datetime.datetime(2020, 9, 1, 0, 0), 'to': datetime.datetime(2021, 5, 31, 0, 0)}, {'from': datetime.datetime(2021, 9, 7, 23, 0), 'to': datetime.datetime(2021, 9, 8, 15, 43, 47, 783440)}], will try again later

**Comment by uvejota** [comment]
Ummm... curioso. 

¿Puedes abrir y ver en el fichero /config/.storage/edata_xxxx qué fechas de contratos te reconoce?

Es un json, haz un control+F de "contracts" y a esa sección me refiero :-)

**Comment by joseal70** [comment]
Sigue saliendo desde mayo.

        "contracts": [
            {
                "date_start": "2021-05-31T00:00:00",
                "date_end": "2021-09-09T00:00:00",
                "marketer": "CURENERGIA S.L.U.",
                "distributorCode": "8",
                "power_p1": 5.75,
                "power_p2": 5.75
            }

**Comment by uvejota** [comment]
Qué curioso, pues parece que tu distribuidora en lugar de registrar un nuevo contrato, lo sobrescribió, por eso no lo caza e-data.

¿En "supplies" qué fechas te salen?

**Comment by joseal70** [comment]
Estas fechas:

                "date_start": "1970-01-01T00:00:00",
                "date_end": "2021-09-09T00:00:00",

**Comment by joseal70** [comment]
Por si te sirve de ayuda, en datadis me sale solo un suministro/contrato y la fecha es del 31-05-2021.
En la web de datadis sí salen los consumos y potencias anteriores al 31-5

![Screenshot_20210908-162645](https://user-images.githubusercontent.com/63608768/132529186-20cd768d-2de5-4963-8425-734f71c6e554.jpg)

**Comment by uvejota** [comment]
@joseal70 tengo que mirarlo, se me ocurren varios apaños, lo anoto para la próx. versión. 

¡Gracias!

**Comment by joseal70** [comment]
Vale, si es fácil de apañar perfecto, pero si ves que es complicado, y solamente me pasa a mi, tampoco te quiero liar.


Muchas gracias

**Comment by veromarlo** [comment]
Hola, a mi me aparece exactamente igual, me empieza a contar a partir del 31 de mayo, me aparecen los mismos datos en "contracts"; por si os puede servir de ayuda.

**Comment by uvejota** [comment]
Supongo que os pasa a varios, y supongo que es cosa de las malas prácticas de las distribuidoras... que por aligerar se han dejado la mitad de las cosas por registrar.

No os preocupéis, todo tiene solución, trataré que no sea demasiado chapuza :-)

Os aviso por aquí cuando necesite testeo, ¡Gracias!

**Comment by joseal70** [comment]
Muchas gracias uvejota 👍

**Comment by veromarlo** [comment]
> Supongo que os pasa a varios, y supongo que es cosa de las malas prácticas de las distribuidoras... que por aligerar se han dejado la mitad de las cosas por registrar.
> 
> No os preocupéis, todo tiene solución, trataré que no sea demasiado chapuza :-)
> 
> Os aviso por aquí cuando necesite testeo, ¡Gracias!

**Comment by veromarlo** [comment]
Gracias!!!!!

**Comment by uvejota** [comment]
Hola, probad con https://github.com/uvejota/homeassistant-edata/releases/tag/v0.1.9-b2 a ver qué pasa :-)

**Comment by joseal70** [comment]
Hola uvejota,

Sigue igual, y he comprobado que el fichero edata.storage_XXX se ha actualizado después de la instalación.


![Screenshot_20210917-131207](https://user-images.githubusercontent.com/63608768/133774425-e1c08ffa-1569-478b-bca9-1ccf3b189703.jpg)


Está advertencia sale en el registro, por si te sirve:
![Screenshot_20210917-131100](https://user-images.githubusercontent.com/63608768/133774419-a91ace5f-4964-4418-a2ae-5f09739d312e.jpg)

**Comment by uvejota** [comment]
La anterior tenía un bug estúpido... 

¿Puedes probar esta? 
https://github.com/uvejota/homeassistant-edata/releases/tag/v0.1.9-b3

**Comment by joseal70** [comment]
Con esta ya aparece el consumo mensual anterior al 31/5 👍, pero en la gráfica del Maxímetro sigue apareciendo solo la potencia máxima de los dos últimos meses.

![Screenshot_20210917-135706](https://user-images.githubusercontent.com/63608768/133779514-df7f25cd-bc3b-4a6e-a9ac-cdf736d7f5d5.jpg)


![Screenshot_20210917-135719](https://user-images.githubusercontent.com/63608768/133779548-2c2a492d-654b-4f96-8bc7-029b00e07208.jpg)

**Comment by uvejota** [comment]
Jeje, siempre me queda algo por retocar. 

Te aviso cuando arregle eso :-)

**Comment by joseal70** [comment]
Ok, gracias.

Y sólo como curiosidad, ¿sabes por qué no me aparece la gráfica lineal? 
Lo tengo configurado como el del ejemplo de la documentación, incluso he probado a cambiar el color, por si fuera algún problema de que fuese igual que el fondo.




![Screenshot_20210917-141118__01](https://user-images.githubusercontent.com/63608768/133781175-acb13b86-970d-4134-a694-8e71be676075.jpg)

**Comment by veromarlo** [comment]
Mismo resultado que el compañero, la gráfica mensual bien, el maxímetro no ha variado

**Comment by arnauos** [comment]
A mi me pasa algo similar, en datadis aparece todo el histórico pero al importar los datos solo veo los consumos desde que cambié de comercializadora el 24/11 y en máximetro de momento sin datos.

Tanto en contracts como supplies, la fecha de inicio que aparece es la del cambio de comercializadora.

**Comment by uvejota** [comment]
> A mi me pasa algo similar, en datadis aparece todo el histórico pero al importar los datos solo veo los consumos desde que cambié de comercializadora el 24/11 y en máximetro de momento sin datos.
> 
> Tanto en contracts como supplies, la fecha de inicio que aparece es la del cambio de comercializadora.

Es una pu**da, porque literalmente no tengo nada que hacer ahí.

La integración lee fechas de supplies y explora los contratos, y luego va contrato por contrato resolviendo los consumos en esos rangos. Si han modificado erróneamente la fecha del alta del suministro (supplies) no tengo forma alguna de "darme cuenta". 

Lo único que podría hacer más adelante es permitir al usuario forzar (a mano) una fecha de inicio y tomarla como referencia... pero no me termina de convencer la idea.

**Comment by arnauos** [comment]
Pues si, son un poco chapuceros con estas portabilidades, no se si depende de la distribuidora pero a mi e-Distribución me lo ha hecho en 2 de 2 cups 😅

¿Tiene sentido que respetemos la date_start tanto del supply como del contract? Vamos, poniendo 1970 tanto en el contract como en el supply y ya datadis que devuelva lo que tenga para ese CUPS... no tengo claro si esto supondría un problema para algún caso de uso concreto 🤔

**Comment by uvejota** [comment]
> Pues si, son un poco chapuceros con estas portabilidades, no se si depende de la distribuidora pero a mi e-Distribución me lo ha hecho en 2 de 2 cups 😅
> 
> ¿Tiene sentido que respetemos la date_start tanto del supply como del contract? Vamos, poniendo 1970 tanto en el contract como en el supply y ya datadis que devuelva lo que tenga para ese CUPS... no tengo claro si esto supondría un problema para algún caso de uso concreto 🤔

La API de datadis (concretamente la petición del maxímetro) falla si los rangos son inadecuados. Pero creo que para los consumos es tolerante... tengo que probar ;)
