### ISSUE TITLE
Error conexión API Datadis - No descarga datos

### ISSUE THREAD

**Issue by Rodrixx05** [uvejota/homeassistant-edata#171]
Hice la configuración inicial de la integración el día 18 de abril y todo OK, me descargó todo el histórico disponible. A partir de aquí, vi que no me ha descargado ningún dato más. He mirado el registro de logs y me sale el siguiente error:

2023-04-20 02:18:37.699 WARNING (SyncWorker_1) [edata.connectors.datadis] 502 <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.22.1</center>
</body>
</html>
 at https://datadis.es/api-private/api/get-max-power?cups=ESXXXXXXXXXXXXXXX&distributorCode=2&startDate=2023/04&endDate=2023/04&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart

(He substituido por X el código CUPS).

Cuando he reiniciado en ocasiones anteriores me salia el mismo error para el endpoint de get-consumption-data 

Sabéis a qué puede ser debido?

Muchas gracias

**Comment by Rodrixx05** [comment]
Un apunte que quiero dejar: hace poco que soy el titular del suministro (mediados de marzo aproximadamente) y veo que todavía no tengo datos de maxímetro en Datadis. Podría ser este el foco del problema?

**Comment by uvejota** [comment]
Issue "duplicada", lo seguimos en #144
