### ISSUE TITLE
Sin datos desde 03/Abril

### ISSUE THREAD

**Issue by alextoro82** [uvejota/homeassistant-edata#172]
Hola
No me descarga datos desde hace varias semanas, pero en Datadis si que se ven los datos de cada día.
He probado a desinstalar la integración y volver a ponerla y todo igual.
Adjunto captura
![62809C18-F75C-43F4-B7C2-5A1EA2452864](https://user-images.githubusercontent.com/117019247/233854167-5cf1dd80-2102-48e5-83bf-54515d16e0e8.jpeg)

**Comment by ebesuman** [comment]
Me ocurre exáctamente lo mismo, también desde el día 3 de abril
![Captura de pantalla 2023-04-24 152534](https://user-images.githubusercontent.com/43756234/234009974-1177a0e7-f352-426a-8abf-9c1f6d306ff1.png)

**Comment by ebesuman** [comment]
He probado a desinstalar la integración, e incluso a borrar las estadísticas de la BBDD de Home Assistant, sin éxito...

**Comment by paloke** [comment]
Estoy igual, a demás, cuando intento configurarla de nuevo no aparecen las leyendas de las opciones.

![imagen](https://user-images.githubusercontent.com/2188389/234587210-19ddae36-ebac-456b-8083-a9d5415d057f.png)

**Comment by jjvelar** [comment]
Yo estoy igual desde el 9 de abril.
¿Alguien lo ha podido resolver?
Alguna idea, @uvejota?
Gracias!

**Comment by JokeRsevilla** [comment]
yo estoy igual desde el 2 de abril...

**Comment by alextoro82** [comment]
Hoy ha cargado hasta el día 30-Abril
No se que habrá pasado

**Comment by jjvelar** [comment]
A mí también me ha cargado esta noche todo abril.

**Comment by cdeharo** [comment]
Probablemente esté relacionado con https://github.com/uvejota/homeassistant-edata/issues/176

**Comment by uvejota** [comment]
Por unificar hilos, lo seguimos en #144
