### ISSUE TITLE
Solo ha importado los datos del 7 mayo

### ISSUE THREAD

**Issue by dmartinezs** [uvejota/homeassistant-edata#174]
Buenos días,
En mi caso la integración únicamente descarga datos 1 vez al mez ( cuando los actualiza datadis ). Este mes aunque en datadis aparecen perfectamente los consumos, en home assistant únicamente se han importado los datos del 7 de mayo. O sea que desde el 7 de abril al 6 mayo no hay datos.

¿ Cómo hay que hacer para forzar la descarga de nuevo ?
<img width="257" alt="image" src="https://github.com/uvejota/homeassistant-edata/assets/59379566/adc9f5e2-bc34-49ac-9738-9f484d1a482a">

En la web de datadis hay datos todos los días:
<img width="329" alt="image" src="https://github.com/uvejota/homeassistant-edata/assets/59379566/46ce28f7-8674-4fe1-9627-b04dc7cb3f9b">

**Comment by infoscoot** [comment]
Yo en mi caso tambien me ocurre algo similar, solo tengo datos hasta 11 de mayo.En Datadis aparece todo ok hasta el dia anterior(entiendo que es la demora de 1 dia en que vuelcan los datos).He probado de conectar a la api directamente con Postman y tambien aparecen los datos del dia anterior...entonces entiendo que es un problema de edata en Home Assistant que no conecta correctamente...?Es raro...en mi caso tengo Home Assistant OS última versión.

**Comment by dmartinezs** [comment]
Mi problema es que únicamente tengo los datos del día 7 de mayo y me faltan todos los anteriores. 

Indicas que usas Postman, ¿ es posible forzar de nuevo la descarga de datos ?.

**Comment by infoscoot** [comment]
No te lo puedo aclarar, simplemente utilizé postman para revisar que no hubiera algún problema al conectar con la Api.A mí se me ha actualizado a fecha 23/5 pero ya vuelve a no recoger los datos via edata y en datavis si que  estan...un misterio!

**Comment by dmartinezs** [comment]
Se ha actualizado la base de datos y ha importado los datos del 7 al 22 de mayo.

El problema es que me ha dejado un hueco sin datos ( 7 de abril - 6 de mayo ambos inclusive ). ¿ Existe alguna forma de forzar la descarga de esos días ?. En caso negativo, ¿ es posible modificar la base de datos e introducir los datos que faltan a mano ?.

**Comment by uvejota** [comment]
> Se ha actualizado la base de datos y ha importado los datos del 7 al 22 de mayo.
> 
> El problema es que me ha dejado un hueco sin datos ( 7 de abril - 6 de mayo ambos inclusive ). ¿ Existe alguna forma de forzar la descarga de esos días ?. En caso negativo, ¿ es posible modificar la base de datos e introducir los datos que faltan a mano ?.

Si no te salen los datos en ninguna tarjeta puedes borrar los datos del mes completo (del fichero de 'storage') y debería recrearlos. Haz backup del fichero completo por si peta.

Si lo que falla son las estadísticas (panel energía), puedes usar el servicio de recreación de estadísticas de edata.

**Comment by uvejota** [comment]
Por unificar hilos, lo seguimos en #144
