### ISSUE TITLE
Energia vertida

### ISSUE THREAD

**Issue by PutoPunko** [uvejota/homeassistant-edata#175]
Hola,

Veo que en Datadis está disponible la energía vertida sin embargo la integración no la incluye. Es posible añadir dicha medida?

Gracias,

**Comment by alexsalvo1** [comment]
El problema es que no esta disponible en la API.

**Comment by PutoPunko** [comment]
OK, queda claro.

Gracias por responder

**Comment by PutoPunko** [comment]
@alexsalvo1 

He recibido un mail de DATADIS indicando un cambio en el API con la energia vertida. Significa eso que se podría añadir a la integración?

Gracias,

----------INICIO MENSAJE----------

Estimado usuario de DATADIS,

 

Hemos añadido algunas mejoras en nuestra API, para poder mostrar datos referentes al autoconsumo.

 

A continuación detallamos los servicios afectados: 


 https://datadis.es/api-private/api/get-consumption-data.
Se añade el campo "surplusEnergyKWH" donde vendrá informada la energía vertida (si la tiene)

      

      EJEMPLO DE LLAMADA

      https://datadis.es/api-private/api/get-consumption-data?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5

 

      EJEMPLO DE RESPUESTA JSON

 

      [ {

  "cups" : "ES00XXXXXXXXXXXXXXXXXF",

  "date" : "2023/05/01",

  "time" : "01:00",

  "consumptionKWh" : 0.0,

  "obtainMethod" : "Real",

  "surplusEnergyKWh" : 0.567

  }]

 

https://datadis.es/api-private/api/get-contract-detail
Se han añadido nuevos campos al contractual-detail. La respuesta aportará más información sobre el autoconsumo (si lo tuviera):

Se añaden los siguientes campos:

·         "selfConsumptionTypeCode": Tipo de autoconsumo (código CNMC).

·          "selfConsumptionTypeDesc" : Descripción del tipo de autoconsumo.

·         "section": Sección del registro.

·         "subsection": Subsección del registro. 

·         "partitionCoefficient": Coeficiente de reparto.

·         "cau".  Código que identifica la instalación de autoconsumo.

·         "installedCapacity": Potencia de generación instalada

 

      En caso de que no se tenga autoconsumo, estos campos vendrán con valor null.

 

      EJEMPLO DE LLAMADA 

 

      https://datadis.es/api-private/api/get-contract-detail[?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2](https://datadis.es/api-private/api/get-consumption-data?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5)

 

 

      EJEMPLO DE RESPUESTA JSON

[ {
  "cups" : "ES00XXXXXXXXXXXXXX",
  "distributor" : "I-DE REDES ELÉCTRICAS INTELIGENTES, S.A.U.",
  "marketer" : "IBERDROLA CLIENTES, S.A.U",
  "tension" : "Baja tensión",
  "accessFare" : "BAJA TENSION y POTENCIA <= 15 kW",
  "province" : "Madrid",
  "municipality" : "MADRID",
  "postalCode" : "00000",
  "contractedPowerkW" : [ 6.9, 6.9 ],
  "timeDiscrimination" : "",
  "modePowerControl" : "ICP",
  "startDate" : "2023/01/31",
  "endDate" : "",
  "codeFare" : "2T",
  "selfConsumptionTypeCode" : "41",
  "selfConsumptionTypeDesc" : "Con excedentes y compensación Individual",
  "section" : "2",
  "subsection" : null,
  "partitionCoefficient" : 100.0,
  "cau" : "ES00XXXXXXXXXXXXXX",

  "installedCapacity" : 5000.0

**Comment by uvejota** [comment]
Afirmativo, lo implementaré en cuanto pueda.

El 14 jun 2023, a las 17:18, PutoPunko ***@***.***> escribió:

﻿

@alexsalvo1<https://github.com/alexsalvo1>

He recibido un mail de DATADIS indicando un cambio en el API con la energia vertida. Significa eso que se podría añadir a la integración?

Gracias,

----------INICIO MENSAJE----------

Estimado usuario de DATADIS,

Hemos añadido algunas mejoras en nuestra API, para poder mostrar datos referentes al autoconsumo.

A continuación detallamos los servicios afectados:

https://datadis.es/api-private/api/get-consumption-data.
Se añade el campo "surplusEnergyKWH" donde vendrá informada la energía vertida (si la tiene)

      

      EJEMPLO DE LLAMADA

      https://datadis.es/api-private/api/get-consumption-data?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5

      EJEMPLO DE RESPUESTA JSON

      [ {

"cups" : "ES00XXXXXXXXXXXXXXXXXF",

"date" : "2023/05/01",

"time" : "01:00",

"consumptionKWh" : 0.0,

"obtainMethod" : "Real",

"surplusEnergyKWh" : 0.567

  }]

https://datadis.es/api-private/api/get-contract-detail
Se han añadido nuevos campos al contractual-detail. La respuesta aportará más información sobre el autoconsumo (si lo tuviera):

Se añaden los siguientes campos:

· "selfConsumptionTypeCode": Tipo de autoconsumo (código CNMC).

· "selfConsumptionTypeDesc" : Descripción del tipo de autoconsumo.

· "section": Sección del registro.

· "subsection": Subsección del registro.

· "partitionCoefficient": Coeficiente de reparto.

· "cau". Código que identifica la instalación de autoconsumo.

· "installedCapacity": Potencia de generación instalada

      En caso de que no se tenga autoconsumo, estos campos vendrán con valor null.

      EJEMPLO DE LLAMADA

      https://datadis.es/api-private/api/get-contract-detail[?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2](https://datadis.es/api-private/api/get-consumption-data?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5)<https://datadis.es/api-private/api/get-contract-detail%5B?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2%5D(https://datadis.es/api-private/api/get-consumption-data?cups=ES00XXXXXXXXXXXXXXX0F&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5)>

      EJEMPLO DE RESPUESTA JSON

[ {
"cups" : "ES00XXXXXXXXXXXXXX",
"distributor" : "I-DE REDES ELÉCTRICAS INTELIGENTES, S.A.U.",
"marketer" : "IBERDROLA CLIENTES, S.A.U",
"tension" : "Baja tensión",
"accessFare" : "BAJA TENSION y POTENCIA <= 15 kW",
"province" : "Madrid",
"municipality" : "MADRID",
"postalCode" : "00000",
"contractedPowerkW" : [ 6.9, 6.9 ],
"timeDiscrimination" : "",
"modePowerControl" : "ICP",
"startDate" : "2023/01/31",
"endDate" : "",
"codeFare" : "2T",
"selfConsumptionTypeCode" : "41",
"selfConsumptionTypeDesc" : "Con excedentes y compensación Individual",
"section" : "2",
"subsection" : null,
"partitionCoefficient" : 100.0,
"cau" : "ES00XXXXXXXXXXXXXX",

"installedCapacity" : 5000.0

**Comment by alexsalvo1** [comment]
Si lo vi hace unos dias. Creo que @uvejota comentaba en otro hilo que lo iba a implementar.
Entiendo que hay que esperar que tenga el tiempo de dedicarle 😀
