### ISSUE TITLE
Sensor edata con last_registered_date: 2023-05-02T17:00:00

### ISSUE THREAD

**Issue by cdeharo** [uvejota/homeassistant-edata#176]
Hola,

Desde el día 2 de mayo no se han rellenado datos en el sensor de uno de mis CUPS.

Si intento obtener los datos manualmente usando Postman con `https://datadis.es/api-private/api/get-consumption-data` me devuelve la información completa. En la web de Datadis también aparece la información completa.

También he intentado eliminar la integarción y volver a añadirla, sin cambios. No hay logs de error (excepto los provocados por mi al hacer la consulta con Postman antes de abrir este bug, que ha provocado el `429 Consulta ya realizada en las últimas 24 horas`).

Tengo otros CUPS que están devolviendo los datos correctamente.
El CUPS que falla es el único con excedentes solares y se cambió de contrato (que no de distribuidora) en marzo (lo comento por descartar el bug [Los datos dejan de actualizarse cuando cambias de distribuidora #169](https://github.com/uvejota/homeassistant-edata/issues/169)).

*Home Assistant:* 2023.5.3
*homeassistant-edata:* 2023.02.1

Acabo de activar los logs en debug para ver si arrojan algo de luz. Dime si necesitas algo más.

Gracias

**Comment by uvejota** [comment]
Sospecho, por lo que comentó otro usuario, que el timeout que he puesto es insuficiente para la obtención de los datos de algunos suministros…

Voy a intentar sacar algo de tiempo para hacer este cambio y vemos. Está siendo un año de locos.

Un saludo

El 20 may 2023, a las 8:53, cdeharo ***@***.***> escribió:

﻿

Hola,

Desde el día 2 de mayo no se han rellenado datos en el sensor de uno de mis CUPS.

Si intento obtener los datos manualmente usando Postman con https://datadis.es/api-private/api/get-consumption-data me devuelve la información completa. En la web de Datadis también aparece la información completa.

También he intentado eliminar la integarción y volver a añadirla, sin cambios. No hay logs de error (excepto los provocados por mi al hacer la consulta con Postman antes de abrir este bug, que ha provocado el 429 Consulta ya realizada en las últimas 24 horas).

Tengo otros CUPS que están devolviendo los datos correctamente.
El CUPS que falla es el único con excedentes solares y se cambió de contrato (que no de distribuidora) en marzo (lo comento por descartar el bug Los datos dejan de actualizarse cuando cambias de distribuidora #169<https://github.com/uvejota/homeassistant-edata/issues/169>.

Home Assistant: 2023.5.3
homeassistant-edata: 2023.02.1

Acabo de activar los logs en debug para ver si arrojan algo de luz. Dime si necesitas algo más.

Gracias

**Comment by cdeharo** [comment]
Gracias @uvejota , no hay prisa.

Por si sirve de ayuda, desde Postman, ha tardado 1442ms en responder a la siguiente petición con 161KB de respuesta:
```
GET /api-private/api/get-consumption-data?cups=XXXXXXXXXXXXX&distributorCode=2&startDate=2023/04&endDate=2023/05&measurementType=0&pointType=5 HTTP/1.1
Host: datadis.es
```

He tenido que poner abril y mayo ya que hoy, al poner solamente mayo, me devolvía 500 Internal Server Error.

**Comment by uvejota** [comment]
Entonces no sé yo… ahora mismo tiene un timeout de 1 minuto. Probaré también a emular otros user-agents, a ver si están haciendo cosas raras

El 20 may 2023, a las 23:13, cdeharo ***@***.***> escribió:

﻿

Gracias @uvejota<https://github.com/uvejota> , no hay prisa.

Por si sirve de ayuda, desde Postman, ha tardado 1442ms en responder a la siguiente petición con 161KB de respuesta:

GET /api-private/api/get-consumption-data?cups=XXXXXXXXXXXXX&distributorCode=2&startDate=2023/04&endDate=2023/05&measurementType=0&pointType=5 HTTP/1.1
Host: datadis.es

**Comment by Ovonuiz** [comment]
Buenas tardes,
me ocurre exactamente lo mismo que a @cdeharo.

El CUPS que está dando fallos es también con excedentes solares y el contrato se cambió en marzo (también sigo con la misma distribuidora). 

La instalación solar llevaba un par de meses y todo bien, dejó de obtener datos el mismo día del cambio de contrato.
Probé con otras versiones de Home Assistant y homeassistant-edata.

Gracias. 
Un saludo.

**Comment by cdeharo** [comment]
Aún no me ha dejado logs de DEBUG la integración, ¿dejará logs con las peticiones y respuestas que realiza?

El último log que tengo es de ayer al mediodía. Dice que la consulta está repetida en las últimas 24h, esto me parece normal, ya que seguramente renicié el HA. Pero si aprovecho estos logs para ver las consultas que se realizan puedo ver diferéncias entres los CUPS que van bien y el que no:
```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:191
First occurred: May 19, 2023 at 20:57:14 (8 occurrences)
Last logged: May 20, 2023 at 13:19:52

429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?cups=VABIEN1&distributorCode=2&startDate=2023/05&endDate=2023/05&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-consumption-data?cups=VABIEN2&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?cups=VABIEN2&distributorCode=2&startDate=2023/05&endDate=2023/05&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2023/04&endDate=2023/04&measurementType=0&pointType=5&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2023/05&endDate=2023/05&measurementType=0&pointType=5&
```

* `VABIEN1`: tiene una única llamada para *mayo* de `get-max-power`.
* `VABIEN2`: tiene dos llamadas para *mayo*: `get-max-power` y `get-consumption-data`.
* `ELQUEFALLA`: tiene dos llamadas, una para *abril* y otra para *mayo*, y ambas son `get-consumption-data`

¿Puede que el hecho de tener llamadas para abril y mayo esté indicando que algo le pasa a este CUPS? ¿O simplemente estas son las que se están considerando repetidas y todos están haciendo lo mismo?

Por otro lado, en la respuesta que obtengo de Postman veo que los datos de la última hora recibida son 0.0 y con valores muy pequeños (0.002), no sé si esto tendrá algo que ver al procesarlos (aunque no creo, ya que antes de estos ya tengo consumos de 0.0, pero lo dejo aquí por si ayuda):
```json
{
  "cups" : "ELQUEFALLA",
  "date" : "2023/05/02",
  "time" : "17:00",
  "consumptionKWh" : 0.0,
  "obtainMethod" : "Real"
}, {
  "cups" : "ELQUEFALLA",
  "date" : "2023/05/02",
  "time" : "18:00",
  "consumptionKWh" : 0.002,
  "obtainMethod" : "Real"
}, {
  "cups" : "ELQUEFALLA",
  "date" : "2023/05/02",
  "time" : "19:00",
  "consumptionKWh" : 0.0,
  "obtainMethod" : "Real"
}, {
  "cups" : "ELQUEFALLA",
  "date" : "2023/05/02",
  "time" : "20:00",
  "consumptionKWh" : 0.44,
  "obtainMethod" : "Real"
}
```

**Comment by cdeharo** [comment]
Actualizo con algunos logs que recopilé a finales de mayo (e interesantes novedades en junio):
```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:206
First occurred: May 23, 2023 at 21:24:48 (20 occurrences)
Last logged: May 25, 2023 at 14:19:01

502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2022/05&endDate=2022/05&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2022/05&endDate=2022/05&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/03&endDate=2023/03&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
502 <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html> at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/04&endDate=2023/04&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"I/O error on POST request for \"http://nikola-middleware:8086/middleware/edistribucion/potencias\": Connect to nikola-middleware:8086 [nikola-middleware/10.1.245.118] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to nikola-middleware:8086 [nikola-middleware/10.1.245.118] failed: Connection refused (Connection refused)","timestamp":"2023-05-25T14:19:01.751+0200"} at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/05&endDate=2023/05&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
```
```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:191
First occurred: May 19, 2023 at 20:57:14 (14 occurrences)
Last logged: 08:32:51

429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2022/07&endDate=2022/07&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2022/11&endDate=2022/11&measurementType=0&pointType=5&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2023/03&endDate=2023/03&measurementType=0&pointType=5&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2022/11&endDate=2022/11&
429 Consulta ya realizada en las últimas 24 horas. at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/03&endDate=2023/03&
```

```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:175
First occurred: May 22, 2023 at 21:01:06 (47 occurrences)
Last logged: May 25, 2023 at 14:18:58

Timeout at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2023/03&endDate=2023/03&measurementType=0&pointType=5&
Timeout at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2023/04&endDate=2023/04&measurementType=0&pointType=5&
Timeout at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/03&endDate=2023/03&
Timeout at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/04&endDate=2023/04&
Timeout at https://datadis.es/api-private/api/get-max-power?cups=ELQUEFALLA&distributorCode=2&startDate=2023/05&endDate=2023/05&
```
```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:132
First occurred: May 23, 2023 at 22:49:44 (107 occurrences)
Last logged: May 24, 2023 at 05:09:50

Unknown error while retrieving token, got <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.22.1</center> </body> </html>
Unknown error while retrieving token, got <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>Microsoft-Azure-Application-Gateway/v2</center> </body> </html>
Unknown error while retrieving token, got <html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.22.1</center> </body> </html>
```

El 4 de junio a la 1:53:36 CET cambió el estado del sensor edata (`last_registered_date: 2023-06-02T07:00:00`) rellenando todo el periodo de mayo de golpe hasta el 2 de junio a las 0:00. Desde ese día no ha vuelto a actualizarse (los otros CUPS sí que se han actualizado). 

En los logs encuentro el siguiente error:
```
Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.10/site-packages/edata/connectors/datadis.py:206
First occurred: June 6, 2023 at 23:28:19 (3 occurrences)
Last logged: 02:35:21

500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-06-06T23:28:19.715+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2022/06&endDate=2022/06&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-06-07T01:32:02.025+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2022/07&endDate=2022/07&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
500 {"status":500,"error":"INTERNAL_SERVER_ERROR","message":"500 Internal Server Error","timestamp":"2023-06-07T02:35:21.266+0200"} at https://datadis.es/api-private/api/get-consumption-data?cups=ELQUEFALLA&distributorCode=2&startDate=2022/08&endDate=2022/08&measurementType=0&pointType=5&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart
```

Con esta información quizá puedas acotar mejor el problema. Dime si necesitas algo más.

**Comment by uvejota** [comment]
He subido el timeout en la versión 2023.06.1 (a 3 minutos), debería corregir algunos casos, aunque me temo que no todos.

Los errores con código superior o igual a 500 son por parte del servidor, aunque puede ser que estén haciendo cosas raras en función del user-agent del cliente. Tengo que probar (lo cual es difícil si sólo puedo hacer 1 prueba cada 24h...)

Seguiremos informando :)

**Comment by cdeharo** [comment]
Gracias!

Quizá Datadis ofrezca una API KEY sin esta limitación para desarrolladores... ¿Has contactado con ellos?

**Comment by Yoryigil** [comment]
Hola

Tengo el mismo problema que a @cdeharo.
En mi caso funciono unos cuantos días con excedentes solares, he cambiado de compañía a Iberdrola y desde que cambie ha dejado de recibir información, en datadis tengo info actualizada correctamente.

Tengo otros cups de tarifas 6.1 y estos si que cargan datos sin problemas (evidentemente los tramos P no los coge bien, mientras no se agregen tramos horarios de las tarifas 6.1) los totales mensuales si que coinciden.

Gracias por compartir tu trabajo y enhorabuena por la excelente herramienta que has creado
Un saludo

**Comment by uvejota** [comment]
> Hola
> 
> Tengo el mismo problema que a @cdeharo. En mi caso funciono unos cuantos días con excedentes solares, he cambiado de compañía a Iberdrola y desde que cambie ha dejado de recibir información, en datadis tengo info actualizada correctamente.
> 
> Tengo otros cups de tarifas 6.1 y estos si que cargan datos sin problemas (evidentemente los tramos P no los coge bien, mientras no se agregen tramos horarios de las tarifas 6.1) los totales mensuales si que coinciden.
> 
> Gracias por compartir tu trabajo y enhorabuena por la excelente herramienta que has creado Un saludo

La API de Datadis falla en los meses que cambias de comercializadora independientemente de que en su web se vean los datos o no (de lo que deduzco que ellos no usan la misma API que nosotros).

Esto es un error conocido que ya ha sido notificado a datadis por algunos de vosotros, y que no podemos solucionar desde aquí.

Un saludo

(lo de las tarifas 6.1 lo tengo pendiente... pero primero voy a meterle mano al retorno de energía)

**Comment by uvejota** [comment]
> Gracias!
> 
> Quizá Datadis ofrezca una API KEY sin esta limitación para desarrolladores... ¿Has contactado con ellos?

Aún no, quizá lo haga este verano

**Comment by uvejota** [comment]
Hay varias issues referentes a errores en la descarga de datos, lo seguimos en #144 para centralizar un poco vuestras malas experiencias
