### ISSUE TITLE
Tarifa 6.1?? 

### ISSUE THREAD

**Issue by Yoryigil** [uvejota/homeassistant-edata#181]
Hola, antes de nada agradecerte que compartas con todos tu grandísimo trabajo.

Quería preguntarte (si es posible) cual seria el código o que parámetros debo tocar para obtener los mismos datos que da en las tarifas 3.1, creo que añadiendo los tramos P4, P5 y P6 debería reportar la misma información. (desde mi ignorancia claro esta)

Un saludo

**Comment by uvejota** [comment]
Aprovechando que tengo que adaptar esto debido a que Datadis ya muestra la energía excedente vía API, voy a intentar aprovechar para incluir estas tarifas. 

No prometo nada :)

**Comment by Yoryigil** [comment]
Muchísimas gracias, tienes unas cervezas pagas solo por intentarlo, GRACIAS
Un saludo

**Comment by currentrutherfordium** [comment]
+1

**Comment by uvejota** [comment]
Voy a dejar abierto el #8, que trata de lo mismo, y cierro este. Por ordenar un poquito :)
