### ISSUE TITLE
Error tras actualizar a la versión 2023.06.1

### ISSUE THREAD

**Issue by jjvelar** [uvejota/homeassistant-edata#182]
Hola
Tras actualizar a la versión 2023.06.1 de edata, me sale este error al verificar la instalación que me impide reiniciar:

Platform error sensor.edata - Requirements for edata not found: ['e-data==1.1.2'].

Gracias por la ayuda.
Saludos,

José

**Comment by fedelebrero** [comment]
Hola!

Mismo error por aquí, adjunto log.

[home-assistant_2023-06-12T08-03-50.892Z.log](https://github.com/uvejota/homeassistant-edata/files/11719833/home-assistant_2023-06-12T08-03-50.892Z.log)

Aunque este fallo no impide el correcto reinicio de HA.

Saludos!

**Comment by aguilaair** [comment]
Puede que tanga algo que ver con un error en la plataforma?

![image](https://github.com/uvejota/homeassistant-edata/assets/29983481/1b34c01e-a8eb-4cbd-a01e-99303c6fb27e)

tengo el mismo error pero no me impide reiniciar HA

**Comment by jjvelar** [comment]
A ver si @uvejota nos ilumina pronto! :-)

**Comment by uvejota** [comment]
> Puede que tanga algo que ver con un error en la plataforma?
> 
> ![image](https://user-images.githubusercontent.com/29983481/245075326-1b34c01e-a8eb-4cbd-a01e-99303c6fb27e.png)
> 
> tengo el mismo error pero no me impide reiniciar HA

No creo, el error que estáis reportando es por fallo al instalar numpy/pandas.

Estoy dándole al coco.. 

Alguien puede probar a:
1. Hacer backup del fichero de storage de edata
2. Desinstalar edata con HACS
3. Reiniciar HA
4. Volver a instalar la última versión de edata con HACS

Es por descartar que el fallo venga por hacer downgrade de pandas con HACS.

**Comment by jjvelar** [comment]
cómo hago "Hacer backup del fichero de storage de edata"?

**Comment by JokeRsevilla** [comment]
> > Puede que tanga algo que ver con un error en la plataforma?
> > ![image](https://user-images.githubusercontent.com/29983481/245075326-1b34c01e-a8eb-4cbd-a01e-99303c6fb27e.png)
> > tengo el mismo error pero no me impide reiniciar HA
> 
> No creo, el error que estáis reportando es por fallo al instalar numpy/pandas.
> 
> Estoy dándole al coco..
> 
> Alguien puede probar a:
> 
> 1. Hacer backup del fichero de storage de edata
> 2. Desinstalar edata con HACS
> 3. Reiniciar HA
> 4. Volver a instalar la última versión de edata con HACS
> 
> Es por descartar que el fallo venga por hacer downgrade de pandas con HACS.

Lo he hecho, pero no me deja añadir la integración, se queda "Por favor espera, iniciando el asistente de configuración para edata"

EDIT. finalmente ha dado este mensaje: "Error
No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble"

**Comment by jjvelar** [comment]
> > > Puede que tanga algo que ver con un error en la plataforma?
> > > ![image](https://user-images.githubusercontent.com/29983481/245075326-1b34c01e-a8eb-4cbd-a01e-99303c6fb27e.png)
> > > tengo el mismo error pero no me impide reiniciar HA
> > 
> > 
> > No creo, el error que estáis reportando es por fallo al instalar numpy/pandas.
> > Estoy dándole al coco..
> > Alguien puede probar a:
> > 
> > 1. Hacer backup del fichero de storage de edata
> > 2. Desinstalar edata con HACS
> > 3. Reiniciar HA
> > 4. Volver a instalar la última versión de edata con HACS
> > 
> > Es por descartar que el fallo venga por hacer downgrade de pandas con HACS.
> 
> Lo he hecho, pero no me deja añadir la integración, se queda "Por favor espera, iniciando el asistente de configuración para edata"
> 
> EDIT. finalmente ha dado este mensaje: "Error No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble"

Cómo has hecho la copia del fichero de storage de edata y lo pruebo yo también?

**Comment by uvejota** [comment]
> > > Puede que tanga algo que ver con un error en la plataforma?
> > > ![image](https://user-images.githubusercontent.com/29983481/245075326-1b34c01e-a8eb-4cbd-a01e-99303c6fb27e.png)
> > > tengo el mismo error pero no me impide reiniciar HA
> > 
> > 
> > No creo, el error que estáis reportando es por fallo al instalar numpy/pandas.
> > Estoy dándole al coco..
> > Alguien puede probar a:
> > 
> > 1. Hacer backup del fichero de storage de edata
> > 2. Desinstalar edata con HACS
> > 3. Reiniciar HA
> > 4. Volver a instalar la última versión de edata con HACS
> > 
> > Es por descartar que el fallo venga por hacer downgrade de pandas con HACS.
> 
> Lo he hecho, pero no me deja añadir la integración, se queda "Por favor espera, iniciando el asistente de configuración para edata"
> 
> EDIT. finalmente ha dado este mensaje: "Error No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble"

Mmm. ¿Desde modo oculto/borrando cookies también ocurre (he tenido experiencias similares que se solucionaron así)?

**Comment by daniperaleda** [comment]
Por aquí tengo el mismo error. No sé hacer el backup de edata

**Comment by mrbluebrett** [comment]
Otro con el mismo error.

**Comment by JokeRsevilla** [comment]
para hacer la copia de los ficheros que comienzan por edata.storage en la carpeta .storage, simplemente me los he descargado...

**Comment by JokeRsevilla** [comment]
> > > > Puede que tanga algo que ver con un error en la plataforma?
> > > > ![image](https://user-images.githubusercontent.com/29983481/245075326-1b34c01e-a8eb-4cbd-a01e-99303c6fb27e.png)
> > > > tengo el mismo error pero no me impide reiniciar HA
> > > 
> > > 
> > > No creo, el error que estáis reportando es por fallo al instalar numpy/pandas.
> > > Estoy dándole al coco..
> > > Alguien puede probar a:
> > > 
> > > 1. Hacer backup del fichero de storage de edata
> > > 2. Desinstalar edata con HACS
> > > 3. Reiniciar HA
> > > 4. Volver a instalar la última versión de edata con HACS
> > > 
> > > Es por descartar que el fallo venga por hacer downgrade de pandas con HACS.
> > 
> > 
> > Lo he hecho, pero no me deja añadir la integración, se queda "Por favor espera, iniciando el asistente de configuración para edata"
> > EDIT. finalmente ha dado este mensaje: "Error No se pudo cargar el flujo de configuración: 500 Internal Server Error Server got itself in trouble"
> 
> Mmm. ¿Desde modo oculto/borrando cookies también ocurre (he tenido experiencias similares que se solucionaron así)?

Entiendo que te refieres solo a instalar la integración... Mismo resultado...

**Comment by uvejota** [comment]
Necesito un poco de tiempo para replicar el error, ya os comento en cuanto pueda. 

Guardad copia del fichero storage por si haciendo pruebas se os tuerce

**Comment by jjvelar** [comment]
Sin ánimo de meter presión, @uvejota, sólo para aportar más información.

He seguido el proceso que has sugerido y da este error:

`Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble`

**Comment by uvejota** [comment]
2023.06.2 liberada, no tengo demasiada fe, pero a mi me ha funcionado en HA 2023.06.0

Ya me decís...

**Comment by Pabsilon** [comment]
A mi sí me va. La tenía desactivada de esta mañana, he instalado la 2023.06.2 y al reactivarla parece que todo OK.

**Comment by JokeRsevilla** [comment]
coincido con el compañero, 2023.06.2  parece que funciona, sin errores en el registro!

**Comment by JokeRsevilla** [comment]
Mil gracias Uvejota !

**Comment by uvejota** [comment]
A vosotros :)

**Comment by jjvelar** [comment]
yo también lo he podido configurar.
ahora, a ver qué tal va.
muchas gracias!

**Comment by cbolumar** [comment]
Funciona perfecto , ya me ha cargado los datos de los días que me faltaban .

Muchas gracias .
