### ISSUE TITLE
Paquete roto en HA 2023.5.4

### ISSUE THREAD

**Issue by RafaTicArte** [uvejota/homeassistant-edata#187]
Buenas,

La última actualización me ha roto el paquete y da un error en los sensores edata. Copio el mensaje del registro por si es de ayuda.

`Unable to install package e-data==1.1.4: ERROR: Cannot install e-data==1.1.4 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1 -> 23.1.2 [notice] To update, run: pip install --upgrade pip`

Gracias.

**Comment by uvejota** [comment]
Buenas, puedes instalar la versión anterior de edata mientras lo soluciono

**Comment by nitobosch** [comment]
Hola, yo tengo el mismo problema. He probado a bajar de versión o incluso eliminar temporalmente la integración y al verificar la configuración me aparece el mensaje: 
Platform error sensor.edata - Requirements for edata not found: ['e-data==1.1.4'].

**Comment by uvejota** [comment]
La última versión lo soluciona.

HACS es un poco "tricky", igual tenéis que forzar el reinicio de la máquina para que os deje actualizar.
