### ISSUE TITLE
Cambios en la API de DATADIS

### ISSUE THREAD

**Issue by GMTZMU** [uvejota/homeassistant-edata#188]
Buenas, me ha llegado mensaje de DATADIS indicando que hay cambios en la API.

¿Afecta en algo a la descarga de datos?

Gracias.

**Comment by uvejota** [comment]
Nos abre la posibilidad de consultar el excedente (retorno a la red).

Dicha mejora la tengo en cola :)

**Comment by jose2403** [comment]
Excedentes. Esto estaría fantástico. Muchas gracias por tu trabajo.
Al margen de esto, no me carga datos desde el 1 de septiembre. No sé lo que pasa. ¿Es normal?.

**Comment by d4icon** [comment]
> Nos abre la posibilidad de consultar el excedente (retorno a la red).
> 
> Dicha mejora la tengo en cola :)

has podido mirar esto?
gracias!
