### ISSUE TITLE
Energía consumida baja en carbono

### ISSUE THREAD

**Issue by zevayo** [uvejota/homeassistant-edata#189]
Buenos días,

En el panel de energía de Home Assistant, si desgloso la energía añadiendo como consumo de la red los 3 consumos de p1, p2 y p3, el cálculo de energía consumida baja en carbono se vuelve totalmente erróneo con porcentajes por encima de 100% o negativos. Si en vez de 3 consumos de la red, pongo sólo el total parece que calcula bien. ¿Cómo se puede arreglar para tener el desglose de los 3 consumos pero bien el porcentaje de energía consumida baja en carbono? Gracias.

Saludos.

**Comment by uvejota** [comment]
Esto no tengo ni idea, esos cálculos los hace Home Assistant y no tengo muy claro cómo lo hace (o qué datos usa como entrada)

**Comment by zevayo** [comment]
Ok, muchas gracias :)
