### ISSUE TITLE
Timeouts y tiempos de arranque de las integraciones

### ISSUE THREAD

**Issue by Danieldiazi** [uvejota/homeassistant-edata#199]
Hola:
Me estaba dando timeouts otras integraciones, entre ellas "Meteogalicia" y a esta última le subí su propio timeout al doble.
Pero investigando algo más, he visto que hay algo raro, no sé si relacionado con edata, o con la forma en la que funciona HA.
El caso es que si desactivo edata, los timeouts desaparecen. He ido a mirar el tiempo que tardan las integraciones en arrancar y en función de si edata está activo (y con datos) o no, tardan más o menos. Igual es algo que tiene que ver más con HA, pero lo expongo aquí por si le ha pasado a más gente, o por si sabéis cual puede ser la causa.

Por si tenía algo que ver con mi entorno de HA, he creado dos máquinas virtuales en las que he instalado desde cero HA y he hecho varias pruebas para ver los tiempos de arranque. 

Estos son los resultados:

**Entorno: Máquina virtual con HA instalación Supervisor**
Sin edata instalado:

- Home Assistant Supervisor: 5,46
- Meteogalicia: 1,76
- HACS: 0,51

Se ve que todo va normal.

Con edata configurado:

- MeteoGalicia:  8,15s
- Home Assistant Supervidor: 5,4 segundos
- HACS: 3,95s

Aqui ya hay datos descargados y se ve que los tiempos de carga han incrementado.

**Entorno VM - Contenedor**
Sin edata instalado:
- meteogalicia: 1.82 segundos
- Sol: 0,52
- Hacs: 0,49

Todo normal.

Con edata - loading (los atributos tiene datos de contract, pero resto a desconocido):
- meteogalicia: 1.82 segundos
- Sol: 0,52
- Hacs: 0,49

Todo normal.

Con edata - con datos:
- meteogalicia: 21 segundos
- Hacs: 8,03 segundos
- Sol: 1,82

Aquí se ve que suben los tiempos de carga

Con edata - deshabilitado:
- meteogalicia: 1,51 s
- Sol: 0,30
- Hacs: 0,45s

Aquí se ve que vuelve todo a la normalidad.

Con edata - habilitado (con datos) y meteogalicia eliminado
- Hacs: 6,88s
- Google TTS: 13,27s

Siguen tardando en arrancar el resto de integraciones.

La prueba ha sido con Meteogalicia porque la tenía a mano, pero también he hecho las pruebas con otras, como OpenSky con resultados parejos.
La conclusión a priori es que va lento el arranque cuando edata ha conseguido descargarse los datos. ¿Tendrá algo que ver con el proceso de carga de esos datos que afecta a todo lo que en ese momento se esté tratando de arrancar?

Es raro, por lo menos no le encuentro sentido.

**Comment by skgsergio** [comment]
Yo tengo el mismo problema a veces tarda la vida en arrancar homeassistant. Con `edata` desactivado va volando.

![image](https://github.com/uvejota/homeassistant-edata/assets/186349/03454915-355e-4b42-bb3e-040607b867c3)

La cosa es que haciendo profiling hace cosa de un mes vi que parece que en el mismo arranque de la integración empieza a procesar datos y demás con pandas y tira el 100% de la CPU.

**Comment by uvejota** [comment]
Gracias por el informe.

Los tiempos pueden ser simplemente porque las consultas a Datadis son lentísimas (y es posible/seguro que todas las actividades en segundo plano compartan el mismo hilo, retrasando la ejecución del resto).

Pero el procesamiento no debería poner la CPU al 100% mucho rato (de hecho no debería tardar en el orden de milisegundos), sin duda tengo que revisar si hay algo que pueda almacenar para no calcularlo (que seguro).

Volveré...

El 30 ago 2023, a las 23:47, Sergio Conde Gómez ***@***.******@***.***>> escribió:



Yo tengo el mismo problema a veces tarda la vida en arrancar homeassistant. Con edata desactivado va volando.

La cosa es que haciendo profiling hace cosa de un mes vi que parece que en el mismo arranque de la integración empieza a procesar datos y demás con pandas y tira el 100% de la CPU.

**Comment by skgsergio** [comment]
Esto es un profile usando la integracion de [profiler](https://www.home-assistant.io/integrations/profiler) para hacer un profile de 120 segundos e inmediatamente despues dandole a recargar la integración de edata:

![profile](https://github.com/uvejota/homeassistant-edata/assets/186349/6e73fb96-88e1-44fa-87f5-e80b7f8523b0)
