### ISSUE TITLE
No aparecen datos

### ISSUE THREAD

**Issue by ConsolaViejuna** [uvejota/homeassistant-edata#2]
Estupenda integración, gracias por tu trabajo.
He configurado todo según los pasos que indicáis, pero no recibo ningún dato. Poniendo el log em mod debug me encuentro esto:

```
2021-08-12 14:28:59 DEBUG (MainThread) [edata.helpers] ReportHelper: requesting an async update
2021-08-12 14:28:59 DEBUG (SyncWorker_6) [edata.helpers] ReportHelper: requesting an update from 2020-08-01 00:00:00 to 2021-08-12 14:28:59.432491
2021-08-12 14:28:59 DEBUG (SyncWorker_6) [edata.helpers] ReportHelper: updating data from 2020-08-01 00:00:00 to 2021-08-12 14:28:59.432491
2021-08-12 14:28:59 DEBUG (SyncWorker_6) [edata.connectors] DatadisConnector: updating data for CUPS XXXX from 2020-08-01 00:00:00 to 2021-08-12 14:28:59.432491
2021-08-12 14:28:59 DEBUG (SyncWorker_6) [edata.connectors] ignoring update request due to update interval limit
```
Si miro el sensor, aparece como unknow

Dado de alta en e-data, proveedor de datos i-d-e iberdrola

¿Sabéis que puede ser?

Gracias

**Comment by Keiphar** [comment]
A mi me pasa los mismo, la tarjeta no muestra nada y el sensor pone unknown. Yo tengo UFD Grupo Naturgy y me han confirmado el alta esta mañana

**Comment by javier-develop** [comment]
yo creo que el problema se ve mejor en el error que me da a mi

**Comment by javier-develop** [comment]
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:87
First occurred: 10:50:19 (1 occurrences)
Last logged: 10:50:19

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 80, in update
    if self.update_data (self.__cups, date_from, date_to):
  File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 86, in update_data
    return self.__conn.update (cups, date_from, date_to)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 160, in update
    raise e
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 149, in update
    r = self.get_max_power (cups, supply["distributorCode"], contract['date_start'] + relativedelta(months=1), p_date_end)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 248, in get_max_power
    r = self.__send_cmd("https://datadis.es/api-private/api/get-max-power", data=data)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 115, in __send_cmd
    raise ConnectorError (f'{url + params} returned {r.text} with code {r.status_code}')
edata.connectors.ConnectorError: https://datadis.es/api-private/api/get-max-power?cups=ES0031103662844001RB0F&distributorCode=2&startDate=2004/02&endDate=2021/08& returned Parámetro requerido en estado vacío, con formato erróneo, o con valores fuera de rango / Parámetro de ordenación erróneo with code 400

**Comment by uvejota** [comment]
Hola, antes de nada, mil gracias por probar y compartir los logs.

El error debería estar ya solucionado en la v0.1.2, menuda empanada tengo encima. Probad cuando podáis y decirme.

**Comment by javier-develop** [comment]
muchísimas graciasPruebo y ya te digo algoEnviado desde mi Galaxy
-------- Mensaje original --------De: VMG ***@***.***> Fecha: 14/8/21  11:53  (GMT+01:00) Para: uvejota/homeassistant-edata ***@***.***> Cc: javier-develop ***@***.***>, Comment ***@***.***> Asunto: Re: [uvejota/homeassistant-edata] No aparecen datos (#2) 

Hola, antes de nada, mil gracias por probar y compartir los logs.

El error debería estar ya solucionado en la v0.1.2, menuda empanada tengo encima. Probad cuando podáis y decirme.

**Comment by javier-develop** [comment]
Perfecto, la version 0.1.2 funciona

Muchicismas Gracias

**Comment by cuchoverdejo** [comment]
Yo sigo con sensor desconocido, tengo Iberdrola de distribuidora y no me funciona no me aporta datos, lo tengo actualizado a ultima versión que sacaste ayer y nada
![SmartSelect_20210815-120700_Home Assistant](https://user-images.githubusercontent.com/64358611/129474886-0ea7e4d7-b187-4d84-b08d-b88c7fd98d5c.jpg)
![Screenshot_20210815-120623_Home Assistant](https://user-images.githubusercontent.com/64358611/129474889-c758aae3-16d8-4fa5-8ae6-d052570c154b.jpg)

Gracias por tu trabajo y tú tiempo

**Comment by cuchoverdejo** [comment]
La última versión ya me da daros de cup y la potencia contratada pero no me da datos de consumos gracias

**Comment by gurretxu** [comment]
> La última versión ya me da daros de cup y la potencia contratada pero no me da datos de consumos gracias

A mi me pasa exactamente lo mismo. Tengo Iberdrola distribución. Me da el cupos y la pelvis contratada en ambos periodos pero no da más datos.
Puedo darte algo que te ayude a ver de dónde viene el problema? Un saludo

**Comment by javier-develop** [comment]
en la configuración.yaml ¿ habeis puesto la unidad de medida? kWhEnviado desde mi Galaxy
-------- Mensaje original --------De: gurretxu ***@***.***> Fecha: 18/8/21  14:23  (GMT+01:00) Para: uvejota/homeassistant-edata ***@***.***> Cc: javier-develop ***@***.***>, Comment ***@***.***> Asunto: Re: [uvejota/homeassistant-edata] No aparecen datos (#2) 



La última versión ya me da daros de cup y la potencia contratada pero no me da datos de consumos gracias



A mi me pasa exactamente lo mismo. Tengo Iberdrola distribución. Me da el cupos y la pelvis contratada en ambos periodos pero no da más datos.

Puedo darte algo que te ayude a ver de dónde viene el problema? Un saludo

**Comment by gurretxu** [comment]
Arreglado, ya recibe datos. He actualizado la integración a la 0.1.6 y ahora funciona correctamente.
Gracias y buen trabajo!!

**Comment by cuchoverdejo** [comment]
Ya funciona todo perfecto ya aparecen consumos y todo perfecto
