### ISSUE TITLE
Desfase de 1h en la lectura de datos

### ISSUE THREAD

**Issue by Borty97** [uvejota/homeassistant-edata#200]
Hay un desfase de 1h en la lectura de datos que hace la integración en relación a los que proporciona Datadis:
**DATOS INTEGRACIÓN**
![image](https://github.com/uvejota/homeassistant-edata/assets/60492018/83261a65-8d43-4444-b8d3-737d670966a5)
**DATOS DATADIS**
![image](https://github.com/uvejota/homeassistant-edata/assets/60492018/58f732b5-1df3-460d-9b79-08224954bf3f)

## System Information

version | core-2023.8.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.4
os_name | Linux
os_version | 4.4.302+
arch | aarch64
timezone | Europe/Madrid
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4960
Installed Version | 1.32.1
Stage | running
Available Repositories | 1268
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 1, 2018 at 1:00 AM
relayer_connected | false
relayer_region | null
remote_enabled | false
remote_connected | false
alexa_enabled | true
google_enabled | true
remote_server | null
certificate_status | null
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 0
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | August 14, 2023 at 7:57 AM
-- | --
current_recorder_run | August 24, 2023 at 3:21 PM
estimated_db_size | 36.25 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

**Comment by uvejota** [comment]
No hay desfase. Home Assistant indica el consumo en el inicio de la hora (de 00 a 23h) y Datadis en el final (de 01 a 24h). Simplemente es una diferencia de criterio.
