### ISSUE TITLE
No se actualizan los datos ni en HA ni en la web de Datadis

### ISSUE THREAD

**Issue by josemabcn** [uvejota/homeassistant-edata#201]
Hola,

Desde hace mucho tiempo que no me funciona la integración en Home Assistant, he probado a instalarla y desinstalarla, pero no consigo que funcione. He accedido a la web de Datadis y no consigo ver ningún datos de consumos, ni por dia, ni por semana, ni por mes ni por año. Sabeis que le pasa a la web de Datadis?:

![image](https://github.com/uvejota/homeassistant-edata/assets/19243737/488fbb48-d475-4f99-b9d8-cbf5c3482cce)

Gracias,

**Comment by Danieldiazi** [comment]
Hola:

En la web de datadis a mi me funciona perfectamente.  Prueba a contactar con ellos en https://datadis.es/private-contact a ver qué pueden decirte. Porque si no tienes datos en datadis, esta integración no va a descargar nada :(

**Comment by gbasile** [comment]
Estoy con el mismo problema. Me enseña los datos anuales pero no los diarios/semanales/mensuales. 
@josemabcn has podido resolver el problema?

**Comment by JoseHoA** [comment]
Me pasa lo mismo. Pero en la web de datadis la información se muestra bien.
