### ISSUE TITLE
Problemas con recepción de datos. Parche sugerido

### ISSUE THREAD

**Issue by jesus-0262** [uvejota/homeassistant-edata#203]
Buenos días, ante todo reitero mi agradecimiento @uvejota por poner esta integración para Homeassistant que uso desde hace dos años.

Tengo instalada la versión 2023.06.3. Al instalar se actualizan los datos, pero pasado un día no se vuelve a actualizar (como otros reportan).  También he tenido paciencia y he comprobado que si lo instalé en junio, el 2 de julio a media noche se recuperan los datos de junio OK, pero el 3 ya no vuelven a aparecer. además sí aparecen los datos last_registered_day  pero yesterday está completamante a nulll.  También ha ocurrido lo mismo en agosto, septiembre, octubre y noviembre.

last_registered_date: "2023-11-05T23:00:00"
last_registered_day_kWh: 19.28
last_registered_day_hours: 22
last_registered_day_p1_kWh: 0
last_registered_day_p2_kWh: 0
last_registered_day_p3_kWh: 19.28

yesterday_kWh: null
yesterday_hours: null
yesterday_p1_kWh: null
yesterday_p2_kWh: null
yesterday_p3_kWh: null

Sin embargo, me he dado cuenta que mi proveedor IBERDROLA distribución sólo actualiza los datos cada hora. por lo que he trasteado con la función coordinator.py y he cambiado la línea que indica que se recojan datos desde hace un año hasta hoy a las 0:0:0 menos un minuto y lo he cambiado por menos una hora. Desde el día 2 de Noviembre recibo datos cada día con un desfase de 2 días, con null en yesterday pero con datos en last registered day. He cambiado la tarjeta lovelace para registrar last registered day en lugar de yesterday y me funciona. También se actualizan los datos del mes actual y del mes anterior. Quizá sólo lleva una semana y todavía puede ser casualidad y no definitivo.

coordinator.py (129, 136)
  
# fetch last 365 days
        await self.hass.async_add_executor_job(
            self._datadis.update,
            datetime.today().replace(day=1, hour=0, minute=0, second=0, microsecond=0)
            - relativedelta(months=12),  # since: 1 year ago
            datetime.today().replace(hour=0, minute=0, second=0, microsecond=0)
            - timedelta(hours=1),  # to: yesterday midnight
        )

Por si alguno quiere probar. Es posible que para otros proveedores no funcione.

Saludos

**Comment by uvejota** [comment]
Pues es interesante, quizá conviene hacerlo parametrizable, según cada distribuidora.

Voy a echarle un ojo y lo subo si me da buen resultado.

Gracias!

**Comment by uvejota** [comment]
Se me había olvidado pero revisando la petición a Datadis (que se hace en mi librería python-edata), sólo se envía el mes y el año (de las fechas de inicio y fin). 

El día, hora, minuto, etc; se pierden; así que me temo que ha debido ser casualidad, mi gozo en un pozo... :(
