### ISSUE TITLE
Problema a la hora de instalar el addon

### ISSUE THREAD

**Issue by Tecytic** [uvejota/homeassistant-edata#205]
Realizo todo el proceso segun las instrucciones y no logro que se instale.
Tengo la cuenta en datadis en funcionamiento (abierta en otra pestaña). Le faltan datos, pero ese es otro tema con la distribuidora
Cuando le doy a instalar nueva integracion/edata me pide los datos de usuario, contraseña y cups.
Se los proporciono y siempre me da datos erroneos.
En usuario ya he probado con el DNI (es con lo que entro en datadis) o con la cuenta de correo que use. La contraseña es la usada en datadis. El cups lo he copiado del de datadis. Incluso he probado a poner el dni tambien en usuario autorizado. No hay manera

**Comment by uvejota** [comment]
¿Conseguiste solucionarlo?  ¿Qué mensaje te da?

Debería funcionar con DNI+letra, contraseña, y cups.

El nif autorizado hay que dejarlo vacío si eres el titular del cups que estás incluyendo.
