### ISSUE TITLE
Loading y no termina de cargar

### ISSUE THREAD

**Issue by sanvaras** [uvejota/homeassistant-edata#21]
Hola
He instalado la versión 0.1.8. Estoy dado de alta en datadis y veo mis datos perfectamente en la web.
Mi distribuidora es UFD y en la web de datadis puedo recuperar perfectamente mi suministro y acceder al consumo diario.
En el yaml he configurado mi usuario, contraseña de datadis y CUPS, que tanto en la web de datadis como en la de UFD es el mismo, es decir, no añade ningún número más. Estoy totalmente seguro que los datos que he puesto en el yaml son correctos.
Pero siempre indica loading y de ahí no pasa.
He probado a desinstalarlo y comprobar que no quedaba ningún dato dentro de la carpeta custom-components por si había algún problema de cache o similar pero sigue exactamente igual.
Lo he dejado varios días por si también podía ser ese el problema pero el resultado es el mismo
¿Sabe alguien que puede estar pasando?
Un saludo y gracias

Posdata:
Después de 5 o 6 días ya me ha aparecido el cups y el contract en la tarjeta en HA pero todavía tengo todos los valores en None. Lo dejaré unos días más a ver si termina de cargar.
Gracias y un saludo

**Comment by uvejota** [comment]
@sanvaras ¡Hola! Si ya te ha aparecido cups y contract acabará cargando. Habrá problemas con la API de Datadis (a mi últimamente me va fatal).

¡Un saludo!

**Comment by mabusdogma** [comment]
He notado lo mismo, y ha sido error mío: durante unas horas salía 'Loading', hasta que me di cuenta que no había cambiado el _xxxx del código no solo en Entities, sino en el texto que está en verde (cada item hay que cuidarlo.dos veces).
Al momento de cambiarlo, todo ha funcionado perfectamente.
