### ISSUE TITLE
Error en el formulario de facturacion

### ISSUE THREAD

**Issue by MrMarble** [uvejota/homeassistant-edata#210]
![imagen](https://github.com/uvejota/homeassistant-edata/assets/4268580/941d7ed4-5c15-4223-96de-9565e17f036b)

**Comment by jonathanathe** [comment]
Mismo problema aquí, pero con el campo del IVA. En mi factura, aparece que actualmente es del 5%, pero no me permite ingresar el número 5, y al intentar poner 5.0, lo borra automáticamente, dejando solo el 5.


![image](https://github.com/uvejota/homeassistant-edata/assets/34164094/14221060-6a86-4916-ba3a-b4b8c3d78db2)

**Comment by alexcamlo** [comment]
@jonathanathe lo pone en el texto de ayuda.
Para un IVA del 5% poner 1.05
