### ISSUE TITLE
Error requesting edata_##### data: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

### ISSUE THREAD

**Issue by Lugrider** [uvejota/homeassistant-edata#217]
Llevo tiempo que no me recoge datos aun habiendo datos actualizados en Datasis, y tras activar la depuración, me he encontrado el siguiente mensaje:

```
Este error se originó a partir de una integración personalizada.

Logger: custom_components.edata.coordinator
Source: helpers/update_coordinator.py:313
Integration: Integración edata (documentation, issues)
First occurred: 11:57:59 (1 occurrences)
Last logged: 11:57:59

Error requesting edata_##### data: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))
```

El error se repite múltiples veces, supongo que con cada intento de contactar con el servidor.

**Comment by uvejota** [comment]
Esto es raro, tengo que investigarlo...

**Comment by oscarsanchezdm** [comment]
Hola, yo tengo el mismo problema. La integración me funcionó hasta el 31 de diciembre. Los días 1 y 2 de febrero volví a tener datos (sin haber tocado nada), pero vuelvo a tener el mismo mensaje de error.
En Datadis puedo visualizar correctamente los datos.

Si necesitas nada para echarte una mano a debugar y encontrar dónde está el problema me lo dices!!

Utilizo Home Assistant 2024.1.6 y HACS 1.34.0.

Un saludo,
Òscar

**Comment by Theliel** [comment]
Exactamente el mismo problema desde el primer día, ni mucho ni poco, nada, el sistema por otro lado completamente actualizado.

Un saludo.

**Comment by uvejota** [comment]
A falta de hacer alguna pruebecilla, se ve que el servidor (datadis) dice enviar los datos comprimidos (gzip), pero los envía sin comprimir... 

Creo que puedo resolverlo, subiré algún fix pronto

**Comment by d4icon** [comment]
mismo problema por aqui

**Comment by uvejota** [comment]
He subido un "hotfix" a [2023.06.4](https://github.com/uvejota/homeassistant-edata/releases/tag/2023.06.4)

Mi idea es implementar una solución definitiva en #216, pero para ello antes necesito recopilar algunos logs de qué es lo que devuelve el servidor en estos casos, voy a probarlo localmente y veremos... en un par de días debería tener algún indicio.

Ahora mismo está marcado como pre-release porque no he podido hacer muchas pruebas (limitado a 1 petición cada 24h, y como el error no sucede siempre...). Cuando compruebe que esta pre-release no rompe nada, la marcaré como release. Es entonces cuando recomendaré actualizar.

**Comment by oscarsanchezdm** [comment]
Hola.

Acabo de actualizar edata y al arrancar Home Assistant sigo con el error:

>Logger: edata.connectors.datadis
>Source: /usr/local/lib/python3.12/site-packages/edata/connectors/datadis.py:223
>First occurred: 12:38:05 (4 occurrences)
>Last logged: 12:38:09
>Exception ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check')) at 'https://datadis.es/api-private/api/get-consumption-data'

Le iré echando un vistazo por lo que comentas de una petición cada 24h… ¡quizá es que soy un impaciente!

Un saludo y gracias por tu esfuerzo.
Òscar

**Comment by uvejota** [comment]
Perdón, no me he expresado bien. 

El error sigue sucediendo, pero ahora la integración lanza un warning y "continúa" intentándolo. Antes se detenía la ejecución del programa. Lo he hecho así porque en mi suministro sucede esporádicamente... pero parece ser que en tu caso es más frecuente.

Implementaré una solución definitiva cuando entienda por qué sucede ese error, estoy investigando.

Gracias por los avisos, os mantengo informados, no cierro la issue.

**Comment by uvejota** [comment]
He subido otra versión [2023.06.5](https://github.com/uvejota/homeassistant-edata/releases/tag/2023.06.5) en la que pruebo a eliminar gzip de la lista de encodings aceptables. Con suerte la api nos lo devolverá en texto plano sin comprimir... y el error debería dejar de suceder.

Aún no sé si funciona, lo he dejado en pre-release de momento... por si alguien quiere probar suerte :)

**Comment by oscarsanchezdm** [comment]
> He subido otra versión [2023.06.5](https://github.com/uvejota/homeassistant-edata/releases/tag/2023.06.5) en la que pruebo a eliminar gzip de la lista de encodings aceptables. Con suerte la api nos lo devolverá en texto plano sin comprimir... y el error debería dejar de suceder.
> 
> Aún no sé si funciona, lo he dejado en pre-release de momento... por si alguien quiere probar suerte :)

¡Ni dos minutos ha tardado en cargar los datos!
Ya funciona!!! Muchisimas gracias por tu implicación!

A ver qué dicen los otros ;-)

**Comment by d4icon** [comment]
Acabo de instalar esa versión y me ha salido otro error:

Logger: edata.connectors.datadis
Source: /usr/local/lib/python3.12/site-packages/edata/connectors/datadis.py:211
First occurred: 13:48:21 (1 occurrences)
Last logged: 13:48:21

500 {"status":500,"error":"INTERNAL_SERVER_ERROR","timestamp":"2024-02-28T13:48:21.386+0100"} at https://datadis.es/api-private/api/get-max-power?cups=ES0031104752501001AH0F&distributorCode=2&startDate=2024/02&endDate=2024/02&. Query temporary disabled. Future 500 code errors for this query will be silenced until restart


:(

**Comment by uvejota** [comment]
Los errores 500 son internos del servidor (datadis). Creo que ha podido ser casualidad, déjalo un tiempecillo a ver si se recupera :)

**Comment by d4icon** [comment]
> Los errores 500 son internos del servidor (datadis). Creo que ha podido ser casualidad, déjalo un tiempecillo a ver si se recupera :)


Nada, ahora me está apareciendo este error:

Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:599
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 19:03:56 (10 occurrences)
Last logged: 19:03:57

Client error on /store request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
Client error on /core/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
Client error on /supervisor/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
Client error on /os/info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]
Client error on /info request Cannot connect to host 172.30.32.2:80 ssl:default [Connect call failed ('172.30.32.2', 80)]

**Comment by uvejota** [comment]
Eso es un error ajeno a edata, concretamente del supervisor de hassio. Parece un error de conectividad local. No tiene nada que ver con esto, me temo.

**Comment by d4icon** [comment]
> Eso es un error ajeno a edata, concretamente del supervisor de hassio. Parece un error de conectividad local. No tiene nada que ver con esto, me temo.

Vaya... Entiendo

Pues es la primera vez que me sale en varios años...
Que raro.
Investigaré.

Se te ocurre algo?
Yo no he cambiado nada.

**Comment by d4icon** [comment]
Ainss...
Perdona me equivoqué al copiarte el mensaje.

Luego te lo paso bien
