### ISSUE TITLE
En la web datadis no aparecen mis suministros 

### ISSUE THREAD

**Issue by frikiman8** [uvejota/homeassistant-edata#218]
No se obtienen datos y supongo que hasta que en la web de datadis no aparezca mi suministro en el listado de suministros, no funciona nada.

**Comment by uvejota** [comment]
Afirmativo, hasta que no salga en datadis, nothing to do :)

En algunos casos además, en el mes en que se realiza un cambio de contrato tampoco devuelve datos la API.

Paciencia
