### ISSUE TITLE
The provided scups parameter is not correct: XXXX

### ISSUE THREAD

**Issue by lufetico** [uvejota/homeassistant-edata#219]
Since I installed the integration, 1 week ago, I have not been able to obtain historical data on my electricity consumption. Only data from the current month. I guess it is due to the error I see in the HA logs:

![image](https://github.com/uvejota/homeassistant-edata/assets/38246115/1b9a8dd8-45c6-49d0-9358-6aec67c58bda)

```
This error originated from a custom integration.

Logger: custom_components.edata.websockets
Source: custom_components/edata/websockets.py:56
Integration: edata integration (documentation, issues)
First occurred: 15:09:37 (2 occurrences)
Last logged: 15:11:26

The provided scups parameter is not correct: XXNK
```

The cards never receive data:

![image](https://github.com/uvejota/homeassistant-edata/assets/38246115/bc81a4ce-c8ee-44b6-ab6d-c4fbbf161c83)

My Home Assistant Green installation:

- HA Core: 2024.2.1
- Supervisor: 2024.01.1
- Operating System: 11.5
- Frontend:  20240207.1

**Comment by uvejota** [comment]
Replace your scups ("xxxx") to lowcase in cards config.

This will be fixed anyways on future releases (#216).

**Comment by lufetico** [comment]
Thanks!

Most of the cards are already working for me. There is only one that is failing but I have to analyze what is going on. 

![image](https://github.com/uvejota/homeassistant-edata/assets/38246115/9b6f1a44-cdc6-460f-b0f2-9cbcc3244613)

**Comment by uvejota** [comment]
Yesterday data is frequently unavailable due to the absence of data at Datadis.
