### ISSUE TITLE
No puedo añadir la integración

### ISSUE THREAD

**Issue by JordiSFR** [uvejota/homeassistant-edata#221]
He seguido todos los pasos de la instalación sin problemas (reiniciando en este punto) hasta llegar al punto 4, dónde dice: Buscar "edata" en Configuración > Dispositivos y servicios > Añadir integración. Ahí me aparece "e-data", clico, y me aparece el error: "El flujo de datos de configuración no se ha podido cargar: Failed dependencies recorder". ¿Alguien podría decirme por qué no funciona?

**Comment by uvejota** [comment]
Necesitas tener el componente 'recorder' de home assistant activo. Esto es obligatorio, es necesario para guardar los datos en el panel de energía.

Viene activo por defecto, salvo que hayas modificado el configuration.yaml para no incluirlo a propósito.
