### ISSUE TITLE
Unique ID

### ISSUE THREAD

**Issue by Linx-ESP** [uvejota/homeassistant-edata#223]
https://www.home-assistant.io/faq/unique_id
Permitiria tener varios CUPS que terminaran igual sin problema, y poder renombrar entidades o atributos, útil para renombrar de p1/p2/p3 a valle/llano/pico en tarifas con discriminación horaria.

**Comment by uvejota** [comment]
Esto estará en la próxima release en la que estoy trabajando (ver #216). Sin ETA aún, voy trabajando poquito a poquito :)

Además se van a separar los atributos en varios sensores, siguiendo la línea de buenas prácticas que sugiere Home Assistant.
