### ISSUE TITLE
Ver mas información en el apartado energia

### ISSUE THREAD

**Issue by cvc90** [uvejota/homeassistant-edata#227]
Buenas,

la integración edata, solo me carga la información del ultimo año en el apartado energía (Hasta el día 1 de Marzo de 2023), existe alguna manera de cargar mas tiempo?

**Comment by uvejota** [comment]
De momento, está protegido para rescatar sólo el último año de consumos en el arranque. Quizá me plantee hacerlo configurable.

**Comment by cvc90** [comment]
Gracias, por la respuesta.

**Comment by uvejota** [comment]
FYI: esto está entre una de mis prioridades (ver #247)

**Comment by uvejota** [comment]
En la versión 2024.07.5 estará disponible un botón asociado al dispositivo edata para descargar el histórico disponible en datadis (que está limitado a 2 años por su API).
