### ISSUE TITLE
Not creating devices nor instances

### ISSUE THREAD

**Issue by oriolpino** [uvejota/homeassistant-edata#228]
The configuration is completed and the global entity with the 6 last CUPS numbers is created but inside entities and devices are not created and no data is recieved

**Comment by josemrs** [comment]
Me pasa igual. Estaba configurado y funcionando pero ha dejado de reportar en el panel de energía y puedo ver los siguiente errores en los logs.

`Unknown error while retrieving token, got <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.24.0</center> </body> </html>`
`Setup of sensor platform edata is taking over 10 seconds.`
`Some stats are missing for xxxx`
`Setup of platform edata is taking longer than 60 seconds. Startup will proceed without waiting any longer.`


La web de datadis.es ha estado caía unos días con un error de servidor y creo que la API podría seguir caida pero no puedo comprobarlo ahora mismo.

Coincide que cambié de comercializadora hace una semana, no de distribuidora, en datadis.es puedo ver el consumo hasta el día de ayer bien por lo que no creo que sea esto.

**Comment by songochain** [comment]
Buenas, en mi caso es la primera vez que uso la integración, no crea entidades y en logs sale "Setup of sensor platform edata is taking over 10 seconds."

**Comment by oriolpino** [comment]
Para mi también es la primera vez que uso la integración y no me aparece ningún error

**Comment by josemrs** [comment]
> Para mi también es la primera vez que uso la integración y no me aparece ningún error

Sin error pero tampoco funciona? Te salen los sensores y entidades?

**Comment by oriolpino** [comment]
Exacto tampoco funciona. Adjunto captura de pantalla.

![Uploading Captura de pantalla 2024-04-09 a las 20.21.37.png…]()

**Comment by oriolpino** [comment]
> > Para mi también es la primera vez que uso la integración y no me aparece ningún error
> 
> Sin error pero tampoco funciona? Te salen los sensores y entidades?

Exacto, sin error pero
<img width="678" alt="Captura de pantalla 2024-04-09 a las 20 21 37" src="https://github.com/uvejota/homeassistant-edata/assets/72791988/acc0171d-8c59-4d77-a3f6-6d8e42419a56">
 tampoco funciona. Adjunto captura de pantalla.

**Comment by fjluquerodriguez** [comment]
igual aquí:  "Setup of sensor platform edata is taking over 10 seconds." y no sale ningun dispositivo ni nada

**Comment by SamuelsonLB** [comment]
> > > Para mi también es la primera vez que uso la integración y no me aparece ningún error
> > 
> > 
> > Sin error pero tampoco funciona? Te salen los sensores y entidades?
> 
> Exacto, sin error pero <img alt="Captura de pantalla 2024-04-09 a las 20 21 37" width="678" src="https://private-user-images.githubusercontent.com/72791988/320961979-acc0171d-8c59-4d77-a3f6-6d8e42419a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDY5MjAsIm5iZiI6MTcyMDAwNjYyMCwicGF0aCI6Ii83Mjc5MTk4OC8zMjA5NjE5NzktYWNjMDE3MWQtOGM1OS00ZDc3LWEzZjYtNmQ4ZTQyNDE5YTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDExMzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWQ3NTA0OGE0NjYxZTJiNzQ2MGQ3Y2I2YTNjM2Y3MGRkZjcxNmY2NDhhYzI4OTEwYmZjOTZlNzQ5ZWI3MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z9TsSbZVDZq7zHbfAnt96X99GCh5K8K5wT79vgiuvJE"> tampoco funciona. Adjunto captura de pantalla.

A mí me pasa lo mismo. ¿Alguna solución?

**Comment by josemrs** [comment]
No, habrá que esperar a que el mantenedor lo pueda arreglar, parece que no tiene mucho tiempo para mantener la integracion

**Comment by asiersan** [comment]
Yo estoy igual. Funcionaba de maravilla y ahora nada.

**Comment by oliveraf** [comment]
Aqui la solucion: https://github.com/uvejota/homeassistant-edata/issues/243#issuecomment-2276560935
