### ISSUE TITLE
Precio y consumo integrados

### ISSUE THREAD

**Issue by mabusdogma** [uvejota/homeassistant-edata#23]
Hola! Nos encanta el trabajo qué estás haciendo, ahora podemos ver exactamente cuánto hemos gastado por día y por mes. Una mejora que se me ocurre es incluir el precio en la gráfica del consumo diario y mensual, como si fuera una línea más, no sé si es posible.
Así se tendría la información de dos gráficas en una :)
Marco una idea, con una línea verde, en donde se podría poner el precio del mes (o del día), en lugar de la hora de registro.

Si tuviera el dato del precio, creo que me ahorraría los quesitos :P

Muchas gracias por tu esfuerzo!
![14541](https://user-images.githubusercontent.com/19146242/133890404-3ec2b300-e07a-4f81-a995-ada73631fd69.png)

**Comment by mabusdogma** [comment]
![Screenshot_20210919-084016510~2](https://user-images.githubusercontent.com/19146242/133918169-60c88dfb-5a81-4bd1-b45e-17a3f6e46287.jpg)

Otra pregunta, se podría ver el consumo en euros que hemos hecho el día anterior? (Ideal para culpabilizarnos después de un día de derroche, jeje)

**Comment by uvejota** [comment]
Me las anoto como futuras mejoras, todo es posible :-)

¡Gracias por las sugerencias!

**Comment by SirMartin** [comment]
Hola, aunque quizá no es el mejor sitio, pero viendo esta pregunta y el tema del precio, entiendo que el precio lo tomas de Datadis no? A mi no me aparece ningún precio. ¿Es algo que habéis configurado vosotros mismos de alguna manera, o se supone que debería mi eléctrica haberlo registrado?

Un saludo.

**Comment by mabusdogma** [comment]
No, el precio es otra integración llamada PVPC

**Comment by mabusdogma** [comment]
![Screenshot_20210922-120233938 (1)](https://user-images.githubusercontent.com/19146242/134324223-c1e99c11-08db-4ecd-b01b-ccd7b25d7d9d.jpg)

**Comment by SirMartin** [comment]
Muchas gracias, ahora lo probare.

**Comment by mabusdogma** [comment]
![Screenshot_20210923-095325006 (1)](https://user-images.githubusercontent.com/19146242/134472187-c906ec87-0f3f-474e-940e-fdc3c339e303.jpg)
Yo la tengo en la sección de energía, soy un poco perezoso pero sé que podríamos calcular CO2 y gasto en euros, día por dia, teniendo el precio, el CO2, el porcentaje de energías provenientes de combustibles fosiles y los kW consumidos.

**Comment by SirMartin** [comment]
Realmente el tema de CO2 si consiguieramos que el panel de energía pillara los datos de este plugin, tendrías ese tema resuelto alli, Y alguna opción más.

**Comment by uvejota** [comment]
Voy a cerrar este hilo ya que el PVPC ahora mismo no anda, y creo que lo que se pide en el OP depende más de funcionalidades de la tarjeta que de la integración. En cualquier caso estoy trabajando en inyectar precios personalizados a las estadísticas de HA (y debería ser seleccionable también en el panel de energía).
