### ISSUE TITLE
Acceso y manejo de datos LTS (statistics)

### ISSUE THREAD

**Issue by jmrplens** [uvejota/homeassistant-edata#230]
Hola, 

Estoy intentando sacar los históricos de consumo por hora y los precios por hora para representar en columnas el consumo diario y el coste diario. No solo ayer sino todos.

No tengo experiencia manejando los datos estadísticos como los que tiene la integración. En la tarjeta para visualizar estadísticas lo veo perfectamente pero al intentar leerlo mediante SQL no lo consigo. No sé si se puede hacer mediante template o script.

¿Alguna idea?

Sería interesante que estuviera la información en la documentación, el cómo acceder a los datos como si fuese otro sensor más. Tengo entendido que estás trabajando en la nueva versión y parece que ya estarán más accesibles los datos no? O esta parte continuará igual?

Ejemplo (me faltaría poder sacar los datos para procesarlos y obtener el coste diario):

![IMG_2955](https://github.com/uvejota/homeassistant-edata/assets/28966312/383ea0b2-5623-42d3-abe4-a4f33096fc98)

Gracias!

**Comment by webtense** [comment]
buenos dias, 

Podrías compartir lo que has conseguido hasta ahora, me interesa mucho. 

gracias

**Comment by uvejota** [comment]
He añadido info sobre los endpoints de websockets que se exponen en la última versión de edata, en https://github.com/uvejota/homeassistant-edata?tab=readme-ov-file#acceso-a-datos-descargados

Puedes ver las definiciones con más detalle en el fichero websockets.py del repositorio.

Desconozco cómo se consumen los websockets de home assistant fuera de la integración, supongo que habrá que usar una api key...

Cierro el hilo por mantener un poquito el orden. Si logras conseguirlo te animo a que lo compartas en el foro de discusión y le hago algo de publi en el README.
