### ISSUE TITLE
Datos no actualizan al cambiar de compañía

### ISSUE THREAD

**Issue by salgado-sergio** [uvejota/homeassistant-edata#232]
Hice un cambio de compañía el 11 de abril (de mercado libre a PVPC) y desde entonces no se actualizan los datos. En datadis en cambio sí puedo descargar los datos nuevos. ¿Alguna idea para solucionar el problema?

Gracias

**Comment by uvejota** [comment]
Esto me temo que no tiene solución por nuestra parte. Por algún motivo la API que usamos de Datadis no devuelve datos la mensualidad en que se cambia el contrato, independientemente de lo que muestre su web (que asumo que utilizan otro mecanismo para su obtención).

El 17 abr 2024, a las 11:17, sergiosb89 ***@***.***> escribió:

﻿

Hice un cambio de compañía el 11 de abril (de mercado libre a PVPC) y desde entonces no se actualizan los datos. En datadis en cambio sí puedo descargar los datos nuevos. ¿Alguna idea para solucionar el problema?

Gracias

**Comment by salgado-sergio** [comment]
pero me devolverá la siguiente mensualidad?

**Comment by uvejota** [comment]
Si, al menos en mi caso siempre ha sido así.

El 17 abr 2024, a las 12:26, sergiosb89 ***@***.***> escribió:

﻿

pero me devolverá la siguiente mensualidad?

**Comment by salgado-sergio** [comment]
ok, gracias!

**Comment by salgado-sergio** [comment]
pues hoy se han actualizado los datos. eso sí, no me calcula el consumo en euros. Me devuelve esto: month_€: None
