### ISSUE TITLE
Problema datos autoconsumo

### ISSUE THREAD

**Issue by davidrielves** [uvejota/homeassistant-edata#234]
Buenos días,
Estoy viendo que en el API Datadis si se puede recoger los datos de autoconsumo, pero en edata no vienen....
Estoy configurando algo yo mal en homeassistant? o simplemente no se pueden ver estos datos?

Gracias de antemano

![image](https://github.com/uvejota/homeassistant-edata/assets/92336901/f160bb17-9f3d-4f76-b1c2-59411327a6a0)
![image](https://github.com/uvejota/homeassistant-edata/assets/92336901/9a843e5c-948c-47eb-8b54-9991918d8e50)

**Comment by Korvenwin** [comment]
@uvejota ha comentado en otras ocasiones que está trabajando en una nueva versión muy mejorada que incluiría el autoconsumo, pero que lo está haciendo tranquilamente cuando puede. 

Sólo nos queda animarle en su trabajo y esperar el resultado.

Aquí tienes el estado: 

https://github.com/uvejota/homeassistant-edata/pull/216

**Comment by davidrielves** [comment]
> @uvejota ha comentado en otras ocasiones que está trabajando en una nueva versión muy mejorada que incluiría el autoconsumo, pero que lo está haciendo tranquilamente cuando puede.
> 
> Sólo nos queda animarle en su trabajo y esperar el resultado.
> 
> Aquí tienes el estado:
> 
> #216

Gracias por la info
@uvejota Gracias por el esfuerzo!

**Comment by cho0p** [comment]
+1      It would be awesome if the integration could also show the selfConsumption/energy exported to grid.

**Comment by juanxu101** [comment]
+1 Antes de nada muchisimas gracias por la integracion, absolutamente fantastica y un currazo,  @uvejota he visto que que el tema de autoconsumo lo estas preparando en una major update #216 , aunque parece que desde marzo no hay ninguna modificacion. Estoy mirando una alternativa para usar mi cargador de coche  electrico para medir, pero tienen un error muy grande.... Sabes si se tardara mucho aunque sea en coger los datos de autoconsumo?

Mil gracias en cualquier caso por todo!

**Comment by uvejota** [comment]
Hola, gracias a vosotros por usarla, y la paciencia ante la falta de updates!

Ahora viene el veranito... y espero darle un achuchón a esto. Así que me gustaría tenerlo durante el mes de julio, pero no puedo prometer nada, depende de cómo se me tuerza el trabajo :)

**Comment by Korvenwin** [comment]
@uvejota ánimo y calma con las actualizaciones. Yo llevo usándola ya unos meses y la base es muy muy sólida. Buen trabajo.

**Comment by juanxu101** [comment]
> Hola, gracias a vosotros por usarla, y la paciencia ante la falta de updates!
> 
> Ahora viene el veranito... y espero darle un achuchón a esto. Así que me gustaría tenerlo durante el mes de julio, pero no puedo prometer nada, depende de cómo se me tuerza el trabajo :)

Mil gracias! Concuerdo totalmente, la base es muy buena. Te debemos muchos una cerveza.... y cuando este esto otra ajajaja

**Comment by juanxu101** [comment]
> > Hola, gracias a vosotros por usarla, y la paciencia ante la falta de updates!
> > Ahora viene el veranito... y espero darle un achuchón a esto. Así que me gustaría tenerlo durante el mes de julio, pero no puedo prometer nada, depende de cómo se me tuerza el trabajo :)
> 
> Mil gracias! Concuerdo totalmente, la base es muy buena. Te debemos muchos una cerveza.... y cuando este esto otra ajajaja

@uvejota he visto que le has dado un. Buen empujón! Avisarás por aquí cuando esté para instalar??
