### ISSUE TITLE
Problemas en el arranque desde 2024.5: Detected blocking call to import_module inside the event loop by custom integration 'edata'

### ISSUE THREAD

**Issue by fherreror** [uvejota/homeassistant-edata#235]
Desde que actualicé a 2024.5 he empezado a tener algunos errores en los logs vinculados a esta integración. Salen nada más reiniciar:

`Registrador: homeassistant.util.loop
Fuente: util/loop.py:99
Ocurrió por primera vez: 22:25:36 (1 ocurrencias)
Último inicio de sesión: 22:25:36

Detected blocking call to import_module inside the event loop by custom integration 'edata' at custom_components/edata/coordinator.py, line 170: self._datadis.process_data() (offender: /usr/local/lib/python3.12/site-packages/dateparser/languages/loader.py, line 215: import_module("dateparser.data.date_translation_data." + lang),), please create a bug report at https://github.com/uvejota/homeassistant-edata/issues`

La integración tarda mucho en arrancar y luego me sale este otro error, que parece que está ocasionado porque una tarea de esta integración se queda pendiente:

`Registrador: homeassistant.core
Fuente: core.py:533
Ocurrió por primera vez: 22:26:04 (1 ocurrencias)
Último inicio de sesión: 22:26:04

Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: adguard.sensor, logger, mqtt.sensor, alexa_media.switch, rpi_power, application_credentials, home_connect, map, unifi.image, api, samsungtv_smart.media_player, system_log, sun, group.light, esphome.binary_sensor, roborock.sensor, webostv.notify, min_max, wake_on_lan.switch, switch, mqtt.light, hass_agent, wake_on_lan, ezviz.button, camera, roborock.camera, systemmonitor.binary_sensor, config, usb, mobile_app, systemmonitor, homekit_controller.select, energy, todo, esphome.update, esphome.switch, template, input_button, device_automation, bluetooth, netatmo.binary_sensor, alexa_media.media_player, shelly.cover, unifi.switch, analytics, alarmo.alarm_control_panel, cloud, diagnostics, unifi.update, siren, bluetooth_adapters, ideenergy, timer, group.binary_sensor, alexa_media.alarm_control_panel, mobile_app.notify, shelly, shelly.event, input_boolean, radio_browser, cover, mqtt.binary_sensor, esphome.button, stt, device_tracker, ssdp, history, alexa_media.binary_sensor, proximity.sensor, my, google_translate.tts, smtp.notify, multiscrape, sensor, holiday.calendar, roborock.select, utility_meter, alexa_media, wake_word, select, hassio.sensor, mqtt.button, aemet, ezviz.siren, event, ezviz.image, zeroconf, shelly.binary_sensor, shelly.update, http, melcloud.climate, onboarding, alarm_control_panel, rpi_gpio, ezviz.binary_sensor, fan, local_calendar, homekit_controller, sun.sensor, dhcp, logbook, tag, home_connect.binary_sensor, netatmo.light, automation, ezviz.update, mqtt.update, systemmonitor.sensor, ezviz.camera, hass_agent.media_player, pvpc_hourly_pricing.sensor, input_number, time, alexa_media.notify, unifi.device_tracker, unifi.sensor, backup, input_text, lock, roborock.binary_sensor, search, shelly.sensor, template.switch, multiscrape.sensor, person, stream, assist_pipeline, roborock, netatmo.sensor, alarmo, pvpc_hourly_pricing, alexa_media.light, remote, tts, hassio.binary_sensor, conversation, shelly.climate, input_datetime, mqtt, climate, system_health, roborock.button, file_upload, edata, ideenergy.sensor, hacs, ezviz.sensor, group.cover, file.notify, melcloud, template.sensor, shelly.light, ezviz.select, home_connect.switch, alexa, update, local_calendar.calendar, button, binary_sensor, webostv, nut, trace, water_heater, roborock.number, persistent_notification, image_upload, raspberry_pi, default_config, light, schedule, network, mobile_app.binary_sensor, image, mobile_app.sensor, edata.sensor, netatmo.fan, frontend, intent, hass_agent.notify, alexa_media.sensor, govee_lan, blueprint, time_date.sensor, netatmo.cover, ezviz.switch, hassio, unifi.button, influxdb, local_todo.todo, unifi, nut.sensor, homeassistant, homeassistant.scene, nodered, zone, auth, ezviz, media_source, proximity, mqtt.switch, homekit_controller.sensor, wyoming, utility_meter.sensor, melcloud.water_heater, min_max.sensor, scene, netatmo.climate, notify, hardware, esphome, input_select, homekit_controller.button, melcloud.sensor, mqtt.number, webhook, homeassistant_alerts, local_todo, netatmo, rest, panel_custom, netatmo.select, shelly.button, vacuum, roborock.vacuum, roborock.switch, roborock.time, esphome.sensor, ffmpeg, lovelace, counter, holiday, home_connect.light, recorder, group, rest.sensor, repairs, netatmo.camera, govee_lan.light, webostv.media_player, mobile_app.device_tracker, template.binary_sensor, ezviz.number, shelly.switch, ezviz.alarm_control_panel, mqtt.lock, hacs.sensor, hassio.update, ezviz.light, adguard.switch, rpi_gpio.switch, samsungtv_smart, rpi_power.binary_sensor, media_player, homekit_controller.climate, websocket_api, cloud.tts, mqtt.select, adguard, energy.sensor, home_connect.sensor, number, netatmo.switch, calendar, script, samsungtv_smart.remote The system is waiting for tasks: {<Task pending name='Task-2160' coro=<async_setup_entry.<locals>.async_first_refresh() running at /config/custom_components/edata/sensor.py:181> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.12/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> cb=[set.remove()]>}`

**Comment by vanmorden** [comment]
A mi también me ocurre.

**Comment by Eguar-rc** [comment]
Similar error:
Registrador: homeassistant.util.loop
Fuente: util/loop.py:84
Ocurrió por primera vez: 14:48:55 (1 ocurrencias)
Último inicio de sesión: 14:48:55

Detected blocking call to open inside the event loop by custom integration 'edata' at custom_components/edata/coordinator.py, line 149: with open( (offender: /config/custom_components/edata/coordinator.py, line 149: with open(), please create a bug report at https://github.com/uvejota/homeassistant-edata/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval await self._async_refresh(log_failures=True, scheduled=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/edata/coordinator.py", line 149, in _async_update_data with open(

**Comment by imc67** [comment]
same issue here, I can't use it or does anyone has a workaround? Is the project still active?
