### ISSUE TITLE
Veo los gráficos de energía en las tarjetas de apexcards pero no en la pestaña de Energia

### ISSUE THREAD

**Issue by martibc16** [uvejota/homeassistant-edata#236]
Hola, despues de configurar la integración me encuentro con que tengo el sensor:
![imagen](https://github.com/uvejota/homeassistant-edata/assets/44815501/a685a145-97e2-42de-8ad7-508902be4dc0)
He podido crear un gráfico con mi consumo:
![imagen](https://github.com/uvejota/homeassistant-edata/assets/44815501/56ce45b3-3890-4fc3-81a7-01f930f229cb)
Pero en el apartado de energía no me aparece nada a parte del consumo diario en euros.
![imagen](https://github.com/uvejota/homeassistant-edata/assets/44815501/389bd764-da8c-41cc-868f-9c93bee968a2)
Y aparentemente está bien configurado:
![imagen](https://github.com/uvejota/homeassistant-edata/assets/44815501/f307b7ef-2efe-42c8-83ca-e245f904e19f)
Tampoco he visto mensajes de error en el log.

Que estoy haciendo mal?

**Comment by martibc16** [comment]
Hola @uvejota. Supongo que cerraste el hilo porque sacaste la nueva versión con muchas mejoras.

Después de instalar la versión pre-release mencionada [aquí ](https://github.com/uvejota/homeassistant-edata/issues/252#issuecomment-2310546986) las tarjetas de consumo funcionan correctamente y veo datos. Pero el panel de energía sigue sin funcionar. Con esta situación en que me debería fijar para encontrar el error?

**Comment by uvejota** [comment]
Um...

En la primera foto estás enseñándome el sensor EB0F, y en el segundo el 01EB.

Mira a ver si tienes seleccionada la estadística correcta en el panel, no sea que de una versión previa errónea se te creara una statistic_id incorrecta.

**Comment by citisend-app-libraries** [comment]
> Um...
> 
> En la primera foto estás enseñándome el sensor EB0F, y en el segundo el 01EB.
> 
> Mira a ver si tienes seleccionada la estadística correcta en el panel, no sea que de una versión previa errónea se te creara una statistic_id incorrecta.

Gracias @uvejota, toda la razón.

No se por que aparecen todas esas entidades en el desplegable. Muchas gracias igualmente!

**Comment by uvejota** [comment]
> > Um...
> > En la primera foto estás enseñándome el sensor EB0F, y en el segundo el 01EB.
> > Mira a ver si tienes seleccionada la estadística correcta en el panel, no sea que de una versión previa errónea se te creara una statistic_id incorrecta.
> 
> Gracias @uvejota, toda la razón.
> 
> No se por que aparecen todas esas entidades en el desplegable. Muchas gracias igualmente!

Será de alguna versión de edata previa que tenía algún bug. Las primeras versiones eran bastante discutibles ;)
