### ISSUE TITLE
Custom element doesn't exist: edata-card

### ISSUE THREAD

**Issue by tonicb78** [uvejota/homeassistant-edata#237]
Hola, muchas gracias seguir trabajando con la integración! Estoy probando las alphas, puede que ya lo sepas, la tarjeta edata me indica que no existe:

Logger: frontend.js.latest.202407100
Source: components/system_log/__init__.py:333
First occurred: 20:07:53 (1 occurrences)
Last logged: 20:07:53

Uncaught error from Chrome 126.0.0.0 on Windows 10 SyntaxError: Failed to execute 'define' on 'CustomElementRegistry': "Edata-card-editor" is not a valid custom element name /edata/edata-card.js:392:16

Es con la versión 2024.07.0-alpha.8 y HA 2024.7.2.

Saludos!

**Comment by uvejota** [comment]
Hola. Gracias a ti por testarla.

¿Puedes comprobar si aparece en una ventana de incógnito? (Para ver si puede ser la caché del navegador)

Gracias!

**Comment by tonicb78** [comment]
Hola, de nada! probado en modo incógnito y me indica lo mismo, que no encuentra la card edata. Saludos!

**Comment by uvejota** [comment]
Voy un poco a ciegas, porque no soy capaz de replicarlo. 

2024.07.0-alpha.9 tiene un cambio para intentar corregir esto. Necesitarás borrar caché para que se reflejen los cambios.

A ver si hay suerte ;)

**Comment by tonicb78** [comment]
Ahora si! Lo he hecho con el móvil, por lo que en un navegador de PC no aparece será un tema de caché. Tiene muy buena pinta esta actualización, gracias!

**Comment by tonicb78** [comment]
Solved
