### ISSUE TITLE
Tarjeta eData Alpha 8

### ISSUE THREAD

**Issue by PutoPunko** [uvejota/homeassistant-edata#238]
Hola,

Primero de todo quiero darte las gracias por esta gran integración. Al intentar usar la nueva tarjeta (version edata Alpha 8) con agregado anual no se grafica correctamente (valores incorrectos y eje x incorrecto):

![image](https://github.com/user-attachments/assets/30cba7d1-70bb-4d72-90bd-6c49fcf5d771)

Añado configuración yaml de la tarjeta (retirando mis digitos de cups)

title: Consumo Anual
type: custom:edata-card
chart: consumptions
entity: sensor.edata_xxxx
aggr: year
records: 3
colors:
  - '#e54304'
  - '#ff9e22'
  - '#9CCC65'

Funciona correctamente con agregado diario y mensual.

**Comment by uvejota** [comment]
Buen ojo. La agregación week y year no están correctamente implementados, y muestran el mensual.

Lo corrijo, gracias.

**Comment by uvejota** [comment]
Creo que ya (2024.07.0-alpha.9).

Hay algún problema con los ticks del eje x en la agrupación anual (no sale el del año en curso), pero de momento es secundario :)

**Comment by PutoPunko** [comment]
Si, veo que funciona con fallo menor en el eje X. Muchas gracias!

![image](https://github.com/user-attachments/assets/4919db54-43e3-4230-b500-e9df5a531f1c)

**Comment by Truman78es** [comment]
¿Podeis facilitar el codigo yaml exacto para poderlo incluir en nuestros HA?
