### ISSUE TITLE
Titulos en la nueva tarjeta edata

### ISSUE THREAD

**Issue by skgsergio** [uvejota/homeassistant-edata#240]
Quizás para hacer los estilos consistentes con el resto de elementos se podría hacer que el título sea similar al resto de tarjetas.

Ejemplo aqui editando rápidamente los estilos de mi tarjeta de Daily:
![image](https://github.com/user-attachments/assets/58826433-a28c-4a72-99b9-068204399400)

**Comment by uvejota** [comment]
Creo que tienes razón. 

Si lo tienes arreglado, puedes hacer un pull request :) 

En caso contrario, lo haré yo.

¡Gracias!

**Comment by skgsergio** [comment]
No, la prueba la hice cambiando los estilos en el navegador. Le he echado un ojo al .js y mis conocimientos de front son muy limitados como para entender de donde leches salen los estilos y donde ponerlos o si puedo usar alguno existente en home assistant xD
