### ISSUE TITLE
No hay datos en la tarjeta "Ayer"

### ISSUE THREAD

**Issue by diegofrances** [uvejota/homeassistant-edata#241]
Primero que nada me gustaría agradecer el trabajo realizado.

Soy capaz de extraer todos los datos pero la tarjeta "Ayer" siempre está vacía.

Si compruebo el valor del sensor "sensor.edata_xxxx" soy capaz de ver todos los datos de manera correcta comparando con los datos de Datadis, pero los referentes a "yesterday" siempre devuelven "null".

cups: XXXXXXXXXXXX
yesterday_kWh: null
yesterday_hours: null
yesterday_p1_kWh: null
yesterday_p2_kWh: null
yesterday_p3_kWh: null
last_registered_date: 2024-07-21T23:00:00
last_registered_day_kWh: 9.5
last_registered_day_hours: 21
last_registered_day_p1_kWh: 0
last_registered_day_p2_kWh: 0
last_registered_day_p3_kWh: 9.5

Al principio pensaba si podía ser porque el último día que devuelve valores la API es dos días antes; es decir, cuando se realiza la petición GET, la API devuelve valores de dos días anteriores y no el día anterior, ya que el campo "last_registered_date" devuelve un valor de dos días antes de la petición ((2024-07-21T23:00:00" (Lo veo en el sensor)); en cambio si voy a la web de Datadis, soy capaz de ver los detalles de ayer.

Me picaba la curiosidad y he realizado la petición a la API con RESTer "https://datadis.es/api-private/api/get-consumption-data". Me muestra todos los datos de ayer por horas, así que ya no sé si el error está en la API que no devuelve los valores solicitados (No he conseguido sacar la petición correcta) o que cuando después de hacer la petición, cuando realizas la suma de todas las horas para definir los valores de los atributos/parámetros "yesterday_XXXX" falla algo.

De nuevo, gracias por todo y quedo a la espera de tu respuesta.

**Comment by Truman78es** [comment]
Me pasa exactamente lo mismo

**Comment by Jobs33** [comment]
Hola,
A mí también me pasa que no me muestra los datos de los dos días anteriores.
Tengo la información del histórico del mes, pero hace días que no se me actualizan los datos. He ido a la pagina de datadis y veo que la información está actualizada.
No sé cómo se puede arreglar este problema o si como bien dices es un error de la API.

**Comment by jjvelar** [comment]
A mi también me pasa lo mismo.

**Comment by fjterrada69** [comment]
Mismo problema, no aparecen los valores de ayer

**Comment by ferboiar** [comment]
Hola, perdón por reabrir esto. Como no veo respuesta clara no tengo claro si está o no solucionado. A mi me pasa lo mismo, tengo valores en todos los sensores menos en consumo_ayer:

![image](https://github.com/user-attachments/assets/c766162f-c1d1-483e-8ea9-9a6f0964a853)


No se si alguien ha conseguido solucionarlo o se trata de un problema con datadis...

**Comment by diegofrances** [comment]
Revisa este hilo:

https://github.com/uvejota/homeassistant-edata/issues/247

**Comment by ferboiar** [comment]
> Revisa este hilo:
> 
> #247

gracias por la respuesta, acabo de leerlo completo e imagino que soy uno de esos a los que le pasa:

`Muchos me escribís preguntando por los datos de ayer. Veréis, no es tan sencillo. La API de Datadis sólo te permite hacer una misma petición cada 24 horas, de modo que si a vuestra integración le toca a las 17h (por ejemplo), y tu distribuidora sube tus datos de ayer a las 19h, nunca dispondrás de los datos de ayer. Esto puede mitigarse con un pequeño algoritmo que vaya retrasando la petición una hora cada día hasta encontrar la franja en la que encuentres los datos, de modo que al final "sincronices" la hora de tu descarga con una hora próxima a la de la adición de los datos, o indicando una ventana para la actualización (y que cada uno investigue cuál le viene bien a su CUPS).`
