### ISSUE TITLE
Problemas en las "stacked cards" con la última versión 

### ISSUE THREAD

**Issue by Pharizna** [uvejota/homeassistant-edata#242]
Hola

Desde la última actualización del apexcharts-card parece que ha dejado de funcionar la opción de "stacked card" como se puede ver en la figura del consumo mensual :(

![image](https://github.com/user-attachments/assets/894abb57-791c-4267-b6ff-fb447e24fec7)

Antes se veía perfectamente

![image](https://github.com/user-attachments/assets/21e0a56f-3146-4bc8-b25e-92df64bcad3c)

**Comment by uvejota** [comment]
Para corregirlo tienes que añadir las curvas Punta, Llano, y Valle, al mismo grupo.

Anida el siguiente contenido a estas curvas, y se solucionará.

```yaml
stack_group: "1"
```

**Comment by Pharizna** [comment]
Perfecto! Funciona!Muchas gracias por la ayudaEl 8 ago 2024, a las 13:44, VMG ***@***.***> escribió:﻿
Para corregirlo tienes que añadir las curvas Punta, Llano, y Valle, al mismo grupo.
Anida el siguiente contenido a estas curvas, y se solucionará.
stack_group: "1"
