### ISSUE TITLE
La integración no funciona con HA 2024.8

### ISSUE THREAD

**Issue by diegofrances** [uvejota/homeassistant-edata#243]
Acabo de actualizar a HA 2024.8 y la integración ha dejado de funcionar.

He realizado un restore de un fullbackup 2024.7 y funciona de nuevo.

He actualizado mi HA de Test y tras agregar HACS y el repositorio de edata no soy capaz de agregar la integración, ya que no aparece.

Supongo que tendremos que esperar a que sea compatible con 2024.8

Gracias de nuevo por el trabajo.

**Comment by uvejota** [comment]
La próxima release está en estado alpha.

Realmente es perfectamente funcional, pero alguna de las nuevas funcionalidades no están pulidas (en términos de usabilidad).

Intentaré liberarla lo antes posible para el público general.

**Comment by yuuues** [comment]
Para los interesados, para cambiar la versión:

- Vais a HACS
- En e-data, menú y "Volver a descargar"
![image](https://github.com/user-attachments/assets/7ca6cb3a-eab2-4c25-9960-4da6d7368073)
- Añadís "mostrar versiones beta" y escogéis la más nueva (2024.07.0-alfa.9 a día de hoy)
![image](https://github.com/user-attachments/assets/dc03264d-8e6a-4db7-90a0-24dd63cd46b5)
- Descargar
- Reiniciar HomeAssistant
- Ya funciona sin tocar nada extra

**Comment by JordiGrasvi** [comment]
Despues de reiniciar se tiene que volver a HACS y actualizar la version y volver a reiniciar
![Captura de pantalla 2024-08-09 a les 9 03 16](https://github.com/user-attachments/assets/1f5e93f8-86df-4ff5-8637-29db8087bb9d)

**Comment by cvc90** [comment]
Al actualizar a la nueva versión la mayoría de tarjetas con la información han dejado de dar información correctamente o no muestran datos, están disponibles en algún lado las plantillas de gráficos? o alguien seria tan amable de compartir para actualizar las actuales? Porque la información del [borrador](https://github.com/uvejota/homeassistant-edata/blob/2024_major/README.md) no esta completa.

Se podría añadir en forma de sensor la potencia contratada? Para añadirlo al informe? O existe alguna forma de cargar ese atributo en una tarjeta de entidades?

![image](https://github.com/user-attachments/assets/b21e6f47-475f-4598-88dc-e26061d8865b)

**Comment by Miguelhd70** [comment]
Gracias por la rápida actualizacion
