### ISSUE TITLE
Error en la fecha de las tarjetas summary

### ISSUE THREAD

**Issue by frgalan** [uvejota/homeassistant-edata#246]
Hola, 

Ante todo darte las gracias por el proyecto, y por esta acualizacion añadiendo tarjetas, compatibilidad con HA 2024.8 etc

Queria comentarte que estoy probando las tarjetas summary y la fecha me aparece con un mes de antelacion, dia y año es correcto pero el mes es el anterior, por ejemplo a dia de hoy me aparece 11/07/2024

**Comment by uvejota** [comment]
Oído cocina, creo que esa es fácil ;)

**Comment by Davegee77** [comment]
Hola, 
Pero os importa bien los datos de datadis? 
A mi se me han quedado estancado en un dia y no importa resto.

**Comment by adrz95** [comment]
Buenas,
Añado un poco de debug, después de actualizar a la última version de HA Core 2024.8.1 y HA Supervisor 2024.08.0 he perdido las entidades que genera edata.

Si encuentro algo más lo subo.

```
Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2085, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/edata/sensor.py", line 20, in <module>
    from .coordinator import EdataCoordinator
  File "/config/custom_components/edata/coordinator.py", line 19, in <module>
    from .stats import EdataStatistics
  File "/config/custom_components/edata/stats.py", line 10, in <module>
    from homeassistant.components.recorder.const import DATA_INSTANCE
ImportError: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)
```

PD: Acabo de ver la pre-release [2024.07.1](https://github.com/uvejota/homeassistant-edata/releases/tag/2024.07.1) , seguro aquí se solventa el problema. Gracias!

**Comment by uvejota** [comment]
> Buenas,
> 
> Añado un poco de debug, después de actualizar a la última version de HA Core 2024.8.1 y HA Supervisor 2024.08.0 he perdido las entidades que genera edata.
> 
> 
> 
> Si encuentro algo más lo subo.
> 
> 
> 
> ```
> 
> Error doing job: Task exception was never retrieved (None)
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2085, in async_forward_entry_setups
> 
>     await integration.async_get_platforms(platforms)
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
> 
>     import_future.result()
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
> 
>     platforms.update(self._load_platforms(platform_names))
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
> 
>     platform_name: self._load_platform(platform_name)
> 
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
> 
>     cache[full_name] = self._import_platform(platform_name)
> 
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
> 
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> 
>     return func(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> 
>   File "/config/custom_components/edata/sensor.py", line 20, in <module>
> 
>     from .coordinator import EdataCoordinator
> 
>   File "/config/custom_components/edata/coordinator.py", line 19, in <module>
> 
>     from .stats import EdataStatistics
> 
>   File "/config/custom_components/edata/stats.py", line 10, in <module>
> 
>     from homeassistant.components.recorder.const import DATA_INSTANCE
> 
> ImportError: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)
> 
> ```
> 
> 
> 
> PD: Acabo de ver la pre-release [2024.07.1](https://github.com/uvejota/homeassistant-edata/releases/tag/2024.07.1) , seguro aquí se solventa el problema. Gracias!

Raro. La línea de código que te falla lleva sin cambiar al menos un año. Es al importar el recorder. 

Se me ocurren dos opciones a priori: a) que al actualizar HA se ha jodido algo, b) que tienes deshabilitado el recorder.

En cualquier caso, acabo de probar en la misma plataforma y versión que tú y sin problemas. Dime si te saca logs distintos.

Gracias

**Comment by frgalan** [comment]
A mi si me funciona con la ultima prerelease 2024.7.1

Veo datos de ayer y confirmo que el problema de las fechas esta solucionado.

Veo que en los detalles pones que vas a sacar una opcion para cambiar el ciclo de facturacion ?

**Comment by uvejota** [comment]
> A mi si me funciona con la ultima prerelease 2024.7.1
> 
> 
> 
> Veo datos de ayer y confirmo que el problema de las fechas esta solucionado.
> 
> 
> 
> Veo que en los detalles pones que vas a sacar una opcion para cambiar el ciclo de facturacion ?

Está entre mis próximos cambios, si. Con otras muchas cosas... tengo muchas ideas pero muy poco tiempo :)

De primeras, voy a intentar que le funcione a todo el mundo, y poco a poco a ver si implemento esas pequeñas mejoras (cuando se me pase el empacho de estos días, que ha sido intenso).

**Comment by frgalan** [comment]
Normal, al final esto tiene faena al depender de tantas cosas.

Cierro este bug al estar ya solucionado ?

**Comment by uvejota** [comment]
> Buenas,
> 
> Añado un poco de debug, después de actualizar a la última version de HA Core 2024.8.1 y HA Supervisor 2024.08.0 he perdido las entidades que genera edata.
> 
> 
> 
> Si encuentro algo más lo subo.
> 
> 
> 
> ```
> 
> Error doing job: Task exception was never retrieved (None)
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2085, in async_forward_entry_setups
> 
>     await integration.async_get_platforms(platforms)
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
> 
>     import_future.result()
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
> 
>     platforms.update(self._load_platforms(platform_names))
> 
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
> 
>     platform_name: self._load_platform(platform_name)
> 
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
> 
>     cache[full_name] = self._import_platform(platform_name)
> 
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
> 
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
> 
>     return func(*args, **kwargs)
> 
>            ^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
> 
>     return _bootstrap._gcd_import(name[level:], package, level)
> 
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
> 
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
> 
>   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
> 
>   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
> 
>   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
> 
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
> 
>   File "/config/custom_components/edata/sensor.py", line 20, in <module>
> 
>     from .coordinator import EdataCoordinator
> 
>   File "/config/custom_components/edata/coordinator.py", line 19, in <module>
> 
>     from .stats import EdataStatistics
> 
>   File "/config/custom_components/edata/stats.py", line 10, in <module>
> 
>     from homeassistant.components.recorder.const import DATA_INSTANCE
> 
> ImportError: cannot import name 'DATA_INSTANCE' from 'homeassistant.components.recorder.const' (/usr/src/homeassistant/homeassistant/components/recorder/const.py)
> 
> ```
> 
> 
> 
> PD: Acabo de ver la pre-release [2024.07.1](https://github.com/uvejota/homeassistant-edata/releases/tag/2024.07.1) , seguro aquí se solventa el problema. Gracias!

Ignora mi comentario anterior. Te he confundido con la persona que inició el hilo y asumí que tenías la última versión instalada...

Actualiza y supongo que volverá a la vida.

**Comment by uvejota** [comment]
> Normal, al final esto tiene faena al depender de tantas cosas.
> 
> 
> 
> Cierro este bug al estar ya solucionado ?

Adelante :)
