### ISSUE TITLE
Sensor.edata estancado

### ISSUE THREAD

**Issue by Davegee77** [uvejota/homeassistant-edata#249]
Hola Crack!
Gracias por tu esfuerzo !!

No encuentro la solución, toda la integración está bien hecha, recibo datos pero se ha bloqueado a Julio,.
De hecho Datadis no recibia datos de edistribución hasta hace unos dias pero ya ha actualizado y mis sensores no los reciben.
Agradezco tambien tu ayuda de antemano!

Gracias!

**Comment by Davegee77** [comment]
Solucionado,
He eliminado todos los archivos de la integración, incluoso los de config/storage y he vuelto a integrar. 

Gracias!

**Comment by atineo** [comment]
Me esta volviendo loco con el mismo tema, estancado desde el 6 de agosto y venga a instalar y desinstalar. Fue borrar lo relacionado a edata en .storage como decia @Davegee77 y solucionado
