### ISSUE TITLE
Acceso API datadis

### ISSUE THREAD

**Issue by juanbaldovi** [uvejota/homeassistant-edata#25]
Buenas tardes
estoy tratando de registrarme en datadis pero mencionan que solo se tiene acceso a la API si se tiene NIF con formato CIF.
Entiendo que los clientes particulares no podemos hacer uso de la API
¿Alguien me podría confirmar si es así?
Gracias

**Comment by uvejota** [comment]
Buenas, existen dos APIs, una para empresas y otra privada (la que usamos aquí). La privada la tienen todas las cuentas automáticamente, no tienes que marcar la casilla.

¡Un saludo!
