### ISSUE TITLE
Se ha desconfigurado despues de actualizar Home Assistant

### ISSUE THREAD

**Issue by Tramuset** [uvejota/homeassistant-edata#251]
No es posible configurar edata sensor agregando platform: edata a la configuración sensor. Consulta la documentación para obtener más información sobre cómo configurar esta integración.

Para resolver esto:

Elimina las ocurrencias platform: edata de la configuración sensor: en tu archivo de configuración YAML.
Reinicia Home Assistant.
Ejemplo que debe ser eliminado:

sensor:
 - platform: edata

**Comment by uvejota** [comment]
Afirmativo. La config. YAML lleva obsoleta unos años, hay que pasarse a la configuración UI.

**Comment by uvejota** [comment]
Voy a cerrar este hilo y lo dejo en la cabecera del #247, por organizar un poco.

Gracias.
