### ISSUE TITLE
Visualizacion consumos en tarjetas

### ISSUE THREAD

**Issue by SmilinStanSStanman** [uvejota/homeassistant-edata#254]
![Screenshot_2024-08-22-16-13-13-42_c3a231c25ed346e59462e84656a70e50](https://github.com/user-attachments/assets/3c8370cd-5da6-4db0-adb2-131d7b8ee269)

He visto que la cantidad consumida cada mes se visualiza con infinidad de decimales. ¿Es posible limitarlo (por ejemplo 2 decimales) sin necesidad de crear un sensor manualmente que sea el redondeo de esa cifra?

**Comment by uvejota** [comment]
Se ha discutido aquí: #247 

Estará corregido en la próxima release estable.
