### ISSUE TITLE
Atributo precio desaparecido y graficas de tarta sin datos

### ISSUE THREAD

**Issue by txespirito** [uvejota/homeassistant-edata#26]
Hola,
en primer lugar gracias por el excelente trabajo que estas realizando, una gran integración.
He visto que en mi sensor de edata no aparece el atributo del precio.
Por otro lado en las graficas de tarta que pones en la web no me recupera los datos pese a que en el sensor aparecen en los atributos. La grfica es aparentemente simple pero no me coge los valores (los artibutos estan bien escritos con mayusculas y minusculas). ¿que puede pasar?

GRacias

**Comment by uvejota** [comment]
Hola, si tienes una configuración personalizada del recorder es posible que no esté incluyendo el sensor, y por tanto no se puede leer histórico de atributos.

¡Un saludo!

**Comment by Luismi669** [comment]
A la hora de configurar el sensor eData debes incluir:
    experimental: true
A mi así me ha funcionado.
¡Un saludo!

**Comment by txespirito** [comment]
GRacias. Efectivamente, en el recorder tenia un caracter del nombre del sensor de edata mal puesto y no me cogia el historico.
