### ISSUE TITLE
Aplicación de impuestos errónea

### ISSUE THREAD

**Issue by jorgemarmor** [uvejota/homeassistant-edata#260]
Hola, 

He visto que en las fórmulas de cálculo de costes hay lo que creo que es un error en la fórmula al aplicar los impuestos a energía y potencia. 

ahora mismo se multiplica el factor de IVA con el del impuesto de electricidad, cuando realmente son dos impuestos independientes. 

Es decir, ahora se hace 1.05 * 1.10, lo que supone que se está aplicando un impuesto total del 15.5%. Sin embargo, ambos impuestos se aplican sobre el total antes de impuestos, es decir que por un lado se aplica el 1.05 y por otro el 1.10, lo que supondría 1.10+1.05=1.15 (un 15% total). 

La diferencia no es mucho dinero, pero en la próxima actualización se podría corregir el tema

Un saludo

**Comment by uvejota** [comment]
Buen ojo.

Pues es una duda que tuve en su momento, aunque la lógica me decía que ambos impuestos deben aplicarse sobre el precio base, al probar con mi factura la que me daba los céntimos exactos era el producto... Investigaré e intentaré corregirlo, pero daré prioridad a los errores funcionales, ya que éste puede corregirlo el usuario modificando la fórmula.

En cualquier caso, tenía pensado hacer un pequeño _rework_ de las fórmulas para aplicar impuestos (y descuentos) a posteriori.

Gracias

**Comment by zeehio** [comment]
Según https://ganaenergia.com/blog/legalidad-aplicar-iva-impuesto-electrico/ el iva se aplica también sobre el impuesto eléctrico. Y parece que eso es lo que dice la ley del IVA. 

Intuyo que esto es igual que el iva que pagas sobre el impuesto a hidrocarburos al poner gasolina o el impuesto al tabaco.

```
iva = 0.10
imp_electricidad =  0.05113
coste_potencia = ...
coste_consumo = ...
impuesto_elec_base_imponible = coste_potencia + coste_consumo
coste_imp_elec = imp_electricidad*impuesto_elec_base_imponible
iva_base_imponible = coste_potencia + coste_consumo + coste_imp_elec
coste_iva = iva* iva_base_imponible
total_factura = coste_potencia + coste_consumo + coste_imp_elec + coste_iva
```

Así que en mi opinión el cálculo que se hace en esta integración se corresponde con lo que dice la ley del IVA y lo que veo en mi factura también.

**Comment by jorgemarmor** [comment]
Perdonad, @zeehio tiene razón. Tal y como lo presentaban en mi factura parecía que lo aplicaban por separado, pero es cierto que al final me meten el IVA a todo (vaya doble imposición de manual). Cierro el issue.
