### ISSUE TITLE
Varios CUPs Empresa

### ISSUE THREAD

**Issue by boitaullresort** [uvejota/homeassistant-edata#27]
Muchas gracias por tu genial trabajo,

he encontrado un problema, tengo varios CUPs de empresa,
es decir tengo los datos de la persona física, y de la persona jurídica que es un CIF y a pesar de poder ver los datos en la web, no me carga ningún dato en Home assitant, 

gracias

**Comment by uvejota** [comment]
Buenas, gracias. Creo que aunque sea un CIF debería funcionar, dame más datos ¿qué síntomas da?

**Comment by boitaullresort** [comment]
todo funcionado :-(, faltaba paciencia

gracias  :-)
