### ISSUE TITLE
Una vez configurado no arranca HA

### ISSUE THREAD

**Issue by miquellaboria** [uvejota/homeassistant-edata#30]
Lo he configurado y una vez todo puesto HA no arranca ¿puede ser un problema de la carga inicial?

¡Gracias!

**Comment by tco69** [comment]
Hola, mismo problema

es añadir el código en configuration.yaml y se queda bloqueado....

Alguna idea?

**Comment by uvejota** [comment]
Buenas, nunca me ha ocurrido lo anterior. ¿Os sigue pasando?

**Comment by tco69** [comment]
Hola, 
por motivos varios tuve que cambiar el tipo de instalación del HA de core a docker y parece que funciona (ya no se si por instalación limpia o por el cambio).

Un saludo y gracias.
