### ISSUE TITLE
Autoconsumo, falta posibilidad ver el excedente.

### ISSUE THREAD

**Issue by janiversen** [uvejota/homeassistant-edata#32]
Tengo placas solares de forma autoconsumo, y el parte de energía que no usamos va al red electrica (a un precio miserable). En realidad es un registro más en el contador.

Como es posible ver el excedente ?

**Comment by janiversen** [comment]
Ps. soy socio de HomeAssistant, entonces si tu sabes como, pero te falta tiempo para hacerlo, dime y yo voy a hacer un “pull request”.

**Comment by uvejota** [comment]
Buenas, hace meses que no indago al respecto por lo que no sé si datadis.es da esta información. ¿Sabes si lo hace?

Estas navidades espero tener algo de tiempo para dedicarle a este proyecto, y sería buena mejora.

Gracias, un saludo.

**Comment by janiversen** [comment]
He preguntado datadis y ellos han respondido:

Buenas,
 
                Esta información aún no está disponible en datadis, se prevé tener información del autoconsumo en la actualización de la plataforma que se realizará a mediados de febrero, si está registrado le llegará un correo informando de dicha actualización.
 
Muchas gracias.
 
Un saludo.



Entonces voy a esperar hasta Febrero.

**Comment by alexsalvo1** [comment]
Veo que en el portal de datadis están disponibles los datos de autoconsumo

**Comment by Veletax** [comment]
Los datos sobre autoconsumo estan diponibles en el portal datadis.

![image](https://user-images.githubusercontent.com/76955615/178123872-544ae9ac-5905-4274-93fc-acf1f0999549.png)

**Comment by uvejota** [comment]
Buenas @alexsalvo1 @Veletax 

¿Podéis decirme si en Datadis en el apartado de API privada sale algo relacionado con el autoconsumo? Sale como una documentación en esa pestaña.

A mi no me sale nada, pero claro, no tengo autoconsumo... sin esa info no puedo programarlo. O bien no lo han hecho accesible desde la API privada, o bien no me sale a mi porque no tengo ningún suministro con autoconsumo.

**Comment by alexsalvo1** [comment]
Hola,

No, en la API privada no esta disponible nada relacionado a el autoconsumo. Voy a enviarle un correo a Datadis para preguntar.
Gracias por mirar :)

**Comment by alexsalvo1** [comment]
Me acaban de contestar lo de Datadis y me dicen que de momento no van a publicar la Api del autoconsumo. 
Le he pedido fecha de salida y tampoco eso 😔

**Comment by uvejota** [comment]
Pues tendremos que esperar, ¡gracias por las gestiones!

Reabriremos la issue cuando proceda.

**Comment by isaacyera** [comment]
Hola,
Acaban de publicar via API toda la parte de autoconsumo. Ahora la consulta get-consumption-data también retorna el valor  de la energía exportada
```
[
  {
    "cups":"String", | CUPS
    "date":"String", | Fecha (aaaa/MM/dd)
    "time":"String", | Hora (hh:mm)
    "consumptionKWh":Number, | Energía consumida (kWh)
    "obtainMethod":"String", | Método de obtención de la energía consumida (Real/Estimada)
    "surplusEnergyKWh":Number | Energía vertida (neteada/facturada) (kWh)
  }
]
```

**Comment by carlituxman** [comment]
Hay alguna previsión de poder tener esta info? 
Gracias!
