### ISSUE TITLE
No obtiene datos de maxímetro

### ISSUE THREAD

**Issue by joseal70** [uvejota/homeassistant-edata#33]
Hola uvejota, espero que vaya todo bien, hace mucho que no tenemos noticias tuyas por aquí. No sé si ya no se mantiene este repositorio.

He bajado la potencia de 5,75 a 4, pero aún me sigue cogiendo la antigua 5,75.

![Screenshot_20211207-095332](https://user-images.githubusercontent.com/63608768/144998494-016498f6-cdc3-41b7-b2d7-fe07c9fd600a.jpg)

![Screenshot_20211207-095437](https://user-images.githubusercontent.com/63608768/144998571-5b6de59e-ee51-49ba-98f2-c8d49d4028ce.jpg)

Actualizo:
He borrado edata.storage_49JF de . STORAGE y vuelto a reinstalar la integración.
Ahora ya aparece la nueva potencia, pero en consumo mensual no salen los meses anteriores al cambio, en maxímetro se queda Loading, y los precios en N/A.

![Screenshot_20211207-103132__01](https://user-images.githubusercontent.com/63608768/145004608-7f031841-5066-40f6-88eb-dc72cf193439.jpg)

Un saludo y gracias por todo.

**Comment by uvejota** [comment]
Buenas, el proyecto sigue en marcha aunque como habéis notado unos cuantos lleva unos meses en standby, principalmente debido al trabajo (ha sido época de cambios, con el consumo adicional de tiempo que eso conlleva).

La gestión de contratos/consumos no es buena en la versión actual, tampoco lo es la resolución de huecos de consumos, ni la estimación del pvpc (está desactualizado). Soy consciente y lo tengo aparcado hasta que saque algo de tiempo (espero que estas navidades pueda retomarlo). Aunque no responda a los hilos de GitHub, lo tengo todo anotado.

Muchas gracias por los datos aportados, me servirá para resolverlo.

¡Un saludo!

**Comment by uvejota** [comment]
Buenas, ¿te sigue ocurriendo con la versión 2021.12.2 que acabo de subir?

Si te sigue ocurriendo, pégame también aquí el periodo detectado del suministro porfa (igual que me has puesto arriba el de los contratos) :-)

¡Gracias!

**Comment by joseal70** [comment]
Hola, ya me funcionó y salía la potencia correcta, lo indique más arriba en una actualización que puse. Tuve que borrar el archivo edata.storage.
Lo que seguía fallando, y con esta última versión igual, es el maxímetro que se queda en Loading.
Aunque hoy he cambiado de PVPC a una tarifa fija, y con otra comercializadora. No sé cómo saldrá todo cuando el cambio se haga efectivo.

Te pongo los periodos de suministro y una captura de como sale ahora todo.

                "date_start": "1970-01-01T00:00:00",
                "date_end": "2021-12-30T00:00:00",



![Screenshot_20211229-161520__01__01](https://user-images.githubusercontent.com/63608768/147678630-77092366-ea94-4783-9a50-cd95451f3dec.jpg)


Muchas gracias

**Comment by uvejota** [comment]
Qué raro lo del maxímetro, lo añado a la lista de cosas por revisar. Mil gracias.

**Comment by uvejota** [comment]
Lo del maxímetro pinta a que al "cambiarte" la fecha de inicio del contrato, la API se vuelve loca...

¿Te sigue ocurriendo?

**Comment by joseal70** [comment]
Hola uvejota, 
Llevaba tiempo sin actualizar nada de Home Assistant, desde el año pasado, y no he podido probar nada.
Acabo de terminar de instalar todo, y he visto que ya me funciona bien.
Me ha gustado se pueda usar ahora con el tablero de energía de HA. 

Muchas gracias por todo 👍
