### ISSUE TITLE
CUPS Null en respuesta

### ISSUE THREAD

**Issue by yuliusvk** [uvejota/homeassistant-edata#35]
Buenas, primero, gran currada con esta integración, me parece super util.
Quería comentarte una cosilla me imagino que es un error de datadis pero yo lo comento. Desde hace aproximadamente un mes no veo que se me muestren datos en la integración.
He revisado las llamadas a las APIs desde la propia página de datadis y veo que al consultar mis consumos:
https://datadis.es/api-private/api/get-consumption-data?cups=ES0026XXXXXXX&distributorCode=3&startDate=2021%2F12%2F10&endDate=2021%2F12%2F15&measurementType=0&pointType=5
La respuesta obtenida de la API devuelve registros de este tipo:
[ {
  "cups" : null,
  "date" : "2021/12/10",
  "time" : "01:00",
  "consumptionKWh" : 0.073,
  "obtainMethod" : "Real"
}, {
  "cups" : null,
  "date" : "2021/12/10",
  "time" : "02:00",
  "consumptionKWh" : 0.072,
  "obtainMethod" : "Real"
},
.....
....
Puede ser que no se me muestren los datos de la integración por venir el cups de la respuesta a nulo?
Existe alguna manera de que no se realizara esta comprobación?
Muchas gracias!

**Comment by uvejota** [comment]
Hola, tengo unos días para corregir estos errores. ¿Te sigue pasando?

**Comment by yuliusvk** [comment]
Buenas,

muchas gracias, pero parece que después de escribirles un correo al buzón
de soporte ya han comenzado a devolverme el CUPS en las respuesta y la
integración ya me forma las gráficas.

 {
  "cups" : "ES0026000010093948BT0F",
  "date" : "2021/12/01",
  "time" : "22:00",
  "consumptionKWh" : 0.346,
  "obtainMethod" : "Estimada"},


Un saludo y enhorabuena por una integración tan útil.
