### ISSUE TITLE
Edata no funciona tras actualización a Home Assistant 2021.12.5

### ISSUE THREAD

**Issue by emailforos** [uvejota/homeassistant-edata#36]
Hola

Antes que nada, ¡Feliz Navidad!

Llevo muchos días con tu integración funcionando pero hoy tras actualizar a 2021.12.5 HA, me salta el siguiente error y no se carga el sensor:
```
Error while setting up edata platform for sensor

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/edata/sensor.py", line 44, in async_setup_platform
    entities.append(EdataSensor(hass, config[CONF_USERNAME], config[CONF_PASSWORD], config[CONF_CUPS], experimental=experimental))
  File "/config/custom_components/edata/sensor.py", line 77, in __init__
    self._helper = EdataHelper ('datadis', self._usr, self._pwd, self._cups, experimental=self._experimental)
  File "/usr/local/lib/python3.9/site-packages/edata/helpers.py", line 92, in __init__
    self._pvpc = EsiosConnector (data=self._data, log_level=log_level)
  File "/usr/local/lib/python3.9/site-packages/edata/connectors.py", line 335, in __init__
    self._handler = PVPCData(tariff=TARIFFS[0], local_timezone=self._local_timezone)
TypeError: __init__() missing 1 required keyword-only argument: 'session'

```
He reinstalado la integración, he entrado en Datadis a ver si había algo que no funcionaba pero no he encontrado nada.

A ver si alguien con conocimientos me puede orientar.

**Comment by uvejota** [comment]
Buenas, voy a ver qué puede ser. Estoy trabajando en una serie de mejoras estos días que estoy de vacaciones.

Gracias por la info!

**Comment by uvejota** [comment]
Como "workaround", puedes deshabilitar la descarga de precios PVPC poniendo `experimental: false` en la configuración del yaml, y debería andar mientras encuentro una solución.

**Comment by lobolobo** [comment]
Muchas gracias @uvejota, el "workaround" funciona.

**Comment by emailforos** [comment]
Muchas gracias por mirértelo tan rápido sobretodo en un día com hoy.

He hecho el cambio y funciona. Quedo a la espera de si necesitas alguna info / prueba para avanzar en el fallo o para que avises de que no es problema de la integración.

**Comment by vmanuel** [comment]
Muchas gracias! ¡Disfrutard todos de estos días!

**Comment by uvejota** [comment]
Seguimos en #37
