### ISSUE TITLE
Actualizar dependencia aiopvpc (3.0.0)

### ISSUE THREAD

**Issue by vmanuel** [uvejota/homeassistant-edata#37]
Con la última actualización de HA 2021.12.5 hay una actualización de pvpc que implica aiopvpc==3.0.0

Parece que hay problemas si existe el Custom Component de e-data (no actualiza a esa versión aiopvpc y no inicializa)

https://github.com/home-assistant/core/issues/62699

**Comment by uvejota** [comment]
Afirmativo, acabo de comprobarlo.

Como workaround podéis desactivar la tarificación de edata con `experimental: false`.

Es una tontería, pero hoy es un día especial :-) 

Cuando me acabe la caja de polvorones lo arreglo.

Felices fiestas

#36

**Comment by lobolobo** [comment]
Muchas gracias @uvejota . Feliz Navidad. :-)
