### ISSUE TITLE
Cuando se crean dos sensores, uno para cada contador, los datos se mezclan

### ISSUE THREAD

**Issue by jumate** [uvejota/homeassistant-edata#4]
Si se define un sensor para cada contador en un mismo perfil (mismo usuario de datadis), los datos de uno y otro se mezclan, o aparecen los datos de uno de ellos en los dos sensores, aunque se crean dos sensores cada uno acabado con los 4 alfanumericos de cada contador.

- platform: edata
  provider: datadis
  username: !secret my_datadis_username
  password: !secret my_datadis_password
  cups: !secret edistribucion_endcups
- platform: edata
  provider: datadis
  username: !secret my_datadis_username
  password: !secret my_datadis_password
  cups: !secret edistribucion_endcups_2

**Comment by uvejota** [comment]
Hola @jumate, soy consciente de lo que comentas y tengo pendiente solucionarlo. 

¡Gracias por el testeo!

**Comment by uvejota** [comment]
Hola, esto debería estar solucionado en v0.1.7-beta.11 

Prueba y me dices :-)

**Comment by jumate** [comment]
Probado.
Funciona correctamente, cada sensor muestra sus datos, de dos contadores diferentes.

Solucionado.
