### ISSUE TITLE
Roadmap / discusión general

### ISSUE THREAD

**Issue by uvejota** [uvejota/homeassistant-edata#41]
<details>
<summary>Ver introducción original/agradecimientos</summary>

Buenas a todos, este hilo es únicamente para exponeros la hoja de ruta a seguir en el desarrollo de esta integración. Como sabéis, en su estado actual es un prototipo, aunque gracias a las tarjetas de apexcharts-card ha quedado una integración muy resultona.

Antes de nada, agradecer la enorme aceptación y apoyo. 

60 estrellas en el repositorio no es ninguna broma, y mucho menos para un proyecto personal desarrollado en tan poco tiempo. También la paciencia ante la falta de actualizaciones por motivos de trabajo. Al no dedicarme profesionalmente al desarrollo he cometido infinitos fallos por el camino que hace que tengamos ciertos problemas estructurales y fallos que con el paradigma actual son tediosos de resolver, por lo que veo mejor intentar reencaminar la base a algo más sólido.

</details>

### Problemas identificados
* ~~El sistema de almacenamiento actual se realiza mediante un volcado en json a un fichero, 1 vez al día. Aunque no supone gran problema ya que el fichero únicamente almacena el último año de consumos, no es ideal, ni mucho menos la mejor opción.~~
* ~~La definición de datasets en el backend es confuso.~~ Resuelto en 2022.11.2
* ~~Depender del módulo data-generator de apexcharts-card implica una configuración tediosa y complicada para algunos usuarios.~~ De momento no hay solución aparente.
* ~~La API de Datadis no es particularmente robusta, lo cual lleva a hacer "guarrerías" para resolver las incongruencias que a veces devuelve (huecos en periodos de datos).~~ Hacemos lo que se puede, que no es demasiado, pero parece bastante consistente a día de hoy.

### Fallos conocidos
* ~~**La tarificación**, históricamente limitada al PVPC (Precio Voluntario al Pequeño Consumidor) en su tarifa 2.0TD, se encuentra desactivada en la última versión para evitar los problemas indicados en la issue #37. El desarrollador de la biblioteca que permite la descarga de estos datos ha limitado recientemente los métodos de la misma al uso de la integración oficial de PVPC de HA, por lo que la he deshabilitado a propósito.~~
* ~~En algunos casos, existen problemas al rescatar los datos de datadis, normalmente provocados por respuestas anómalas a las peticiones enviadas (e.g., #17, #35). Algunos de ellos pueden ser solucionados/paliados desde aquí pero otros, en cambio, son inevitables.~~

### Roadmap
1. :heavy_check_mark:  Habilitar la **adición de estadísticas externas** mediante esta nueva funcionalidad de HA, de modo que el sensor será seleccionadle en el panel de energía y usaremos la base de datos como almacenamiento de los datos, con la consecuente ganancia de robustez y simplicidad. 
2. :heavy_check_mark: Reescribir, limpiar y **mejorar la estructura de datos** en el back (https://github.com/uvejota/python-edata) para simplificar su funcionamiento.
3. ~~Cuando 1-2 estén satisfechos, **deshabilitar el sistema de almacenamiento actual** a favor de las estadísticas externas de HA.~~ (ha resultado ser poco robusto, mejor mantener el sistema actual - fichero de almacenamiento en /config/.storage/.)
4. ~~Cuando 1-3 estén satisfechos, **actualizar el soporte a apexcharts card para leer desde las estadísticas nativas de HA**.~~ Esto de momento es imposible.
5. :heavy_check_mark: **Implementar la tarificación personalizada** mediante ~~yaml~~ UI, de modo que cada uno pueda describir su fórmula de tarificación ~~mediante una sintaxis sencilla~~. A 5/9/22 se permite únicamente la definición de tarifas fijas para 2.0TD, permitiendo identificar distintos costes fijos en P1/P2/P3. A día 27/11/22 se permite seleccionar PVPC.
6. :heavy_check_mark: Finalmente, permitir la configuración de la integración mediante la UI de HA.
7. ~~Nuevas funcionalidades, como la solicitada en #32 cuando sea posible.~~ Sigue sin ser posible, pero estaremos al loro :)

Y algún día, quizá, tratar de formalizar la integración para añadirla al repositorio de integraciones nativas en HA.

Mi intención es implementar en orden, partiendo de la 1, las mejoras propuestas. Esto llevará un tiempo, sin duda, pero creo que es el mejor camino a seguir (o al menos, el óptimo, considerando mi tiempo).

### Leyenda
:construction: En construcción
:heavy_check_mark: en release
:white_check_mark: en rama `dev`

**Comment by rekix85** [comment]
Mil gracias por todo el trabajo que te estas tomando con este proyecto personal 👏👏👏
Tiene una pintaza tremenda lo que tienes pensado hacer, tus fans esperaremos pacientes cada actualización. Sin prisas y cuando se pueda 😉

**Comment by fritanga** [comment]
Genial, gracias por el trabajo @uvejota

**Comment by uvejota** [comment]
Primer intento de integración con la plataforma de energía (apdo. 1 del roadmap) en versión 2021.12.1 (de momento en pruebas).

https://github.com/uvejota/homeassistant-edata/releases/tag/2021.12.1

**Comment by alexsalvo1** [comment]
Acabo de actualizar a la ultima version. Trabajo excelente de verdad!
La unica cosa que no veo son los consumos del dia de hoy. Entiendo que cargas los consumos del dia anterior, verdad? A lo mejor se prodria pedir el consumo de hoy cada 1-2 horas.

Repito trabajazo!

**Comment by arnauos** [comment]
Al menos en mi caso los consumos que recibe datadis (y la comercializadora) siempre llevan retraso, por ejemplo, a esta hora aún no aparece el consumo del día 27.

**Comment by alexsalvo1** [comment]
Si es verdad, he dicho una estupidez :)

**Comment by uvejota** [comment]
Lo que comenta @arnauos es cierto. En cualquier caso la integración trata de obtener lo que haya lo antes posible :-) 

> Acabo de actualizar a la ultima version. Trabajo excelente de verdad! La unica cosa que no veo son los consumos del dia de hoy. Entiendo que cargas los consumos del dia anterior, verdad? A lo mejor se prodria pedir el consumo de hoy cada 1-2 horas.
> 
> Repito trabajazo!

Es posible que haya errores en los datos del panel (no lo he testado demasiado), pero eso ya lo vamos viendo y lo voy arreglando ;)

**Comment by carlos-48** [comment]
Wow! Gracias!! Funciona genial!!! Lo único es el precio, al cogerlo del sensor de la integración PVPC no me sale nada, entiendo que saldrá a partir de hoy pero no en los datos anteriores. Esto es un tema de PVPC y de Energy de Home Assistant, sé que no es cosa de tu integración, que está coj*nuda...
![Screenshot_20211228-141705~2](https://user-images.githubusercontent.com/63410909/147570270-609c3ca0-31d9-4ce1-9ab1-ac07b242583c.png)

**Comment by rekix85** [comment]
Perdon por mi ignorancia pero, como puedo instalar la nueva actualización? Descomprimir el archivo y copiarlo en custom-components? Es que no la quiero liar y soy bastante novato en esto. Gracias!

**Comment by etatus** [comment]
Una pregunta @uvejota, ¿tienes pensado que la integración contemple el consumo por horas? En principio parece que datadis ofrece los datos por horas y me parece muy útil para calcular lo que pagamos por hora y compararlo con el PVPC para comprobar lo que hemos gastado en las franjas más caras y más baratas. Yo lo he hecho de forma un poco rudimentaria para UFD, pero estaría genial que lo contemplase tu integración.

![cost_hour](https://user-images.githubusercontent.com/7522061/147611343-b333d236-d249-4421-acac-07fbf806e1b8.jpg)

**Comment by carlos-48** [comment]
No sé qué ha pasado que me ham aparecido consumos negativos en el dia de ayer! En las Tarjetas no me pasa, pero en la integración de energía sí.

![Screenshot_20211229-142718](https://user-images.githubusercontent.com/63410909/147667257-3e0b6d35-9484-4b3d-8708-db304faf6c83.png)
![Screenshot_20211229-142737](https://user-images.githubusercontent.com/63410909/147667261-3a904e72-a9e7-4983-a5fc-254cfa91d94d.png)

**Comment by alexsalvo1** [comment]
Me ha pasado exactamente lo mismo.
Para reiniciar todo, he borrado el fichero abajo de la carpeta .storage, como decía la guía, pero tengo los datos en negativo en el mes de junio, pero no entiendo la relación…
Si necesitas algo para la investigación, estoy disponible!

**Comment by uvejota** [comment]
Hola, nos ha pasado a todos, es un bug estúpido. Estoy preparando un fix.

**Comment by uvejota** [comment]
Nueva versión (2021.12.2) en https://github.com/uvejota/homeassistant-edata/releases/tag/2021.12.2

@carlos-48 @alexsalvo1, tendréis que eliminar el fichero `/config/.storage/edata.storage_XXXX` (este procedimiento es temporal, sólo es la forma más rápida que he encontrado para reiniciar las estadísticas)

**Comment by uvejota** [comment]
> Wow! Gracias!! Funciona genial!!! Lo único es el precio, al cogerlo del sensor de la integración PVPC no me sale nada, entiendo que saldrá a partir de hoy pero no en los datos anteriores. Esto es un tema de PVPC y de Energy de Home Assistant, sé que no es cosa de tu integración, que está coj*nuda...
> ![Screenshot_20211228-141705~2](https://user-images.githubusercontent.com/63410909/147570270-609c3ca0-31d9-4ce1-9ab1-ac07b242583c.png)

Para lo del precio de la energía del pasado hay varias soluciones, pero de momento voy a darle prioridad a otras cosas, voy a intentar dejar fino lo mío y ya pasaremos a integrar el trabajo de los demás :-)

**Comment by alexsalvo1** [comment]
> Nueva versión (2021.12.2) en https://github.com/uvejota/homeassistant-edata/releases/tag/2021.12.2
> 
> @carlos-48 @alexsalvo1, tendréis que eliminar el fichero `/config/.storage/edata.storage_XXXX` (este procedimiento es temporal, sólo es la forma más rápida que he encontrado para reiniciar las estadísticas)

Si he borrado el fichero y a cargado de nuevo todos los datos. La unica diferencia respecto ayer es que no ha cargado los datos mas antiguos del 14 julio 2021.

**Comment by raimun00** [comment]
Buenas noches;

He actualizado a la versión 2021.12.2 y en la pestaña Energía no me sale nada, las tarjetas anteriores si que muestran datos actualizados pero en energía no me sale nada.

Soy un poco nuevo en esto, te cuento el proceso de actualización por si hubiera hecho algo mal, me he descargado el zip, lo he descomprimido, he sobrescrito todos los archivos de la carpeta custom_components/edata, he borrado el archivo /config/.storage/edata.storage_XXXX y he reiniciado el HA.

HA está actualizado a la ultima versión Home Assistant 2021.12.7

¿Sabéis que puede estar pasando?

**Comment by arnauos** [comment]
En ajustes > energia has añadido los sensores?

**Comment by raimun00** [comment]
> En ajustes > energia has añadido los sensores?

En configuración>energia>añadir un dispositivo tengo que añadir los 4 sensores de edata, no?

Vale, ya los añadí y me sale una gráfica con barras horizontales con el total, p1, p2 y p3, no me sale las gráficas que veo más arriba, ni distribución de la energía, ni fuentes...

**Comment by uvejota** [comment]
Sólo por informaros del progreso: 

el apartado 6 está en la última release, los apartados 1, 3 están ya a falta de algunas pequeñas mejoras en la rama `dev`, el apartado 5 está implementado parcialmente para 2.0TD.

Espero tener 1-3, 5 terminados para la release de febrero.

**Comment by Trueatzumi** [comment]
Lo dicho por los demas. Gran trabajo. Gracias por tu tiempo.

**Comment by Siroguh** [comment]
Muchas gracias por todo tu trabajo. Haces la vida más fácil a mucha gente.

**Comment by ravlar** [comment]
Muchas gracias por el trabajazo. Es un gusto ver lo que la gente hace de manera altruista. Estoy deseando probar la release de febrero/marzo.

**Comment by uvejota** [comment]
Buenas, he conseguido sacar un minutito para prestaros atención :-)

Antes de nada, quería comentar que el proyecto no está abandonado, ni va a dejar de recibir actualizaciones o mejoras. He desaparecido un par de meses por diversos motivos personales (mudanza, trabajo...) y no he podido hacer mucho más que leeros desde la sombra.

El roadmap sigue en marcha, y tengo que actualizar la documentación con los cambios de apexcharts, pero a la gran mayoría de los problemas habéis encontrado un workaround.

¡Seguiremos en contacto pronto!

**Comment by 50l3r** [comment]
@uvejota muchas gracias por tu trabajo. En un abrir y cerrar de ojos he podido tener importados los datos de datadis en mi HA.

**Comment by adrz95** [comment]
Buenas @uvejota,

No sé si la API de datadis tiene algun problema, pero desde hace unos días tengo los datos incompletos. He intentado realizar la petición por postman, pero la consulta ya la ha realizado hoy  mi HA, así que nada... hasta mañana no podré ver realizar la petición para comprobarlo.

En el panel de datadis los valores parecen ser correctos, también lo he comprobado en e-distribución.

`Last registered kWh date 29 de octubre de 2022, 23:00:00`
La fecha en la que datadis obtuvo datos por última vez.

Tengo una grafica de apex-charts donde veo los consumos totales diarios de los últimos 30 días y **desde el dia 26/10/2022 son incorrectos.** Día en que actualizamos la integración ?

He añadido logs para ver que devuelve la integración:
```  
type: 'edata/consumptions/daily',
scups: 'SA0F'}).then(
   (resp) => {
      console.log(resp)
```
Por ejemplo, el día 26 tengo estos datos:
```
{
    "datetime": "2022-10-26",
    "delta_h": 24,
    "value_kWh": 4.22,
    "value_p1_kWh": 1.36,
    "value_p2_kWh": 1.55,
    "value_p3_kWh": 1.32
}
```
En el panel de datadis (mismos valores que e-distribución) :
![image](https://user-images.githubusercontent.com/49124915/198981953-a8842758-4b1d-4f31-bb49-b4e37688ba0e.png)

Esto es lo mismo en todos los dias desde el dia 26, me he dado cuenta de que a partir de las 17:00 - 18:00 no tengo registros de kWh y es probablemente lo que le falte al total. 

Día 26:
![image](https://user-images.githubusercontent.com/49124915/198982703-04c3b200-04d6-4b5a-a0af-ef6149902fd8.png)

Día 27:
![image](https://user-images.githubusercontent.com/49124915/198982773-32151c94-9ea5-4190-ab74-d8dadd97412d.png)

Día 28:
![image](https://user-images.githubusercontent.com/49124915/198982858-6090f638-c3f7-4599-a4c6-f6ba7bff9d71.png)

OJO. El día 29 tengo el mismo "comportamiento" en datadis y e-distribución.
![image](https://user-images.githubusercontent.com/49124915/198983071-073871ef-2216-4adc-bd85-cd2bb01d6a2f.png)

En este caso, en HA si tengo los mismos valores para el día 29, pero estoy seguro, de que mañana en datadis y e-distribución estarán actualizados y HA se quedará con los datos parciales que ha enviado la API hoy (`Last registered kWh date 29 de octubre de 2022, 23:00:00`). 

Es posible que cuando se realiza la petición a la API de datadis, la integración solo "guarde" los días que no estan en la petición anterior (días nuevos) ?

Quizás me equivoque... creo que en cada petición se debería re-escribir todo.

Gracias por tu/vuestro tiempo! Y perdón por el tocho.

**Comment by uvejota** [comment]
@adrz95 en la última actualización borré una línea sin querer... y ese es el efecto.

La última update debería solucionarlo. La release tiene algo de info de cómo "corregir" las anomalías.

**Comment by adrz95** [comment]
@uvejota Muchas gracias por tu tiempo!

**Comment by uvejota** [comment]
Se puede decir que el roadmap original está prácticamente satisfecho con la nueva versión (2022.11.2).

Es hora de plantear uno nuevo con vuestras sugerencias, colgaré algo aquí en los próximos días.

Mil gracias por el apoyo, es un placer :)

**Comment by BertMart71** [comment]
Parece que Datadis ya publica los datos de Autoconsumo en la API.

¿Es posible plantear finalmente la incorporación de estos datos en la integración?

Gracias
