### ISSUE TITLE
no me reconoce  el sensor edata

### ISSUE THREAD

**Issue by ogitegi** [uvejota/homeassistant-edata#45]
He actualizado el core a su ultima version la 2021.12.6 y al reiniciar no me reconoce el sensor.Lo he reiniciado varias veces pero sigue sin reconocerlo, no he tocado nada solo actualizar.
Igual es posible que no sea compatible con esta actualizacion.Gracias.

**Comment by uvejota** [comment]
Buenas, voy a probar, aunque no debería guardar relación. Te aviso con lo que vea.

**Comment by uvejota** [comment]
He actualizado, y no tengo ningún problema. Actualiza e-data a la última versión o pon `experimental: false` en el fichero de configuración, intuyo que está relacionado con el deshabilitado del PVPC.

**Comment by ogitegi** [comment]
Muchas gracias era eso.haces un trabajo increíble con esta integración.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
