### ISSUE TITLE
Gráfico Apexcharts

### ISSUE THREAD

**Issue by lordraiden** [uvejota/homeassistant-edata#49]
Antes de nada agradecerte el esfuerzo que estás dedicando al proyecto.

Querría pedirte si podrías hace un gráfico de apex charts manteniendo el estilo de los que ya has creado usando la integración de PVPC  para plotear el precio hora de la electricidad
https://www.home-assistant.io/integrations/pvpc_hourly_pricing/

No debe ser difícil pero llevo una hora dándole vueltas y no doy con algo que se parezca a lo que tu has creado

Estoy partiendo de esta base pero no consigo hacerlo funcionar

https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/948

**Comment by lordraiden** [comment]
Un gráfico interesante que se podría adaptar a tu integración

https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877/1332

**Comment by contrasenda** [comment]
Yo utilizo la siguiente integración para ver el gráfico del pvpc:
https://github.com/danimart1991/pvpc-hourly-pricing-card
