### ISSUE TITLE
Errores reportados por home assistant

### ISSUE THREAD

**Issue by lordraiden** [uvejota/homeassistant-edata#50]
![imagen](https://user-images.githubusercontent.com/17175395/147788446-ad0dad03-f038-4acc-a886-79442b49447e.png)

```
This error originated from a custom integration.

Logger: custom_components.edata.websockets
Source: custom_components/edata/websockets.py:34
Integration: edata (documentation, issues)
First occurred: 10:09:03 PM (13 occurrences)
Last logged: 10:15:19 PM

'XXXX'
Traceback (most recent call last):
  File "/config/custom_components/edata/websockets.py", line 34, in websocket_get_maximeter
    connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('maximeter', []))
KeyError: 'XXXX'
```
```

This error originated from a custom integration.

Logger: custom_components.edata.websockets
Source: custom_components/edata/websockets.py:25
Integration: edata (documentation, issues)
First occurred: 10:08:33 PM (48 occurrences)
Last logged: 10:15:19 PM

'XXXX'
Traceback (most recent call last):
  File "/config/custom_components/edata/websockets.py", line 25, in websocket_get_monthly_data
    connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_monthly_sum', []))
KeyError: 'XXXX'

```
```

This error originated from a custom integration.

Logger: custom_components.edata.websockets
Source: custom_components/edata/websockets.py:14
Integration: edata (documentation, issues)
First occurred: 10:06:31 PM (64 occurrences)
Last logged: 10:15:19 PM

'XXXX'
Traceback (most recent call last):
  File "/config/custom_components/edata/websockets.py", line 14, in websocket_get_daily_data
    data = hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_daily_sum', [])
KeyError: 'XXXX'
```

```
Logger: edata.connectors
Source: /usr/local/lib/python3.9/site-packages/edata/connectors.py:175
First occurred: 10:05:56 PM (1 occurrences)
Last logged: 10:05:56 PM

Connector: still missing the following consumption ranges [{'from': datetime.datetime(2020, 12, 1, 0, 0), 'to': datetime.datetime(2021, 5, 31, 0, 0)}, {'from': datetime.datetime(2021, 12, 17, 23, 0), 'to': datetime.datetime(2021, 12, 18, 23, 0)}, {'from': datetime.datetime(2021, 12, 29, 23, 0), 'to': datetime.datetime(2021, 12, 30, 22, 5, 10, 892482)}], will try again later

```

**Comment by lordraiden** [comment]
tras seguir los pasos y esperar un rato de momento me muestra esto. El gráfico de arriba a la izquierda es de otra integración, el resto son los que hay en el tutorial

![imagen](https://user-images.githubusercontent.com/17175395/147788614-912cb2cc-cc2a-48a4-826c-12c30521f0e6.png)

**Comment by lordraiden** [comment]
![imagen](https://user-images.githubusercontent.com/17175395/147789199-ff8bf0ab-60ba-4618-893f-19a746a5ee5b.png)

Tampoco me aparece aquí edata y se supone que debería, tengo la última versión de HA y de edata

**Comment by uvejota** [comment]
Buenas, trato de responderte:

> ```
> This error originated from a custom integration.
> 
> Logger: custom_components.edata.websockets
> Source: custom_components/edata/websockets.py:34
> Integration: edata (documentation, issues)
> First occurred: 10:09:03 PM (13 occurrences)
> Last logged: 10:15:19 PM
> 
> 'XXXX'
> Traceback (most recent call last):
>   File "/config/custom_components/edata/websockets.py", line 34, in websocket_get_maximeter
>     connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('maximeter', []))
> KeyError: 'XXXX'
> ```
> 
>  ```
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.edata.websockets
> Source: custom_components/edata/websockets.py:25
> Integration: edata (documentation, issues)
> First occurred: 10:08:33 PM (48 occurrences)
> Last logged: 10:15:19 PM
> 
> 'XXXX'
> Traceback (most recent call last):
>   File "/config/custom_components/edata/websockets.py", line 25, in websocket_get_monthly_data
>     connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_monthly_sum', []))
> KeyError: 'XXXX'
> ```
> 
>  ```
> 
> This error originated from a custom integration.
> 
> Logger: custom_components.edata.websockets
> Source: custom_components/edata/websockets.py:14
> Integration: edata (documentation, issues)
> First occurred: 10:06:31 PM (64 occurrences)
> Last logged: 10:15:19 PM
> 
> 'XXXX'
> Traceback (most recent call last):
>   File "/config/custom_components/edata/websockets.py", line 14, in websocket_get_daily_data
>     data = hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_daily_sum', [])
> KeyError: 'XXXX'
> ```
> 

Estos dos errores son por no haber configurado correctamente las tarjetas de apexcharts, hay que sustituir todos los XXXX por los 4 últimos caracteres de tu CUPS (más info en la documentación)

>  ```
> Logger: edata.connectors
> Source: /usr/local/lib/python3.9/site-packages/edata/connectors.py:175
> First occurred: 10:05:56 PM (1 occurrences)
> Last logged: 10:05:56 PM
> 
> Connector: still missing the following consumption ranges [{'from': datetime.datetime(2020, 12, 1, 0, 0), 'to': datetime.datetime(2021, 5, 31, 0, 0)}, {'from': datetime.datetime(2021, 12, 17, 23, 0), 'to': datetime.datetime(2021, 12, 18, 23, 0)}, {'from': datetime.datetime(2021, 12, 29, 23, 0), 'to': datetime.datetime(2021, 12, 30, 22, 5, 10, 892482)}], will try again later
> ```

Este error es cosa de Datadis, por algún motivo no te está "dando" esos rangos de datos, por lo que tendrás huecos en esos intervalos. La API de Datadis en algunos casos no te da los datos que le pides, y a veces se soluciona cambiando los rangos (haciéndolos más pequeños), pero en otros no. La integración trata  de resolver estos huecos automáticamente en cada descarga, a veces no lo consigue, lo único que podemos hacer es esperar.

**Comment by uvejota** [comment]
> ![imagen](https://user-images.githubusercontent.com/17175395/147789199-ff8bf0ab-60ba-4618-893f-19a746a5ee5b.png)
> 
> Tampoco me aparece aquí edata y se supone que debería, tengo la última versión de HA y de edata

Tarda bastante en aparecer, prueba ahora, me parece raro que no te aparezca seleccionable.

Si quieres volver a forzar la carga, elimina el fichero de `/config/.storage/edata.storage_xxxx` y recarga la integración (o reinicia HA)

**Comment by lordraiden** [comment]
> > ![imagen](https://user-images.githubusercontent.com/17175395/147789199-ff8bf0ab-60ba-4618-893f-19a746a5ee5b.png)
> > Tampoco me aparece aquí edata y se supone que debería, tengo la última versión de HA y de edata
> 
> Tarda bastante en aparecer, prueba ahora, me parece raro que no te aparezca seleccionable.
> 
> Si quieres volver a forzar la carga, elimina el fichero de `/config/.storage/edata.storage_xxxx` y recarga la integración (o reinicia HA)

Gracias por responder, dándole vueltas me di cuenta de que tenía la última versión estable pero no la beta, no marqué en HACS la casilla, de modo que ahora si tengo la última versión, he reiniciado y eliminado el fichero edata.storage_xxxx. Ahora ya me aparecen las entradas en la parte de energía de Home assistant, aunque de momento está vacío.
![imagen](https://user-images.githubusercontent.com/17175395/147819100-c96efef7-5392-4b92-9d02-fbd465dd6bc2.png)

**Comment by arnauos** [comment]
Mira en los días anteriores, la información de datadis puede llevar 1 o 2 días de retraso según el día.

**Comment by lordraiden** [comment]
> Buenas, trato de responderte:
> 
> > ```
> > This error originated from a custom integration.
> > 
> > Logger: custom_components.edata.websockets
> > Source: custom_components/edata/websockets.py:34
> > Integration: edata (documentation, issues)
> > First occurred: 10:09:03 PM (13 occurrences)
> > Last logged: 10:15:19 PM
> > 
> > 'XXXX'
> > Traceback (most recent call last):
> >   File "/config/custom_components/edata/websockets.py", line 34, in websocket_get_maximeter
> >     connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('maximeter', []))
> > KeyError: 'XXXX'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > This error originated from a custom integration.
> > 
> > Logger: custom_components.edata.websockets
> > Source: custom_components/edata/websockets.py:25
> > Integration: edata (documentation, issues)
> > First occurred: 10:08:33 PM (48 occurrences)
> > Last logged: 10:15:19 PM
> > 
> > 'XXXX'
> > Traceback (most recent call last):
> >  File "/config/custom_components/edata/websockets.py", line 25, in websocket_get_monthly_data
> >    connection.send_result(msg["id"], hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_monthly_sum', []))
> > KeyError: 'XXXX'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> > This error originated from a custom integration.
> > 
> > Logger: custom_components.edata.websockets
> > Source: custom_components/edata/websockets.py:14
> > Integration: edata (documentation, issues)
> > First occurred: 10:06:31 PM (64 occurrences)
> > Last logged: 10:15:19 PM
> > 
> > 'XXXX'
> > Traceback (most recent call last):
> >  File "/config/custom_components/edata/websockets.py", line 14, in websocket_get_daily_data
> >    data = hass.data[DOMAIN][msg["scups"].upper()].get('consumptions_daily_sum', [])
> > KeyError: 'XXXX'
> > ```
> 
> Estos dos errores son por no haber configurado correctamente las tarjetas de apexcharts, hay que sustituir todos los XXXX por los 4 últimos caracteres de tu CUPS (más info en la documentación)
> 
> > ```
> > Logger: edata.connectors
> > Source: /usr/local/lib/python3.9/site-packages/edata/connectors.py:175
> > First occurred: 10:05:56 PM (1 occurrences)
> > Last logged: 10:05:56 PM
> > 
> > Connector: still missing the following consumption ranges [{'from': datetime.datetime(2020, 12, 1, 0, 0), 'to': datetime.datetime(2021, 5, 31, 0, 0)}, {'from': datetime.datetime(2021, 12, 17, 23, 0), 'to': datetime.datetime(2021, 12, 18, 23, 0)}, {'from': datetime.datetime(2021, 12, 29, 23, 0), 'to': datetime.datetime(2021, 12, 30, 22, 5, 10, 892482)}], will try again later
> > ```
> 
> Este error es cosa de Datadis, por algún motivo no te está "dando" esos rangos de datos, por lo que tendrás huecos en esos intervalos. La API de Datadis en algunos casos no te da los datos que le pides, y a veces se soluciona cambiando los rangos (haciéndolos más pequeños), pero en otros no. La integración trata de resolver estos huecos automáticamente en cada descarga, a veces no lo consigue, lo único que podemos hacer es esperar.

Cierto, gracias, lo sustituí en los nombres de los sensores pero no en la parte  del data generator. Ahora ya funciona.

**Comment by lordraiden** [comment]
> Mira en los días anteriores, la información de datadis puede llevar 1 o 2 días de retraso según el día.

Pues sí, yendo hacia atrás si tengo datos. Pues todo solucionado, muchas gracias a los 2 y disculpad que ha sido descuido mio los fallos.

**Comment by lordraiden** [comment]
Hay forma de obtener también los precios?
lo tengo configurado pero no me sale
![imagen](https://user-images.githubusercontent.com/17175395/147819747-d4da15d5-e2ee-4df3-b445-0a6e18ccabe6.png)
Uso el sensor de esta integración pero igual hay que tocar algo más
https://www.home-assistant.io/integrations/pvpc_hourly_pricing
![imagen](https://user-images.githubusercontent.com/17175395/147819786-cb639d13-e70e-4387-8ab0-2801b7d2f0c1.png)
![imagen](https://user-images.githubusercontent.com/17175395/147819832-ee868797-91bc-442c-b876-110b58c9f9ad.png)

**Comment by uvejota** [comment]
> Hay forma de obtener también los precios?
> lo tengo configurado pero no me sale
> ![imagen](https://user-images.githubusercontent.com/17175395/147819747-d4da15d5-e2ee-4df3-b445-0a6e18ccabe6.png)
> Uso el sensor de esta integración pero igual hay que tocar algo más
> https://www.home-assistant.io/integrations/pvpc_hourly_pricing
> ![imagen](https://user-images.githubusercontent.com/17175395/147819786-cb639d13-e70e-4387-8ab0-2801b7d2f0c1.png)
> ![imagen](https://user-images.githubusercontent.com/17175395/147819832-ee868797-91bc-442c-b876-110b58c9f9ad.png)

La verdad, yo tampoco soy capaz de ponerle el precio (ni siquiera el estático). No sé si alguien lo habrá conseguido. Puede ser un bug del propio HA (esto de inyectar estadísticas externas es reciente), o que necesito registrar los datos de otra forma (lo cual me parecería raro, ya que los muestra y contabiliza correctamente)
