### ISSUE TITLE
Consumo por horas

### ISSUE THREAD

**Issue by etatus** [uvejota/homeassistant-edata#51]
Buenas @uvejota, te había puesto esto en el issue del Roadmap, pero con tanta actividad igual se te pasó por alto...

¿Tienes pensado que la integración contemple el consumo por horas? En principio parece que datadis ofrece los datos por horas y me parece muy útil para conocer lo que pagamos por hora y compararlo con el PVPC para comprobar lo que hemos gastado en las franjas horarias más caras y más baratas. Yo lo he hecho de forma un poco rudimentaria para UFD (meto los valores de las 24 horas como un array en un atributo del sensor) y el coste correspondiente lo comparo con PVPC (sensor independiente) en una gráfica de apexcharts, pero estaría genial que lo contemplase tu integración.

![cost_hour](https://user-images.githubusercontent.com/7522061/147996195-bd7b16d7-5385-4a71-a4d8-a5c972fc0f0e.jpg)

![energy_sensor](https://user-images.githubusercontent.com/7522061/147996708-0f9e47aa-f092-491f-90ac-34e4f1d2d144.jpg)

**Comment by uvejota** [comment]
Buenas, el consumo por horas ya está de por sí implementado, pero no he añadido ninguna forma de leerla excepto desde el panel de energía.

Podría ponerlo de forma análoga a como lo hacemos para ver el diario y mensual, con websockets y el módulo data_generator de apexcharts-card.

**Comment by etatus** [comment]
Ah, pues es cierto, sí que me aparecen los consumos por hora en el panel de energía (hasta ahora no los había visto). La verdad es que si a mayores se puede leer el consumo por hora del sensor para visualizaciones personalizadas como comentas estaría genial.

Una cosa que hice en mi integración rudimentaria que igual te resulta también interesante es el cálculo del **gasto por hora** a partir del consumo horario de energía (kWh) y el PVPC horario del día correspondiente (€/kWh), que es algo que el panel de energía no da (el coste/hora). Me refiero a crear un sensor en tu integración que se llame **edata:xxxx_cost** con esa información (para poder visualizarlo con apexcharts y compararlo con el PVPC, tal como aparece en la gráfica de ejemplo que te puse arriba). Eso sí, necesitarías los datos históricos de PVPC...

En cualquier caso enhorabuena por tu gran trabajo y por ofrecernos esta fantástica integración!

**Comment by uvejota** [comment]
Las lecturas mediante websockets tienen un problemilla (al margen de la configuración, que es un poquito tediosa para el usuario), y es que en cada visualización del gráfico descarga todos los datos. Es por ese motivo que sólo muestro los últimos 30 días o los últimos 12 meses en lugar del histórico completo. Con las horas pasaría lo mismo, sólo podría mostrar los últimos 30 registros o así (o dejarlo configurable). Pero vamos, que si lo queréis no tiene mucho misterio :-) me lo apunto para la próxima release.

Sobre el coste, yo tenía pensado algo similar. La dificultad pasa por:
a) permitir al usuario elegir si quiere pvpc o tarificación fija,
b) permitir al usuario definir su tarificación fija (fijo por tramos?, o fijo todo el rato?)

Mi idea inicial era que el panel de energía se encargara de la tarificación y que cada usuario definiera el sensor de coste que le interesara, pero **no funciona**, y desconozco por qué (supongo que las estadísticas externas están en pañales y es un bug).

Tengo que darle una vuelta, a ver qué nos viene mejor.

**Comment by etatus** [comment]
Por lo que he podido averiguar, el coste del panel de energía lo calcula sobre el valor actual del sensor correspondiente y como en datadis tenemos datos del pasado, nunca va a dar valores correctos. Es decir, si hablamos de horas, al finalizar cada hora coge el valor del sensor de consumo kWh y lo multiplica por el valor del sensor de precio PVPC (€/kWh) y ese es el coste de esa hora. En el caso de días, pues lo mismo pero al finalizar el día, etc.  Por tanto, parece que el valor del coste se calcula en tiempo real cuando le pones un sensor con los precios.

Yo lo que he hecho es en lugar de elegir "Usar una entidad con el precio actual" (que sería el propio sensor de PVPC), elegir "Usar una entidad que realiza un seguimiento de los costes totales" porque en ese caso en teoría el panel de energía ya no tiene que calcular nada puesto que toma el valor del sensor que le pongas como coste asociado (a cada hora, día, etc...). Por eso si el cálculo lo hace tu integración y se registra mediante un sensor específico (**edata:xxx_cost**), el panel de energía ya no tendría que hacer los cálculos y entiendo que el histórico saldría bien. Si crear un sensor de costes que contemple todas las casuísticas es complicado, quizá se podría empezar por lo más común y ver que tal va la cosa.

![panel_energia](https://user-images.githubusercontent.com/7522061/148291500-a54b4805-33c2-4560-b22b-194a5082983f.jpg)

**Comment by uvejota** [comment]
> Por lo que he podido averiguar, el coste del panel de energía lo calcula sobre el valor actual del sensor correspondiente y como en datadis tenemos datos del pasado, nunca va a dar valores correctos. Es decir, si hablamos de horas, al finalizar cada hora coge el valor del sensor de consumo kWh y lo multiplica por el valor del sensor de precio PVPC (€/kWh) y ese es el coste de esa hora. En el caso de días, pues lo mismo pero al finalizar el día, etc. Por tanto, parece que el valor del coste se calcula en tiempo real cuando le pones un sensor con los precios.
> 
> Yo lo que he hecho es en lugar de elegir "Usar una entidad con el precio actual" (que sería el propio sensor de PVPC), elegir "Usar una entidad que realiza un seguimiento de los costes totales" porque en ese caso en teoría el panel de energía ya no tiene que calcular nada puesto que toma el valor del sensor que le pongas como coste asociado (a cada hora, día, etc...). Por eso si el cálculo lo hace tu integración y se registra mediante un sensor específico (**edata:xxx_cost**), el panel de energía ya no tendría que hacer los cálculos y entiendo que el histórico saldría bien. Si crear un sensor de costes que contemple todas las casuísticas es complicado, quizá se podría empezar por lo más común y ver que tal va la cosa.
> 
> ![panel_energia](https://user-images.githubusercontent.com/7522061/148291500-a54b4805-33c2-4560-b22b-194a5082983f.jpg)

Eso tiene sentido... tengo que hacer algunos cambios antes que aún tengo en curso, para no desarrollar esto 2 veces. Mi intención es aprovechar y que el usuario pueda personalizar su tarifa en la medida de lo posible, ya os iré informando.

**Comment by darguez** [comment]
Pues acabo de ver que ya está implementado en la última versión. O_O Buena funcionalidad @uvejota !!! Ahora ya podemos hacernos una idea de cuanto vamos gastando cada día a lo largo del mes antes de que lleguen las facturas ^_^

**Edito:** Acabo de leer que no se soporta PVPC, solo costes fijos metidos a mano :(

Que pena!! A ver si saco tiempo y creo una entidad de costes para PVPC basada en la integración de ESIOS que es bastante fiable.

**Comment by darguez** [comment]
De todas formas no entiendo por que sin haber habilitado los costes en la configuración de la integración, puedo elegir en el panel de energía la entidad edata_XXXXX p1 energy consumption y me aparece un coste en las gráficas...

![image](https://user-images.githubusercontent.com/96727000/188214491-16781f9d-437a-41ca-9839-5bcb59e17c8f.png)

![image](https://user-images.githubusercontent.com/96727000/188215226-21e5267f-48a2-4716-b989-c7638935d8fe.png)

![image](https://user-images.githubusercontent.com/96727000/188214966-ae46cce8-1b7d-4a25-9a6e-f6d91deb99a0.png)

**Comment by uvejota** [comment]
@darguez esos numeritos que salen son valores por defecto, hasta que no actives la casilla superior (que por cierto se me ha pasado ponerle etiqueta de texto...) no aplican.

Lo tienes mal configurado en cualquier caso, en el apartado "usar una entidad que realiza un seguimiento de los costes totales" hay que poner una estadística llamada edata_XXXX: cost ... que aparece un ratico después de activar la casilla superior de la que te hablo. Al poner la misma estadística edata:xxxx_px_consumption estás asumiendo que kwh=€ (por eso te sale 1€ el kwh :) ) 

Cierro ya que esto está resuelto (ya tenemos consumos por horas disponibles). Hacerlo disponible mediante apexcharts-card es más complicado (son 24 datos por día x N gráficas, si representamos 30 días son MUCHÍSIMOS datos y consultarlos con la técnica actual consumiría muchísimos recursos del navegador), tendría que intentar hablar con su desarrollador a ver si me hace un apaño :)
