### ISSUE TITLE
edata sensor problem

### ISSUE THREAD

**Issue by Ruta40Patagonia** [uvejota/homeassistant-edata#52]
Hello and happy 2022. After updating to the latest version HA 2021.12.7 the edata sensor disappeared and I receive the following error.
Logger: homeassistant.setup
Source: setup.py:291
First occurred: 13:22:36 (1 occurrences)
Last logged: 13:22:36
Unable to prepare setup for platform edata.sensor: Could not set up all dependencies.

I appreciate any help.

**Comment by uvejota** [comment]
Buenas, sugiero que actualices edata a su última versión (2021.12.2), ya que a mi no me da error y esa corregía algún problema de dependencias.

**Comment by Ruta40Patagonia** [comment]
Ante todo muchas gracias por tu pronta respuesta. perdón por el ingles de antes no me di cuenta.. Tengo instalada la versión de edata 2021.12.2 y funcionaba perfectamente hasta que realice la actualización de HA2021.12.6 a HA2021.12.7 y fue ahí cuando desapareció la entidad sensor.edata. Desinstale varias veces edata eliminando hasta el repositorio y reinstalando, pero sin suerte aun; además no veo información en el registro que me de una pista mas clara. Cualquier idea será bienvenida..
Saludos..

**Comment by uvejota** [comment]
¿Tienes restringido el recorder a algunas integraciones? Es la única nueva dependencia que he añadido (para inyectar las estadísticas en HA)

**Comment by Ruta40Patagonia** [comment]
Volví a la versión de edata 0.1.8 y funciono nuevamente.
Posteriormente de leer su respuesta, verifique y efectivamente tenia un problema con la configuración de MariaDB, solventado el problema volví a actualizar el complemento 2021.12.2 y funciona de nuevo, salvo los valores de los siguientes atributos:
yesterday_kWh: null
yesterday_hours: null
yesterday_p1_kWh: null
yesterday_p2_kWh: null
yesterday_p3_kWh: null
también los recibía null con la versión 0.1.8

**Comment by Ruta40Patagonia** [comment]
comente la linea (#experimental: false) y funciona todo perfecto...
Muchísimas Gracias por su ayuda... Gran Trabajo..
