### ISSUE TITLE
No funciona la UI con edata

### ISSUE THREAD

**Issue by jorgejs92** [uvejota/homeassistant-edata#59]
Al llegar al paso de instalación 4 (Configurarla mediante la UI de Home Assistant (buscar "edata" en Configuración > Dispositivos y servicios > Añadir integración)), no me sale esta integración. He instalado el repositorio en HACS e instalado desde alli.

**Comment by uvejota** [comment]
La UI sólo está disponible en rama dev de momento. Perdón por haber borrado la documentación anterior, la he vuelto a hacer disponible en: 

https://github.com/uvejota/homeassistant-edata/wiki/Instalaci%C3%B3n
