### ISSUE TITLE
Integración de sensores a partir de atributos

### ISSUE THREAD

**Issue by emiguerol** [uvejota/homeassistant-edata#6]
Hola a todos,

Desconozco si hay una mejor forma, pero es lo que se me ha ocurrido para poder hacer operaciones con los atributos (seguro que hay otra forma)

1- Integramos edata
2- Leemos el sensor desde Nodered (recuerda que tu sensor tendrá diferente  los 4 últimos dígitos, reemplaza xb0f por el tuyo)
3- Añadimos el nodo función, convirtiendo los datos de string a número
[imagen1](https://imgur.com/cHJw4Le)
4- Añadimos otro nodo función, en este caso para realizar los cálculos de la factura. Modificar los costes en función de la necesidad
[Imagen2](https://imgur.com/Fu6UTJk)

Queda el flow tal que así
[imagen3](https://imgur.com/IZ88aIn)

Para crear los sensores es necesaria la integración de hacs Nodered Companion (https://github.com/zachowj/hass-node-red)

La configuración del nodo es la siguiente,

[imagen4](https://imgur.com/GfGNsCD)
[imagen5](https://imgur.com/nYCoT6o)

Dejo el flow 

`[{"id":"e038fe05.fe40b","type":"tab","label":"Consumos","disabled":false,"info":""},{"id":"5b715dc5e046b717","type":"api-current-state","z":"e038fe05.fe40b","name":"","server":"90696abf.b46218","version":2,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"sensor.edata_xb0f","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"},{"property":"data","propertyType":"msg","value":"","valueType":"entity"}],"override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":180,"y":100,"wires":[["db24a9120489d13d"]]},{"id":"f280f37652202b8f","type":"inject","z":"e038fe05.fe40b","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"00 07 * * *","once":false,"onceDelay":0.1,"topic":"","payloadType":"date","x":130,"y":120,"wires":[["5b715dc5e046b717"]]},{"id":"db24a9120489d13d","type":"function","z":"e038fe05.fe40b","name":"","func":"consumos={};\nconsumos.consumo_total_ayer=parseFloat(msg.data.attributes.yesterday_kWh);\nconsumos.consumo_ayer_punta=parseFloat(msg.data.attributes.yesterday_p1_kWh);\nconsumos.consumo_ayer_llano=parseFloat(msg.data.attributes.yesterday_p2_kWh);\nconsumos.consumo_ayer_valle=parseFloat(msg.data.attributes.yesterday_p3_kWh);\nconsumos.consumo_mes_en_curso=parseFloat(msg.data.attributes.month_kWh);\nconsumos.dias_mes_en_curso=parseFloat(msg.data.attributes.month_days);\nconsumos.consumo_mes_en_curso_punta=parseFloat(msg.data.attributes.month_p1_kWh);\nconsumos.consumo_mes_en_curso_llano=parseFloat(msg.data.attributes.month_p2_kWh);\nconsumos.consumo_mes_en_curso_valle=parseFloat(msg.data.attributes.month_p3_kWh);\nconsumos.consumo_mes_anterior=parseFloat(msg.data.attributes.last_month_kWh);\nconsumos.consumo_mes_anterior_punta=parseFloat(msg.data.attributes.last_month_p1_kWh);\nconsumos.consumo_mes_anterior_llano=parseFloat(msg.data.attributes.last_month_p2_kWh);\nconsumos.consumo_mes_anterior_valle=parseFloat(msg.data.attributes.last_month_p3_kWh);\n\n\n\nmsg.payload=consumos;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":120,"y":260,"wires":[["1d3849cf9e7813f0","0d6454e43e1b2306","b36efda904be5d59","9014294d3be0b05a","a9dc4c09e525cfbb","af0570bd8239ae3a","487e982342c0a3cd","eb487fe01f012fa3","3c9ef939ad867b1a","4e4573b331ac657a","1ed11fba74fe84cc","2b506683d9a2c946","e5133fa702440a9d"]]},{"id":"1d3849cf9e7813f0","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo Ayer","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_total_ayer"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_total_ayer","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_total_ayer","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":480,"y":120,"wires":[[]]},{"id":"0d6454e43e1b2306","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo Ayer Punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_ayer_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_ayer_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_ayer_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":500,"y":180,"wires":[[]]},{"id":"b36efda904be5d59","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo Ayer Llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_ayer_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_ayer_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_ayer_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":500,"y":240,"wires":[[]]},{"id":"9014294d3be0b05a","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo Ayer valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_ayer_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_ayer_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_ayer_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":500,"y":300,"wires":[[]]},{"id":"a9dc4c09e525cfbb","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes en curso","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_en_curso"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_en_curso","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_en_curso","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":510,"y":360,"wires":[[]]},{"id":"af0570bd8239ae3a","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes en curso punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_en_curso_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_en_curso_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_en_curso_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":530,"y":420,"wires":[[]]},{"id":"487e982342c0a3cd","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes en curso llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_en_curso_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_en_curso_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_en_curso_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":520,"y":480,"wires":[[]]},{"id":"eb487fe01f012fa3","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes en curso valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_en_curso_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_en_curso_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_en_curso_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":520,"y":540,"wires":[[]]},{"id":"3c9ef939ad867b1a","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes anterior","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_anterior"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_anterior","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_anterior","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":500,"y":600,"wires":[[]]},{"id":"1ed11fba74fe84cc","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes anterior punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_anterior_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_anterior_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_anterior_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":520,"y":660,"wires":[[]]},{"id":"4e4573b331ac657a","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes anterior llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_anterior_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_anterior_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_anterior_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":520,"y":720,"wires":[[]]},{"id":"2b506683d9a2c946","type":"ha-entity","z":"e038fe05.fe40b","name":"Consumo mes anterior valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"consumo_mes_anterior_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:flashcircle"},{"property":"unit_of_measurement","value":"kWh"}],"state":"payload.consumo_mes_anterior_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"consumo_mes_anterior_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":520,"y":780,"wires":[[]]},{"id":"e5133fa702440a9d","type":"function","z":"e038fe05.fe40b","name":"","func":"factura={};\nfactura.factura_ayer_valle=msg.payload.consumo_ayer_valle*0.11;\nfactura.factura_ayer_llano=msg.payload.consumo_ayer_llano*0.15;\nfactura.factura_ayer_punta=msg.payload.consumo_ayer_punta*0.24;\nfactura.factura_ayer_total=factura.factura_ayer_valle+factura.factura_ayer_llano+factura.factura_ayer_punta;\nfactura.factura_mes_valle=msg.payload.consumo_mes_en_curso_valle*0.11;\nfactura.factura_mes_llano=msg.payload.consumo_mes_en_curso_llano*0.15;\nfactura.factura_mes_punta=msg.payload.consumo_mes_en_curso_punta*0.24;\nfactura.factura_mes_total=factura.factura_mes_valle+factura.factura_mes_llano+factura.factura_mes_punta;\nfactura.factura_mes_anterior_valle=msg.payload.consumo_mes_anterior_valle*0.11;\nfactura.factura_mes_anterior_llano=msg.payload.consumo_mes_anterior_llano*0.15;\nfactura.factura_mes_anterior_punta=msg.payload.consumo_mes_anterior_punta*0.24;\nfactura.factura_mes_anterior_total=factura.factura_mes_anterior_valle+factura.factura_mes_anterior_llano+factura.factura_mes_anterior_punta;\n\n\nmsg.payload=factura;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":460,"y":80,"wires":[["0cb03ceab9d961aa","90a8cd3db0060f36","70c028fe61398c7f","405588eaa12472e3","ad38571d5cdd19fe","fdf74335d2a754f1","7cb0b5cd2c01de20","0e1d9a16ae7f40ba","f01583bd0e248d79","4223b53f38ed4011","67fd1319b28a720c","50e18bd82a2d047f"]]},{"id":"0cb03ceab9d961aa","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura Ayer valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_ayer_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_ayer_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_ayer_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":80,"wires":[[]]},{"id":"90a8cd3db0060f36","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura Ayer llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_ayer_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_ayer_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_ayer_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":120,"wires":[[]]},{"id":"70c028fe61398c7f","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura Ayer total","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_ayer_total"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_ayer_total","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_ayer_total","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":160,"wires":[[]]},{"id":"ad38571d5cdd19fe","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":240,"wires":[[]]},{"id":"fdf74335d2a754f1","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":280,"wires":[[]]},{"id":"7cb0b5cd2c01de20","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":320,"wires":[[]]},{"id":"405588eaa12472e3","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura Ayer punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_ayer_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_ayer_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_ayer_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":200,"wires":[[]]},{"id":"0e1d9a16ae7f40ba","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes total","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_total"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_total","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_total","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":770,"y":360,"wires":[[]]},{"id":"f01583bd0e248d79","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes anterior valle","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_anterior_valle"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_anterior_valle","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_anterior_valle","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":790,"y":400,"wires":[[]]},{"id":"4223b53f38ed4011","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes anterior llano","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_anterior_llano"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_anterior_llano","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_anterior_llano","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":790,"y":440,"wires":[[]]},{"id":"67fd1319b28a720c","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes anterior punta","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_anterior_punta"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_anterior_punta","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_anterior_punta","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":800,"y":480,"wires":[[]]},{"id":"50e18bd82a2d047f","type":"ha-entity","z":"e038fe05.fe40b","name":"Factura mes anterior total","server":"90696abf.b46218","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"factura_mes_anterior_total"},{"property":"device_class","value":"sensor"},{"property":"icon","value":"mdi:FlashCircle"},{"property":"unit_of_measurement","value":"€"}],"state":"payload.factura_mes_anterior_total","stateType":"msg","attributes":[{"property":"entity_id","value":"factura_mes_anterior_total","valueType":"str"}],"resend":true,"outputLocation":"","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":false,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":790,"y":520,"wires":[[]]},{"id":"90696abf.b46218","type":"server","name":"Home Assistant","version":1,"legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true}]`

**Comment by uvejota** [comment]
> 

Con tu permiso, voy a ponerlo en la wiki y cierro este hilo :-)

> Hola,
> 
> Yo lo he conseguido utilizando esto:
> 
> ```
> sensor:
>   - platform: template
>     sensors:
>       last_month_consumption:
>         friendly_name: "Consumo mes anterior"
>         value_template: >-
>            {{ state_attr('sensor.edata_xxxx', 'last_month_kWh') | float }}
>         unit_of_measurement: kWh
> ```
