### ISSUE TITLE
Problema con la actualización 2021.12.8 del Core

### ISSUE THREAD

**Issue by gusmori** [uvejota/homeassistant-edata#60]
Cuando paso el Check Home Assistant configuration me sale el error:
Failed config
  General Errors: 
    - Platform error sensor.edata - No module named 'aiopvpc'
He probado con experimental: false y también con true, y me da el mismo error en ambos caso.
¿Cómo lo puedo solucionar?
Un saludo y gracias por adelantado.

**Comment by aexpositog** [comment]
Hola, a mi me pasa exactamente lo mismo. Al pasar el Check Home Assistant me aparece el mensaje:
- Platform error sensor.edata - No module named 'aiopvpc'
Gracias y un saludo.

**Comment by uvejota** [comment]
Curioso, voy a ver...

**Comment by uvejota** [comment]
Probad con la nueva release:

https://github.com/uvejota/homeassistant-edata/releases/tag/2022.01.0

**Comment by gusmori** [comment]
Perfecto! Con la 2022.01.0 ya no da ese error. Gracias.
