### ISSUE TITLE
Cuestiones Varias

### ISSUE THREAD

**Issue by jorgejs92** [uvejota/homeassistant-edata#61]
Le iba a preguntar un par de cuestiones

1. ¿El tiempo de actualización se puede saber o depende de Datadis? Es curioso que he reiniciado la Raspberry hoy y se me ha actualizado, pero no se si ha sido casualidad o que al reiniciar a hecho una nueva petición.
2. He incluido las cards de "Mes en Curso" y "Mes Anterior" pero los atributos de month_pvpc_€ y last_month_pvpc_€ no me funcionan (no aparecen en el informe con los diversos atributos)

**Comment by uvejota** [comment]
> Le iba a preguntar un par de cuestiones
> 
> 1. ¿El tiempo de actualización se puede saber o depende de Datadis? Es curioso que he reiniciado la Raspberry hoy y se me ha actualizado, pero no se si ha sido casualidad o que al reiniciar a hecho una nueva petición.

Los datos se intentan actualizar cada hora, aunque Datadis lo hace cada 24 aproximadamente. Si reinicias la integración fuerzas la actualización.

> 2. He incluido las cards de "Mes en Curso" y "Mes Anterior" pero los atributos de month_pvpc_€ y last_month_pvpc_€ no me funcionan (no aparecen en el informe con los diversos atributos)

Esos dos atributos están deshabilitados de momento, hasta que dé con una solución al problema.
