### ISSUE TITLE
Mensaje de error al añadir Repositorio

### ISSUE THREAD

**Issue by Truman78es** [uvejota/homeassistant-edata#62]
Buenas a todos.
Soy un newbie en Home Assistant que esta intentando configurar y personalizar su reciente instalación. He intentado añadir el repositorio a la tienda de complementos para así poder realizar la instalación de la integración, pero me aparece el mensaje de fallo _"Invalid Add-on repository!"_ al intentar añadirlo.

La instalación la he hecho a través de Docker en un Synology DS1515+ y las versiones de mi instalación son:

Versión CORE: **core-2021.12.8**
Versión SUPEVISOR: **supervisor-2022.01.dev0503**

Y este es el Log tras intentar la instalación:

> 22-01-09 15:52:20 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/uvejota/homeassistant-edata repository
22-01-09 15:52:21 ERROR (MainThread) [supervisor.store] https://github.com/uvejota/homeassistant-edata is not a valid add-on repository
22-01-09 15:52:21 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / 2375904b
22-01-09 15:52:21 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / 2375904b
22-01-09 15:52:22 WARNING (SyncWorker_5) [supervisor.store.data] No repository information exists at /data/addons/git/2375904b
22-01-09 15:52:22 INFO (MainThread) [supervisor.store] Loading add-ons from store: 63 all - 0 new - 0 remove
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: 2375904b
22-01-09 15:52:22 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/uvejota/homeassistant-edata
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-01-09 15:52:22 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete

Mis conocimientos son muy justitos, así que espero que me podáis echar una mano...

**Comment by uvejota** [comment]
Buenas, hay que añadirlo en la tienda de integraciones HACS (no oficial), creo que lo estás haciendo en los Add-Ons nativos de HA y por eso da error.

Si no tienes instalado HACS, tendrás que hacerlo primero (en su web hay unas instrucciones bastante decentes :-)

**Comment by Truman78es** [comment]
> Buenas, hay que añadirlo en la tienda de integraciones HACS (no oficial), creo que lo estás haciendo en los Add-Ons nativos de HA y por eso da error.
> 
> Si no tienes instalado HACS, tendrás que hacerlo primero (en su web hay unas instrucciones bastante decentes :-)

Ok, gracias.
He tardado toda la tarde en conseguir instalar HACS en Docker, pero por fin lo he conseguido (dichoso NAS). 
Como mañana me toca madrugar para el curro, me toca esperar hasta por la tarde para ponerme con la configuracion y el registro en DATADIS. 

Muchas gracias por la ayuda.
