### ISSUE TITLE
No actualiza datos desde el 01/01

### ISSUE THREAD

**Issue by jespadas69** [uvejota/homeassistant-edata#65]
En primer lugar, felicitaros por tan fantástico trabajo, muy agradecido, seguir así por favor, No se si estará comentado en otro sitio pero desde el 01/01/2022 no me actualiza los datos y parece todo normal, ¿sabeis a que se puede deber? os adjunto pantallazo, como podréis ver hay varios items que no tienen datos tampoco, un millon de gracias
![informe](https://user-images.githubusercontent.com/76209877/149653414-9d093067-be4f-47d1-883c-fa6f5878be54.jpg)

**Comment by uvejota** [comment]
Buenas, ¿En Datadis sale algún dato más reciente?

**Comment by Siroguh** [comment]
Estoy teniendo el mismo problema, y Datadis no parece estar aportando los datos. Yo tengo el problema desde el día 12 de diciembre. Mi comercializadora, creo, también hace uso de la API o de Datadis o de Endesa para darme los datos en su propia aplicación. ¿Tal vez han cerrado el acceso desde Endesa o desde Datadis, por exceso de requests? El acceso a Datadis lo solicite cerca de el 20 de Dic, asi que no creo que sea esto que comento. En cualquier caso no sé como se mira si me han cerrado o no el acceso así que estoy indefenso.

Actualizo: Comprobando fechas de mi contrato nuevo de luz en diciembre estoy viendo que coinciden las fechas de el último registro y de la nueva comercializadora, así que ha de ser cosa suya.

**Comment by jespadas69** [comment]
En Eredes que es desde tomal los datos en mi caso Datadis, si que hay datos
![EREDES CONSUMOS](https://user-images.githubusercontent.com/76209877/149835382-a48a6408-a68e-4e8e-8cff-874b38429569.jpg)
:

**Comment by uvejota** [comment]
Si los datos no aparecen en datadis, no hay nada que hacer. No creo que sea ningún tipo de baneo, más bien desidia o algún error por parte de los proveedores, usamos la api que ofrecen, y se solicitan los datos incrementales 1 vez cada hora, creo que es razonable.

Yo esperaría, a veces las distribuidoras se duermen y algún día espabilan.
