### ISSUE TITLE
Cambios el los atributos

### ISSUE THREAD

**Issue by SmilinStanSStanman** [uvejota/homeassistant-edata#67]
Hola,

Tengo actualizada la integracion a la version 2022.01.0 y me he dado cuenta de que en las apexcharts no me aparecen los costes en euros de los consumos en pvpc.
Mirando en detalle los atributos del sensor de edata he visto estos cambios:

Aparecen los siguientes atributos que no están listados en la wiki de la integración:
Yesterday hours
Last registered kWh date

No me aparecen los siguientes atributos (por eso no me salen los importes en PVPC):
month_pvpc_€
last_month_pvpc_€

¿Es algo previsto y/o conocido, o es problema mío? Tenía creados sensores que se calculaban mediante los valores de los atributos de la integración, para calcular con ellos la factura completa en mi contrato de mercado libre. Y con el precio en pvpc que me calculaba edata veía a tiempo real como de ventajoso era el contrato vigente con respecto al PVPC. Molaba :(

**Comment by uvejota** [comment]
Buenas, es conocido y lo corregiré en cuanto pueda. Tienes más info en https://github.com/uvejota/homeassistant-edata/issues/41

Un saludo
