### ISSUE TITLE
Obtener historico de más de 30 días

### ISSUE THREAD

**Issue by SirMartin** [uvejota/homeassistant-edata#7]
Hola @uvejota, muchas gracias por tu genial trabajo.

He estado probando las gráficas que has incluido como ejemplos, y he estado intentando toquitear y ver más datos a pasado, pero he visto que es imposible, y cotilleando un poco el código, he visto que en la librería fuente de python que has creado ([https://github.com/uvejota/python-edata/](https://github.com/uvejota/python-edata/)) tenies _hardcoded_ por defecto 30 días, no se si he visto correctamente o he mirado el método correcto, porque he mirado en la web, y yo de python justito, pero tienes idea de cambiar esto a futuro? ¿Te has encontrado alguna limitación de datadis al respecto y por eso lo has puesto?

Un saludo.

**Comment by uvejota** [comment]
Hola, más o menos: 

En el paquete e-data se descargan todos los datos del último año natural, y están disponibles para homeassistant por horas. Luego agrupo los datos diarios del último mes, y los mensuales del último año para las gráficas de apexcharts-card.

Por poder, no hay ningún problema en agrupar los datos de todo el histórico, pero consideré que para las gráficas con apexcharts igual añadir más de 30 valores podría llegar a ralentizar la interfaz, ya que los datos se consultan mediante websockets. Podría hacerlo configurable si así lo quieres.

Mi intención futura es facilitaros la lectura de todos los datos mediante llamadas REST a direcciones del tipo `homeassistant.local/api/edata/consumptions?from=xxx&to=yyy&group_by=zzz` pero ahora mismo, que el estado de la integración es bastante preliminar, lo tengo aparcado :-)

**Comment by SirMartin** [comment]
Si se puede hacer configurable de alguna manera para que sea desde las propias tarjetas (gráfico o lo que sea) la que marque la cantidad de días, aunque tengas el 30 por defecto, sería lo ideal.

**Comment by uvejota** [comment]
En la nueva versión (2021.12.1) estoy probando la integración con la plataforma de energía (inyectando 1 año de datos), creo que puede servirte :-) (aún en pruebas!)

Lo de añadirlo a apexcharts-cards estoy esperando a que implementen una funcionalidad en concreto, con el paradigma actual si añadimos más granularidad de datos, se ralentiza mucho y se cuelga.
