### ISSUE TITLE
No descarga datos de consumo

### ISSUE THREAD

**Issue by thejako** [uvejota/homeassistant-edata#71]
Buenas, tengo la integración instalada (ultima versión) y funcionando en mi HA (ultima versión), el sensor es visible, veo el CUPS, descarga algunos datos (potencias, potencia máxima alcanzada, fechas...) pero no descarga ni un dato de consumos. Desde Datadis si puedo verlos, aunque va SUPER LENTO y a veces da error, pero supongo que es lo normal. Mi distribuidora es UFD.

Por si ayuda, Datadis me muestra 2 CUPS (si, he introducido el correcto).

![image](https://user-images.githubusercontent.com/2477388/150314949-f528bbb9-7a69-41d9-85b7-d2cb203c4330.png)

Cualquier info adicional que se necesite, aquí estoy :)

Mil gracias!!

**Comment by uvejota** [comment]
Buenas, ¿Dice algo el log de HA (`Configuración > Registros`)? 

Lo más probable es que sea un error de Datadis y simplemente tengas que esperar, cada hora se reintenta :-)

**Comment by thejako** [comment]
Lo acabo de comprobar de nuevo, tienes razón!!! ha debido haber un error en el momento de la lectura y un rato (largo) despues se ha actualizado.

Lo cierto! Mil gracias por tu trabajo!
