### ISSUE TITLE
No actualiza atributos

### ISSUE THREAD

**Issue by miguelmoreau** [uvejota/homeassistant-edata#74]
Hola,
Primero dar las gracias por la contribucion de la integracion.

No se donde esta el error, Lo intale sobre Noviembre y funciono y al poco tiempo dejo de fincionar, no actualiza. El sensor esta creado, coge el CUPS pero no actualiza los atributos
![Screenshot1](https://user-images.githubusercontent.com/90466852/150582274-1a48a9ed-c1a5-4ac0-9b9d-5e85a46bd60b.jpg)
La integracion la tengo actualizada.
Y en la web de datadis si veo los datos
Alguna ideal
![Screenshot_2](https://user-images.githubusercontent.com/90466852/150582480-8c82debf-30f2-40ed-9ee9-cd250d288e7e.jpg)

**Comment by uvejota** [comment]
Buenas, prueba a renombrar el fichero `/config/.storage/edata.storage_XXXX` a cualquier otro nombre (por si hay que restaurarlo más adelante) y volverás a descargar todos los datos, a ver si así se resuelve (tardará un ratín).

**Comment by miguelmoreau** [comment]
Lo acabo de hacer y me ha desaparecido todos los datos incluido el cups. Me ha creado el archivo nuevo y el sensor esta operativo.

He comprobado cel configurator.yaml y los datos estan correctos, usuario y contraseña y el cups copiado de Datadis.

**Comment by lobolobo** [comment]
Buenas.
A mi desde el día 17 de enero de 2022 me ha dejado de actualizar datos de buenas a primeras.

**Comment by alexsalvo1** [comment]
A mi me pasa algo similar. Para que funcione de nuevo voy a borrare el fichero en la carpeta .storage y reinicio HA. El solo reinicio no funciona! Creo que hay algo que se queda atascado...

**Comment by uvejota** [comment]
Umm... supongo que el log de HA no dice nada.

¿Podéis pegarme el contenido del `supplies` y `contracts` anonimizado (dentro del fichero de la carpeta `.storage`)?

A ver si se me ocurre algo. En cualquier caso, me parece extraño que borrando el fichero y reiniciando no se recupere. Es posible que vuestra comercializadora haya cambiado algún dato de forma extraña.

**Comment by lobolobo** [comment]
Buenas, por si sirve de ayuda. He visto que tenía una actualización de HA de Home Assistant OS 7.1 a Home Assistant OS 7.2. La he realizado y al rearancar HA, DATADIS se ha puesto al día sin hacer nada más (salvo los datos de ayer que supongo, aun no estarán disponibles en DATADIS hasta dentro de unas horas).

Una vez más, muchas gracias por la respuesta y por la integración @uvejota

**Comment by miguelmoreau** [comment]
Ahora me aparece asi:
"supplies": [],
        "contracts": [],
Antes (elimino cups y direccion:
"supplies": [
            {
                "cups": "ESXXXXXXXXXX79MY",
                "date_start": "1970-01-01T00:00:00",
                "date_end": "2021-11-20T00:00:00",
                "address": "XXXXXXXXXXX",
                "postal_code": "2003",
                "province": "2",
                "municipality": "003",
                "distributor": "I-DE REDES EL\u00c3\u0089CTRICAS INTELIGENTES, S.A.U.",
                "pointType": 5,
                "distributorCode": "8"
            }
        ],
        "contracts": [
            {
                "date_start": "2021-05-31T00:00:00",
                "date_end": "2021-11-20T00:00:00",
                "marketer": "CURENERGIA S.L.U.",
                "distributorCode": "8",
                "power_p1": 3.3,
                "power_p2": 3.3
            }
        ],

**Comment by uvejota** [comment]
> Ahora me aparece asi: "supplies": [], "contracts": [], Antes (elimino cups y direccion: "supplies": [ { "cups": "ESXXXXXXXXXX79MY", "date_start": "1970-01-01T00:00:00", "date_end": "2021-11-20T00:00:00", "address": "XXXXXXXXXXX", "postal_code": "2003", "province": "2", "municipality": "003", "distributor": "I-DE REDES EL\u00c3\u0089CTRICAS INTELIGENTES, S.A.U.", "pointType": 5, "distributorCode": "8" } ], "contracts": [ { "date_start": "2021-05-31T00:00:00", "date_end": "2021-11-20T00:00:00", "marketer": "CURENERGIA S.L.U.", "distributorCode": "8", "power_p1": 3.3, "power_p2": 3.3 } ],

Mmm... ¿tu comercializadora suele estimarte consumos?

**Comment by miguelmoreau** [comment]
Lo acabo de comprobar y son lecturas reales.

Si reinstalo la integracion??

**Comment by miguelmoreau** [comment]
Algo ha pasado que eliminando la integracion y reiniciando se ha solucionado,

Me queda que salgan datos de consumo de ayer y el precio pvpc

**Comment by acenjes** [comment]
Ante todo gracias por la integración, pero me ocurre lo mismo. Lo instalé hace unos días y ha dejado de actualizar los datos. Tengo dos integraciones de dos pisos distintos con diferentes compañías y ninguno de los dos me actualiza. Ayer borré los archivos /config/.storage/edata.storage_XXXX y me vuelven salir datos no actualizados.

**Comment by enriquemp** [comment]
Me ocurre lo mismo. Lo configuré todo la semana pasada, siguiendo todos los pasos, modificando los dígitos XXXX por los 4 últimos del CUPS, etc., pero no actualiza los valores, está todo a "none"

**Comment by cho0p** [comment]
First of all thank you for this integration!

Unfortunately I don't speak Spanish but I have the same issue. It stopped working without any log entries or visible issues.

![image](https://user-images.githubusercontent.com/42189739/155998387-90627b71-eb0e-41f1-837c-cd18f4cf7c04.png)

![image](https://user-images.githubusercontent.com/42189739/155998501-0bfd8af5-9c16-4d66-bd3c-da30d26a3ed4.png)

**Comment by gusmori** [comment]
Hola.
A mí me dejó de actualizar el 22 de febrero. 
Renombré el archivo del .storage y ya ha cargado los datos de febrero y algo de enero pero los anteriores no los carga.
Un saludo y gracias.

![image](https://user-images.githubusercontent.com/65916964/156580880-06346853-ba79-4594-9fd5-e687f2c071bf.png)

**Comment by acenjes** [comment]
A mí ya me actualiza correctamente.

**Comment by dagna1001** [comment]
Gracias por el aporte, pero como indican otros compañeros, no recarga los datos.

Lleva desde el 28 de marzo sin actualizarme los datos. Yo reinicio mi HASS ahora, y al reiniciar, me renueva los datos. Pero solo los renueva si reinicio.

Tengo otro HASS en casa de mi hermano, y tiene los datos sin actualizar desde el día 27 de marzo, casualmente el tiempo que lleva sin reiniciar su HASS.

¿Hay alguna manera de crear un servicio para forzar el que vuelva a pedir los datos o algo?

**Comment by arnauos** [comment]
Yo os diria que es normal, teneis que entrar en Datadis y confirmar hasta que dia teneis ya datos. Yo tengo dos suministros, de uno tengo hasta el 29 y de otro hasta el 27. Los datos en datadis suelen tener siempre un decalaje de unos días (a veces hasta una semana he llegado a ver).

**Comment by lobolobo** [comment]
> Gracias por el aporte, pero como indican otros compañeros, no recarga los datos.
> 
> Lleva desde el 28 de marzo sin actualizarme los datos. Yo reinicio mi HASS ahora, y al reiniciar, me renueva los datos. Pero solo los renueva si reinicio.
> 
> Tengo otro HASS en casa de mi hermano, y tiene los datos sin actualizar desde el día 27 de marzo, casualmente el tiempo que lleva sin reiniciar su HASS.
> 
> ¿Hay alguna manera de crear un servicio para forzar el que vuelva a pedir los datos o algo?

Me pasa exactamente lo mismo. Yo no creo que sea el decalaje de DATADIS pq al reiniciar Home Assistant se actualizan los datos al instante y hasta el siguiente reinicio no actualiza nada.

**Comment by jordicb** [comment]
Lo mismo, solo se actualizan los datos al reiniciar

**Comment by marc86lavergne** [comment]
Me pasa lo mismo. Alguna manera de crear una automatización para actualizar sin reiniciar?

**Comment by lobolobo** [comment]
Buenos días, ¿os actualiza al reiniciar? A mi ya ni eso. Con la nueva versión de HA 2022.4.0. No se si será mi sistema o la integración.

El LOG de HA me dice estas cosillas sobre EDATA:

Logger: custom_components.edata.sensor
Source: custom_components/edata/sensor.py:86
Integration: Integración edata ([documentation](https://github.com/uvejota/homeassistant-edata/), [issues](https://github.com/uvejota/homeassistant-edata/issues))
First occurred: 09:06:27 (3 occurrences)
Last logged: 14:10:00

Loading edata sensor via platform setup is deprecated. It will be imported into Home Assistant integration. Please remove it from your configuration

---------------------------------------------------------------------------

Logger: custom_components.edata.sensor
Source: helpers/config_validation.py:820
Integration: Integración edata ([documentation](https://github.com/uvejota/homeassistant-edata/), [issues](https://github.com/uvejota/homeassistant-edata/issues))
First occurred: 09:06:27 (12 occurrences)
Last logged: 14:10:00

The 'username' option near /config/sensors.yaml:671 is deprecated, please remove it from your configuration
The 'password' option near /config/sensors.yaml:671 is deprecated, please remove it from your configuration
The 'cups' option near /config/sensors.yaml:671 is deprecated, please remove it from your configuration
The 'experimental' option near /config/sensors.yaml:671 is deprecated, please remove it from your configuration
