### ISSUE TITLE
Datos negativos

### ISSUE THREAD

**Issue by alexsalvo1** [uvejota/homeassistant-edata#75]
En los ultimos dos dias tengo datos de consumos negativos. Este problema fue corrigido en la version 2021.12.2 pero parece que esta pasando de nuevo.

![Screenshot 2022-01-26 at 12 45 19](https://user-images.githubusercontent.com/3429643/151157948-d2d3c2aa-ddb6-4149-916f-3bde46e46f8c.png)
.

**Comment by uvejota** [comment]
La versión 2022.09.1 (aún beta) identifica estos problemas y lo resuelve automáticamente. Además incluye un servicio manual de restauración de estos datos (edata.recreate_statistics).
