### ISSUE TITLE
Gráficos sin cotes económico (atributos month_pvpc_€ y last_month_pvpc_€)

### ISSUE THREAD

**Issue by vtb77** [uvejota/homeassistant-edata#76]
Hola:

Encuentro esta funcionalidad muy útil, gracias.

He visto que una vez he creado el sensor, los datos económicos no aparece.

He revisado el sensor y los siguientes atributos no aparecen:

> - month_pvpc_€
> - last_month_pvpc_€

¿Qué estoy haciendo mal? Gracias.

Saludos.

**Comment by josvic001** [comment]
Me pasa exactamente lo mismo

**Comment by alienboyxp** [comment]
En mi caso lo mismo

**Comment by Nextric** [comment]
Tengo el mismo problema. :(

**Comment by mvila1992** [comment]
Hola, en el Roadmap #41 indica por qué están desactivados los datos económicos en gráficos. un saludo,

**Comment by 50l3r** [comment]
Existe alguna manera altenativa de sacar el dato?

**Comment by uvejota** [comment]
Esto está difícil de conseguir a día de hoy, antes usaba otra librería (aiopvpc) para leer estos datos, pero cambió de versión y se me ha vuelto tedioso de integrar (lógico, no estaba pensada para el propósito que usamos aquí). Parece ser además que la API de ESIOS tiene ciertas restricciones...

No lo descarto en un futuro, pero de momento hay otras cosas más estructurales que resolver aquí: hay mucha gente a la que no le funciona, a otros les aparecen huecos, algunos warnings inoportunos, cambios en HA que están aquí cogiditos con pinzas...
