### ISSUE TITLE
Añadir CUPS autorizado pero no propio

### ISSUE THREAD

**Issue by diamant-x** [uvejota/homeassistant-edata#79]
Hola,

Gracias por la integración. Estoy intentando agregar un CUPS al cual se me ha autotizado en datadis (ya que el contrato no está a mi nombre). Puedo ver el CUPS y sus datos en Datadis correctamente, pero en HA me aparece la entidad pero el atributo CUPS no está rellenado (ni el resto tampoco).

- ¿Podría confirmar si la integración soporta leer la información de CUPS autorizados?
- Si no, ¿podría considerarse para el Roadmap?

Gracias.
Un saludo.

**Comment by abetancort** [comment]
Yo también estoy en tu misma situación. El contrato esta a nombre de mi casero pero me ha autorizado y puedo acceder al CUPS desde DATADIS.  En la documentación de las APIs indica que para ver un suministro autorizado hay que añadir al GET el NIF del que nos autoriza (authorizedNif).

Supongo que aun no esta implementado.

**Comment by uvejota** [comment]
Voy a tratar de implementar esto

**Comment by uvejota** [comment]
En la versión 2022.09.1 (aún beta) está implementado esto sin probarlo (suerte!).

En la configuración mediante UI hay un campo para meter el authorized nif.

Ya me diréis :)

**Comment by abetancort** [comment]
Gracias voy a probarlo. Y te digo como me va.

**Comment by abetancort** [comment]
Probado, me he instalado la rama de desarrollo y aparentemente ha recuperado los datos de contrato y potencias máximas. 

La descarga de datos de consumo es otra cosa, es va lenta, lenta que no puede más.  Dentro la página de Datadis si los muestra, pero lo consultas varias veces unas llega hasta fecha del dia actual y otras se deja los últimos cinco días vacíos.  

Supongo que no es algo de la rama de desarrollo sino que es un problema de los servidores de api de Datadis o los Endesa en mi caso y que uno u otro tendría que dimensionar mejor su servidores.

 @uvejota **Lo importante que la implementación que has hecho para obtener datos de CUPS autorizados funciona correctamente.**
