### ISSUE TITLE
Problema a reiniciar

### ISSUE THREAD

**Issue by alexsalvo1** [uvejota/homeassistant-edata#80]
Despues de unos dias de funcionamiento, reiniciando HA veo este error:

https://datadis.es/api-private/api/get-max-power?cups=ESXXXXXXXXXXXXXXXXXX&distributorCode=8&startDate=2022/03&endDate=2022/02& returned Parámetro requerido en estado vacío, con formato erróneo, o con valores fuera de rango / Parámetro de ordenación erróneo with code 400

La integracion ya no sincroniza los datos con Datadis y la unica forma es borrar el fichero de storage y reiniciar. Parece un bug!

**Comment by PeRRo-RoJo** [comment]
Buenos días, me encuentro el mismo problema pero sin posibilidad de sincronización pese a borrar el fichero de storage.

Llevo un par de días intentando integrar el addon sin éxito. Me arroja este error además del anterior:

```
Logger: edata.connectors
Source: /usr/local/lib/python3.9/site-packages/edata/connectors.py:240
First occurred: 09:58:04 (1 occurrences)
Last logged: 09:58:04

DatadisConnector: it seems that oldest contract does not match with supply start date, requesting consumptions update from 2021-03-01 00:00:00 to 2022-03-10 00:00:00
```

**Comment by uvejota** [comment]
> Despues de unos dias de funcionamiento, reiniciando HA veo este error:
> 
> https://datadis.es/api-private/api/get-max-power?cups=ESXXXXXXXXXXXXXXXXXX&distributorCode=8&startDate=2022/03&endDate=2022/02& returned Parámetro requerido en estado vacío, con formato erróneo, o con valores fuera de rango / Parámetro de ordenación erróneo with code 400
> 
> La integracion ya no sincroniza los datos con Datadis y la unica forma es borrar el fichero de storage y reiniciar. Parece un bug!

No debería ocurrir más en la versión 2022.09.1 (aún está beta)

> Buenos días, me encuentro el mismo problema pero sin posibilidad de sincronización pese a borrar el fichero de storage.
> 
> Llevo un par de días intentando integrar el addon sin éxito. Me arroja este error además del anterior:
> 
> ```
> Logger: edata.connectors
> Source: /usr/local/lib/python3.9/site-packages/edata/connectors.py:240
> First occurred: 09:58:04 (1 occurrences)
> Last logged: 09:58:04
> 
> DatadisConnector: it seems that oldest contract does not match with supply start date, requesting consumptions update from 2021-03-01 00:00:00 to 2022-03-10 00:00:00
> ```

Ese error indica que tu distribuidora no ha registrado las fechas de inicio del suministro o contrato de forma coherente, y que está intentando obtener datos fuera de alguno de los dos rangos con el fin de explorar si existen estos datos.
