### ISSUE TITLE
Home Assistant reports alert message in the log 

### ISSUE THREAD

**Issue by epserra** [uvejota/homeassistant-edata#81]
Este error se originó a partir de una integración personalizada.

Logger: custom_components.edata.sensor
Source: helpers/config_validation.py:815
Integration: Integración edata (documentation, issues)
First occurred: 13:45:37 (6 occurrences)
Last logged: 16:13:55

The 'password' option near /config/configuration.yaml:37 is deprecated, please remove it from your configuration
The 'cups' option near /config/configuration.yaml:37 is deprecated, please remove it from your configuration
The 'username' option is deprecated, please remove it from your configuration
The 'password' option is deprecated, please remove it from your configuration
The 'cups' option is deprecated, please remove it from your configuration

Configuration in configuration.yaml
sensor:  
  platform: edata
  username: !secret my_datadis_uid 
  password: !secret my_datadis_pwd 
  cups: !secret my_endesa_cups
any suggestion?

**Comment by edufabra** [comment]
Lo que quiere decir este mensaje, es que como ahora la integración se configura visualmente, ya puedes borrar esos parámetros de tu configuration.yaml. Lo primero que hace cuando una integración pasa de configuración manual a configuración por la interface, es mirar si tienes esas entradas en la config y si es así, cogerlas y guardarlas en el storage de HA. Una vez hecho esto, ya se pueden borrar esas líneas del fichero de configuración.
