### ISSUE TITLE
¿Se puede guardar en variables/sensores de HA el consumo mensual de los meses anteriores?

### ISSUE THREAD

**Issue by ulesin** [uvejota/homeassistant-edata#82]
Buenas! Me gustaría ir guardando el histórico de consumo de todos los meses que sea posible. En el gráfico de apexcharts viene el siguiente código y produce el gráfico acumulado de los meses anteriores. ¿Se puede rescatar esa información para jugar con esos datos como variables? Gracias de antemano a todos y al creador de esta maravilla, por supuesto :).

`  - entity: sensor.edata_nk0f
    name: Valle
    color: green
    data_generator: |
      return hass.connection.sendMessagePromise({
      type: 'edata/consumptions/monthly', 
      scups: 'nk0f'}).then(
          (resp) => {
              return resp.map((data, index) => {
                return [new Date(data['datetime']).getTime(), data['value_p3_kWh']];
              });
          }
      );`

![image](https://user-images.githubusercontent.com/36470270/156743987-76b3216c-2c9b-4057-861a-e61233348b39.png)

**Comment by enriqueigl** [comment]
Hola Tienes la solucion? Puedes pasarme el codigo completo de este apex? Gracias. Un saludo

**Comment by uvejota** [comment]
La última versión de edata lo almacena en las estadísticas nativas de HA, igual puedes tirar por ahí.
