### ISSUE TITLE
Error tras actualizar el core a 2022.4 

### ISSUE THREAD

**Issue by jjvelar** [uvejota/homeassistant-edata#86]
Hola!

Tras actualizar el core a la versión 2022.4 tengo este error en el log: "Loading edata sensor via platform setup is deprecated. It will be imported into Home Assistant integration. Please remove it from your configuration".

Aquí os paso el mensaje de error completo:

This error originated from a custom integration.

Logger: custom_components.edata.sensor
Source: custom_components/edata/sensor.py:86
Integration: edata integration (documentation, issues)
First occurred: 10:21:03 AM (1 occurrences)
Last logged: 10:21:03 AM

Loading edata sensor via platform setup is deprecated. It will be imported into Home Assistant integration. Please remove it from your configuration

**Comment by dragonjon** [comment]
Lo que quiere decir este mensaje, es que como ahora la integración se configura visualmente, ya puedes borrar esos parámetros de tu configuration.yaml. Lo primero que hace cuando una integración pasa de configuración manual a configuración por la interface, es mirar si tienes esas entradas en la config y si es así, cogerlas y guardarlas en el storage de HA. Una vez hecho esto, ya se pueden borrar esas líneas del fichero de configuración.

**Comment by uvejota** [comment]
@dragonjon ha dado con el clavo :) 

Cierro por ser ordenados.
