### ISSUE TITLE
No lee valores Maximetro

### ISSUE THREAD

**Issue by cfjuan** [uvejota/homeassistant-edata#88]
Ante todo gracias por el addon. Os cuento... tengo la ultima version del addon y la de Home, y cuando trato de acceder a los consumos másximos no hay manera. En la integración dentro de los atributos, aparecen todos los datos, menos los de los maxímetros, aunque en la página de Datadis si que aparecen. Alguna idea de que puede estar pasando. Un saludo y gracias

**Comment by rauljerico** [comment]
A mi también se me queda en estado "Loading"

**Comment by dragonjon** [comment]
En consumo mensual editando la tarjeta, hay que cambiar la linea 20
de extend_to_end: false a extend_to: end
En maximetro igual pero en la linea 15

**Comment by cfjuan** [comment]
Funcionando. Gracias
