### ISSUE TITLE
Wiki -> Ejemplo consumo mensual al usar apexcharts-card, la opción extend_to_end ya no es válida

### ISSUE THREAD

**Issue by Danieldiazi** [uvejota/homeassistant-edata#89]
Hola:
Fantástica herramienta. 

En la wiki, y en concreto en la sección "Uso", aparece un ejemplo de consumo mensual, en concreto para usar la apexcharts-card

Desde la actualización a la versión 2.0.0, la opción:
  extend_to_end: false

ya no existe, y por lo que he leido, debería ser:

extend_to: "end"

Lo comento porque entiendo que a medida que la gente se vaya actualizando a la versión 2.0.0 o superior le empezará a fallar.

**Comment by SmilinStanSStanman** [comment]
Efectivamente, acabo de actualizar y con tu pequeño cambio la tarjeta esta de nuevo en marcha. Gracias!

**Comment by alexsalvo1** [comment]
Yo había eliminado la opción.
Estaría bien actualizar la documentación!

**Comment by dragonjon** [comment]
En consumo mensual editando la tarjeta, hay que cambiar la linea 20
de extend_to_end: false a extend_to: end
En maximetro igual pero en la linea 15

**Comment by uvejota** [comment]
Actualizado en la Wiki, ¡gracias!
