### ISSUE TITLE
Sigue aumentando kWh consumidos día anterior

### ISSUE THREAD

**Issue by joseal70** [uvejota/homeassistant-edata#9]
Hola,
Estoy viendo que los kWh consumidos ayer siguen aumentando hoy, es como si le sumase los de hoy.

![Screenshot_20210830-191140](https://user-images.githubusercontent.com/63608768/131379155-e9e1719b-b034-4737-bb83-f32beba8317e.jpg)

Después de 2 horas:
![Screenshot_20210830-215003](https://user-images.githubusercontent.com/63608768/131396974-daf69bb2-7986-4618-a412-2f7aa469febe.jpg)

![Screenshot_20210830-191107](https://user-images.githubusercontent.com/63608768/131379224-834fd856-2046-47d5-8374-020bf4a8680a.jpg)

La version que tengo instalada es la v0.1.7-beta.7

Muchas gracias por el complemento uvejota

**Comment by uvejota** [comment]
Hola, gracias por el aviso, creo haberlo solucionado en: v0.1.7-beta.11

Si por algún motivo experimentas cosas raras en el histórico de consumos, o sigue habiendo "duplicados" en el pasado, elimina el fichero `/config/.storage/edata.storage_XXXX` y recarga el componente, eso lo solucionará :-)

Un saludo, ya me dices.

**Comment by joseal70** [comment]
Con la nueva versión y borrando el archivo edata.storage_XXXX se ha corregido.

Muchas gracias.
