### ISSUE TITLE
Missing consumptions when no data exists

### ISSUE THREAD

**Issue by fherreror** [uvejota/homeassistant-edata#92]
Ante todo, gracias por la integración. He tenido muchos problemas para que se actualizara, pero borrando de .storage, parece que al final ha vuelto a actualizar. A ver si sigue.

He detectado que cuando el consumo es 0 en un periodo (0 real, estuve de obras y tengo consumo 0 durante bastantes días en que la luz estuvo cortada 100%), la integración no lo detecta como 0, sino como un Missing Consumption, es decir, un consumo para el que Datadis no ha ofrecido dato, por lo que indica que volverá a intentar descargarlo en el futuro.
Esto es un problema porque significa que 1 vez por hora va a intentar descargar una serie de consumos que nunca va a encontrar, ya que son 0.

Copio lo que dice el log:

DatadisConnector: still missing the following consumption ranges [{'from': datetime.datetime(2021, 10, 7, 15, 0), 'to': datetime.datetime(2021, 10, 8, 9, 0)}, {'from': datetime.datetime(2021, 10, 8, 16, 0), 'to': datetime.datetime(2021, 10, 11, 8, 0)}, {'from': datetime.datetime(2021, 10, 11, 16, 0), 'to': datetime.datetime(2021, 10, 13, 8, 0)}, {'from': datetime.datetime(2021, 10, 13, 12, 0), 'to': datetime.datetime(2021, 10, 18, 10, 0)}, {'from': datetime.datetime(2021, 10, 18, 11, 0), 'to': datetime.datetime(2021, 10, 20, 9, 0)}, {'from': datetime.datetime(2021, 10, 20, 16, 0), 'to': datetime.datetime(2021, 10, 21, 8, 0)}, {'from': datetime.datetime(2021, 10, 21, 16, 0), 'to': datetime.datetime(2021, 10, 22, 8, 0)}, {'from': datetime.datetime(2021, 10, 22, 16, 0), 'to': datetime.datetime(2021, 10, 25, 9, 0)}, {'from': datetime.datetime(2021, 10, 25, 16, 0), 'to': datetime.datetime(2021, 10, 26, 9, 0)}, {'from': datetime.datetime(2021, 10, 26, 16, 0), 'to': datetime.datetime(2021, 10, 27, 8, 0)}, {'from': datetime.datetime(2021, 10, 27, 16, 0), 'to': datetime.datetime(2021, 10, 28, 8, 0)}, {'from': datetime.datetime(2021, 10, 28, 15, 0), 'to': datetime.datetime(2021, 11, 5, 13, 0)}, {'from': datetime.datetime(2021, 11, 5, 16, 0), 'to': datetime.datetime(2021, 11, 8, 8, 0)}, {'from': datetime.datetime(2021, 11, 8, 12, 0), 'to': datetime.datetime(2021, 11, 9, 8, 0)}, {'from': datetime.datetime(2021, 11, 16, 17, 0), 'to': datetime.datetime(2021, 11, 17, 10, 0)}, {'from': datetime.datetime(2022, 5, 2, 23, 0), 'to': datetime.datetime(2022, 5, 3, 21, 47, 16, 111140)}], will try again later

Todos los periodos salvo el último (que es, en verdad, lo que sí falta por descargar), son periodos en los que el consumo es 0, no periodos missing.

Quizás al descargar se podría comprobar si es 0 o error/null, y en caso de que sea 0 de verdad, no registrarlo como un periodo missing.
Otra opción que se me ocurre es que hubiera una opción de configuración en que, una vez hecha la descarga inicial, ponerle una fecha a partir de la cual descargar los datos, de manera que no esté intentando descargar datos antiguos continuamente.

Espero que mi aportación sirva para mejorar esta integración.

Gracias de nuevo por el trabajo.

**Comment by mcrodrig** [comment]
Buenos días,

Primero agradecer la integración y el esfuerzo y dedicación que hay detrás de ella.

Mi problema es el mismo pero en una vivienda nueva, donde en algunos momentos no hubo consumo. En mi caso junio y julio de 2021. El log es el siguiente:
`2022-05-05 10:34:23 WARNING (SyncWorker_16) [edata.connectors] DatadisConnector: still missing the following consumption ranges [{'from': datetime.datetime(2021, 5, 1, 0, 0), 'to': datetime.datetime(2021, 6, 14, 10, 0)}, {'from': datetime.datetime(2021, 6, 14, 12, 0), 'to': datetime.datetime(2021, 6, 14, 21, 0)}, {'from': datetime.datetime(2021, 6, 14, 21, 0), 'to': datetime.datetime(2021, 6, 15, 9, 0)}, {'from': datetime.datetime(2021, 6, 16, 16, 0), 'to': datetime.datetime(2021, 6, 17, 8, 0)}, {'from': datetime.datetime(2021, 6, 17, 18, 0), 'to': datetime.datetime(2021, 6, 19, 9, 0)}, {'from': datetime.datetime(2021, 6, 19, 12, 0), 'to': datetime.datetime(2021, 6, 20, 12, 0)}, {'from': datetime.datetime(2021, 6, 20, 12, 0), 'to': datetime.datetime(2021, 6, 21, 8, 0)}, {'from': datetime.datetime(2021, 6, 21, 20, 0), 'to': datetime.datetime(2021, 6, 22, 7, 0)}, {'from': datetime.datetime(2021, 6, 22, 9, 0), 'to': datetime.datetime(2021, 6, 23, 9, 0)}, {'from': datetime.datetime(2021, 6, 23, 18, 0), 'to': datetime.datetime(2021, 6, 24, 9, 0)}, {'from': datetime.datetime(2021, 6, 25, 14, 0), 'to': datetime.datetime(2021, 6, 26, 17, 0)}, {'from': datetime.datetime(2021, 6, 26, 19, 0), 'to': datetime.datetime(2021, 6, 28, 9, 0)}, {'from': datetime.datetime(2021, 6, 28, 19, 0), 'to': datetime.datetime(2021, 6, 29, 8, 0)}, {'from': datetime.datetime(2021, 6, 29, 17, 0), 'to': datetime.datetime(2021, 6, 30, 9, 0)}, {'from': datetime.datetime(2021, 7, 1, 18, 0), 'to': datetime.datetime(2021, 7, 2, 8, 0)}, {'from': datetime.datetime(2021, 7, 2, 17, 0), 'to': datetime.datetime(2021, 7, 3, 8, 0)}, {'from': datetime.datetime(2021, 7, 3, 20, 0), 'to': datetime.datetime(2021, 7, 4, 13, 0)}, {'from': datetime.datetime(2021, 7, 4, 14, 0), 'to': datetime.datetime(2021, 7, 5, 9, 0)}, {'from': datetime.datetime(2021, 7, 5, 13, 0), 'to': datetime.datetime(2021, 7, 6, 9, 0)}, {'from': datetime.datetime(2021, 7, 6, 18, 0), 'to': datetime.datetime(2021, 7, 7, 8, 0)}, {'from': datetime.datetime(2022, 5, 3, 23, 0), 'to': datetime.datetime(2022, 5, 5, 10, 32, 33, 3817)}], will try again later`

Las dos soluciones planteadas me parecen adecuadas y podriamos añadir la opción en un fichero de configuración de eliminar intervalos de fechas. 

De nuevo agradecer el trabajo y esfuerzo.

**Comment by uvejota** [comment]
Voy a echarle un ojo a esto, claramente está de mi lado :)

**Comment by Danieldiazi** [comment]
En mi caso también aparecen también esos errores, pero en este caso sí debería haber consumo:
` Still missing the following consumption ranges [{'from': datetime.datetime(2022, 1, 24, 7, 0), 'to': datetime.datetime(2022, 1, 25, 0, 0)}, {'from': datetime.datetime(2022, 9, 8, 23, 0), 'to': datetime.datetime(2022, 9, 9, 23, 59)}], will try again later `

**Comment by uvejota** [comment]
@fherreror @mcrodrig he estado haciendo algunas pruebecillas y en ciertos casos es imposible saber si el consumo ha sido 0 real, o simplemente es un error... así que la única solución viable es permitir al usuario eliminar rangos, pero esto es tedioso... tengo que estudiarlo

@Danieldiazi a veces la API no devuelve datos para ciertos rangos y la integración insiste periódicamente, con el tiempo suelen recibirse (o no, no encuentro el patrón), esto es cosa de Datadis, no tengo mucho que hacer.

**Comment by Danieldiazi** [comment]
> @fherreror @mcrodrig he estado haciendo algunas pruebecillas y en ciertos casos es imposible saber si el consumo ha sido 0 real, o simplemente es un error... así que la única solución viable es permitir al usuario eliminar rangos, pero esto es tedioso... tengo que estudiarlo
> 
> @Danieldiazi a veces la API no devuelve datos para ciertos rangos y la integración insiste periódicamente, con el tiempo suelen recibirse (o no, no encuentro el patrón), esto es cosa de Datadis, no tengo mucho que hacer.

@uvejota sólo era por aportar información, entiendo que es más de la información que proporciona Datadis, si no vienen los datos, poco puede hacer tu integración xD

**Comment by fherreror** [comment]
> @fherreror @mcrodrig he estado haciendo algunas pruebecillas y en ciertos casos es imposible saber si el consumo ha sido 0 real, o simplemente es un error... así que la única solución viable es permitir al usuario eliminar rangos, pero esto es tedioso... tengo que estudiarlo
> 
> @Danieldiazi a veces la API no devuelve datos para ciertos rangos y la integración insiste periódicamente, con el tiempo suelen recibirse (o no, no encuentro el patrón), esto es cosa de Datadis, no tengo mucho que hacer.

Yo lo que hice al final fue ir a la base de datos y añadir uno por uno esos consumos como 0.
Otra opción sería que en algún sitio mostrara los rangos missing y el usuario pudiera asignarles un valor automáticamente. O que si tras x intentos sin conseguir datos, en caso de que sean rangos con más de x tiempo de antigüedad y siempre que haya rangos posteriores con datos, se rellenaran con 0

**Comment by uvejota** [comment]
Estoy pensando que una opción es "saltar" fechas que han errado al menos N veces. Y que N sea configurable... 

Esto ayudaría a resolver otros problemillas, aunque tiene riesgos.

**Comment by Danieldiazi** [comment]
> Estoy pensando que una opción es "saltar" fechas que han errado al menos N veces. Y que N sea configurable...
> 
> Esto ayudaría a resolver otros problemillas, aunque tiene riesgos.

Lo malo es que un fallo puntual de datadis haga que se llegue a ese valor "N", y luego una vez que funcione datadis, la integración ya no bajaría los datos porque ha superado el valor "N". Eso implicaría igual meter una opción de resetear los que han superado ese umbral. Igual hace todo algo más complejo, pero no tiene mala pinta !

**Comment by fherreror** [comment]
Añádele un filtro de fecha (es decir, datos de más de x tiempo, por ejemplo, de más de uno o dos meses) y comprobar que haya rango posteriores descargados.
Si fuera un error de datadis, no habrá rangos posteriores, pero si hay rangos posteriores, se ha intentado bajar varias veces y los rangos tienen ya un tiempo, es probable que sea porque no hay consumo en los mismos.
Eso o permitir sustituir manualmente rangos sin datos.

**Comment by andresledo** [comment]
Tengo el mismo problema "creo", un piso de nueva construcción que no recibe ningún datos a pesar de que ya tiene datos de al menos un mes. 

Some stats are missing for ww0f
Some data is missing, will try to fetch later
