### ISSUE TITLE
extend_to_end deprecated

### ISSUE THREAD

**Issue by sagatxxx** [uvejota/homeassistant-edata#93]
hello, 
just one thing:
extend_to_end has been deprecated, and with it, the graphics do not work in home assistant. Must be "extend_to"

Thanks

**Comment by dragonjon** [comment]
In monthly consumption editing the card, you have to change line 20
from extend_to_end: false to extend_to: end
In maximeter the same but in line 15

**Comment by uvejota** [comment]
Actualizado en la wiki, gracias por el research :)
