### ISSUE TITLE
Error en las gráficas con el nuevo apexchart-card (HACS)

### ISSUE THREAD

**Issue by mabusdogma** [uvejota/homeassistant-edata#94]
Hola, cuando pongo el nuevo apexchart-card 2.0.1, los gráficos mensuales desaparecen, y simplemente me marca error.
De momento lo he solucionado poniendo la versión anterior de apexchart-card (1.9.0).
Hay alguna forma de solucionarlo para poner la última versión?
Saludos

**Comment by Siroguh** [comment]
Probablemente sea este problema. #93

**Comment by dragonjon** [comment]
En consumo mensual editando la tarjeta, hay que cambiar la linea 20
de extend_to_end: false a extend_to: end
En maximetro igual pero en la linea 15

**Comment by mabusdogma** [comment]
Perfecto, gracias!

**Comment by uvejota** [comment]
Actualizado en la wiki, gracias por el research :)
