### ISSUE TITLE
numpy version after python 3.10 

### ISSUE THREAD

**Issue by miguelfrancisco85** [uvejota/homeassistant-edata#98]
Hola,

Parece que hay un problema de dependencias de numpy al actualizar HA a la version 2022.7 ya que se hace una actualizacion de la version de python a la 3.10

**Comment by fherreror** [comment]
Alguien puede confirmar si funciona o no al actualizar a la 2022.7?

**Comment by pove** [comment]
Pues yo actualicé a la 2022.7.5 el día 17 y veo datos de edata hasta el día 22. Pero desde el día 22, en adelante, nada. En el log veo un error 500 al llamar a la API, pero juraría que es un error que ya daba antes periódicamente:

![IMG_20220726_094901](https://user-images.githubusercontent.com/10817653/180953358-5016d42f-5305-474e-a9c2-0bed5f44f968.jpg)

**Comment by fherreror** [comment]
A mí en la 2022.6 me ha pasado lo mismo, desde el 22/7 me dejó de dar lecturas con error 500, pero he recargado la integración, reiniciado y ha cogido ya las lecturas. Cada x tiempo suele pasar.
