### ISSUE TITLE
ERROR (SyncWorker_18) [edata.connectors] CUPS XXXX not found in ['ES....YYYY'], wrong CUPS?

### ISSUE THREAD

**Issue by javferper** [uvejota/homeassistant-edata#99]
Hola, tengo dos instancias de HA independientes en la que en cada una de ellas tengo integrado edata con un cups diferente. El problema es que en el log saca el siguiente registro ERROR (SyncWorker_18) [edata.connectors] CUPS XXXX not found in ['ES......YYYY'], wrong CUPS?   y no se descarga los datos del cups xxxx
Si vuelvo a recargar la integración en el HA donde está el CUPS XXXX  se descarga los datos pero ahora en el otro HA saca el error del registro y viceversa. 
¿Hay alguna manera de solucionar el problema?
Un saludo y muchas gracias.

**Comment by uvejota** [comment]
Es el primer caso que veo, no tengo caso de que sea un bug (tengo varias instancias corriendo con varios cups, e incluso varios cups en la misma instancia sin problema), ¿Seguro que no es problema de configuración?
